// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        imgRB_dout,
        imgRB_num_data_valid,
        imgRB_fifo_cap,
        imgRB_empty_n,
        imgRB_read,
        imgRgb_din,
        imgRgb_num_data_valid,
        imgRgb_fifo_cap,
        imgRgb_full_n,
        imgRgb_write,
        p_0_0_01183_217801810_lcssa1846_i,
        p_0_0_01184_217781808_lcssa1844_i,
        p_0_0_01185_217761806_lcssa1842_i,
        p_0_2_0_0_011511803_lcssa1840_i,
        p_0_1_0_0_011501801_lcssa1838_i,
        p_0_0_0_0_011491799_lcssa1836_i,
        p_0_0_0116117861798_lcssa1834_i,
        p_0_0_0116217841796_lcssa1832_i,
        p_0_0_0116317821794_lcssa1830_i,
        p_0_2_0_0_011571710_lcssa1752_i,
        p_0_1_0_0_011561707_lcssa1750_i,
        p_0_0_0_0_011551704_lcssa1748_i,
        loopWidth_i,
        empty_52,
        xor_i,
        cmp203_i,
        empty,
        cmp59_i,
        p_0_0_01183_217801809_i_out,
        p_0_0_01183_217801809_i_out_ap_vld,
        p_0_0_01184_217781807_i_out,
        p_0_0_01184_217781807_i_out_ap_vld,
        p_0_0_01185_217761805_i_out,
        p_0_0_01185_217761805_i_out_ap_vld,
        right_2_i_out,
        right_2_i_out_ap_vld,
        right_1_i_out,
        right_1_i_out_ap_vld,
        right_i_out,
        right_i_out_ap_vld,
        p_0_0_0116117861797_i_out,
        p_0_0_0116117861797_i_out_ap_vld,
        p_0_0_0116217841795_i_out,
        p_0_0_0116217841795_i_out_ap_vld,
        p_0_0_0116317821793_i_out,
        p_0_0_0116317821793_i_out_ap_vld,
        p_0_2_0_0_011571712_i_out,
        p_0_2_0_0_011571712_i_out_ap_vld,
        p_0_1_0_0_011561709_i_out,
        p_0_1_0_0_011561709_i_out_ap_vld,
        p_0_0_0_0_011551706_i_out,
        p_0_0_0_0_011551706_i_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [29:0] imgRB_dout;
input  [2:0] imgRB_num_data_valid;
input  [2:0] imgRB_fifo_cap;
input   imgRB_empty_n;
output   imgRB_read;
output  [29:0] imgRgb_din;
input  [2:0] imgRgb_num_data_valid;
input  [2:0] imgRgb_fifo_cap;
input   imgRgb_full_n;
output   imgRgb_write;
input  [9:0] p_0_0_01183_217801810_lcssa1846_i;
input  [9:0] p_0_0_01184_217781808_lcssa1844_i;
input  [9:0] p_0_0_01185_217761806_lcssa1842_i;
input  [9:0] p_0_2_0_0_011511803_lcssa1840_i;
input  [9:0] p_0_1_0_0_011501801_lcssa1838_i;
input  [9:0] p_0_0_0_0_011491799_lcssa1836_i;
input  [9:0] p_0_0_0116117861798_lcssa1834_i;
input  [9:0] p_0_0_0116217841796_lcssa1832_i;
input  [9:0] p_0_0_0116317821794_lcssa1830_i;
input  [9:0] p_0_2_0_0_011571710_lcssa1752_i;
input  [9:0] p_0_1_0_0_011561707_lcssa1750_i;
input  [9:0] p_0_0_0_0_011551704_lcssa1748_i;
input  [10:0] loopWidth_i;
input  [0:0] empty_52;
input  [14:0] xor_i;
input  [0:0] cmp203_i;
input  [10:0] empty;
input  [0:0] cmp59_i;
output  [9:0] p_0_0_01183_217801809_i_out;
output   p_0_0_01183_217801809_i_out_ap_vld;
output  [9:0] p_0_0_01184_217781807_i_out;
output   p_0_0_01184_217781807_i_out_ap_vld;
output  [9:0] p_0_0_01185_217761805_i_out;
output   p_0_0_01185_217761805_i_out_ap_vld;
output  [9:0] right_2_i_out;
output   right_2_i_out_ap_vld;
output  [9:0] right_1_i_out;
output   right_1_i_out_ap_vld;
output  [9:0] right_i_out;
output   right_i_out_ap_vld;
output  [9:0] p_0_0_0116117861797_i_out;
output   p_0_0_0116117861797_i_out_ap_vld;
output  [9:0] p_0_0_0116217841795_i_out;
output   p_0_0_0116217841795_i_out_ap_vld;
output  [9:0] p_0_0_0116317821793_i_out;
output   p_0_0_0116317821793_i_out_ap_vld;
output  [9:0] p_0_2_0_0_011571712_i_out;
output   p_0_2_0_0_011571712_i_out_ap_vld;
output  [9:0] p_0_1_0_0_011561709_i_out;
output   p_0_1_0_0_011561709_i_out_ap_vld;
output  [9:0] p_0_0_0_0_011551706_i_out;
output   p_0_0_0_0_011551706_i_out_ap_vld;

reg ap_idle;
reg p_0_0_01183_217801809_i_out_ap_vld;
reg p_0_0_01184_217781807_i_out_ap_vld;
reg p_0_0_01185_217761805_i_out_ap_vld;
reg right_2_i_out_ap_vld;
reg right_1_i_out_ap_vld;
reg right_i_out_ap_vld;
reg p_0_0_0116117861797_i_out_ap_vld;
reg p_0_0_0116217841795_i_out_ap_vld;
reg p_0_0_0116317821793_i_out_ap_vld;
reg p_0_2_0_0_011571712_i_out_ap_vld;
reg p_0_1_0_0_011561709_i_out_ap_vld;
reg p_0_0_0_0_011551706_i_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln881_reg_1921;
reg   [0:0] icmp_ln891_reg_1930;
wire   [0:0] cmp59_i_read_reg_1910;
reg    ap_predicate_op78_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] and_ln1052_reg_1957;
reg   [0:0] and_ln1052_reg_1957_pp0_iter5_reg;
reg    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln881_fu_574_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    imgRB_blk_n;
wire    ap_block_pp0_stage0;
reg    imgRgb_blk_n;
reg   [9:0] pix_8_reg_395;
reg   [9:0] pix_8_reg_395_pp0_iter4_reg;
reg    ap_block_pp0_stage0_11001;
reg   [9:0] pix_8_reg_395_pp0_iter5_reg;
reg   [9:0] pix_7_reg_405;
reg   [9:0] pix_7_reg_405_pp0_iter4_reg;
reg   [9:0] pix_7_reg_405_pp0_iter5_reg;
reg   [9:0] pix_reg_415;
reg   [9:0] pix_reg_415_pp0_iter4_reg;
reg   [9:0] pix_reg_415_pp0_iter5_reg;
reg   [0:0] icmp_ln881_reg_1921_pp0_iter1_reg;
reg   [0:0] icmp_ln881_reg_1921_pp0_iter2_reg;
reg   [0:0] icmp_ln881_reg_1921_pp0_iter3_reg;
reg   [0:0] icmp_ln881_reg_1921_pp0_iter4_reg;
wire   [10:0] x_8_fu_580_p2;
reg   [10:0] x_8_reg_1925;
wire   [0:0] icmp_ln891_fu_590_p2;
reg   [0:0] icmp_ln891_reg_1930_pp0_iter1_reg;
reg   [0:0] icmp_ln891_reg_1930_pp0_iter2_reg;
wire   [0:0] cmp161_i_fu_596_p2;
reg   [0:0] cmp161_i_reg_1934;
reg   [0:0] cmp161_i_reg_1934_pp0_iter1_reg;
reg   [0:0] cmp161_i_reg_1934_pp0_iter2_reg;
wire   [0:0] icmp_ln1014_fu_618_p2;
reg   [0:0] icmp_ln1014_reg_1950;
reg   [0:0] icmp_ln1014_reg_1950_pp0_iter1_reg;
reg   [0:0] icmp_ln1014_reg_1950_pp0_iter2_reg;
reg   [0:0] icmp_ln1014_reg_1950_pp0_iter3_reg;
reg   [0:0] icmp_ln1014_reg_1950_pp0_iter4_reg;
reg   [0:0] icmp_ln1014_reg_1950_pp0_iter5_reg;
wire   [0:0] and_ln1052_fu_630_p2;
reg   [0:0] and_ln1052_reg_1957_pp0_iter1_reg;
reg   [0:0] and_ln1052_reg_1957_pp0_iter2_reg;
reg   [0:0] and_ln1052_reg_1957_pp0_iter3_reg;
reg   [0:0] and_ln1052_reg_1957_pp0_iter4_reg;
reg   [10:0] lineBuffer_addr_reg_1961;
reg   [10:0] lineBuffer_2_addr_reg_1967;
reg   [10:0] lineBuffer_2_addr_reg_1967_pp0_iter2_reg;
reg   [29:0] InPix_reg_1973;
wire   [9:0] trunc_ln913_fu_646_p1;
wire   [9:0] trunc_ln902_fu_670_p1;
reg   [9:0] trunc_ln902_reg_1993;
reg   [9:0] tmp_i1_reg_2002;
reg   [9:0] tmp_1_i2_reg_2011;
reg   [9:0] p_0_0_0116317821793_i_load_reg_2020;
reg   [9:0] p_0_0_0116317821793_i_load_reg_2020_pp0_iter4_reg;
reg   [9:0] p_0_0_0116217841795_i_load_reg_2026;
reg   [9:0] p_0_0_0116217841795_i_load_reg_2026_pp0_iter4_reg;
reg   [9:0] p_0_0_0116117861797_i_load_reg_2032;
reg   [9:0] p_0_0_0116117861797_i_load_reg_2032_pp0_iter4_reg;
reg   [9:0] right_3_reg_2038;
reg   [9:0] right_3_reg_2038_pp0_iter4_reg;
reg   [9:0] right_4_reg_2043;
reg   [9:0] right_4_reg_2043_pp0_iter4_reg;
reg   [9:0] right_5_reg_2048;
reg   [9:0] right_5_reg_2048_pp0_iter4_reg;
reg   [9:0] p_0_0_01185_217761805_i_load_reg_2053;
reg   [9:0] p_0_0_01185_217761805_i_load_reg_2053_pp0_iter4_reg;
reg   [9:0] p_0_0_01184_217781807_i_load_reg_2059;
reg   [9:0] p_0_0_01184_217781807_i_load_reg_2059_pp0_iter4_reg;
reg   [9:0] p_0_0_01183_217801809_i_load_reg_2065;
reg   [9:0] p_0_0_01183_217801809_i_load_reg_2065_pp0_iter4_reg;
reg   [9:0] p_0_0_0_0_011551706_i_load_reg_2071;
reg   [9:0] p_0_0_0_0_011551706_i_load_reg_2071_pp0_iter4_reg;
reg   [9:0] p_0_1_0_0_011561709_i_load_reg_2077;
reg   [9:0] p_0_1_0_0_011561709_i_load_reg_2077_pp0_iter4_reg;
reg   [9:0] p_0_2_0_0_011571712_i_load_reg_2083;
reg   [9:0] p_0_2_0_0_011571712_i_load_reg_2083_pp0_iter4_reg;
wire   [9:0] select_ln957_3_fu_778_p3;
wire   [9:0] select_ln957_4_fu_784_p3;
wire   [9:0] select_ln957_5_fu_790_p3;
wire   [9:0] select_ln957_6_fu_796_p3;
wire   [9:0] select_ln957_7_fu_803_p3;
wire   [9:0] select_ln957_8_fu_810_p3;
wire   [9:0] select_ln957_9_fu_817_p3;
wire   [9:0] select_ln957_10_fu_824_p3;
wire   [9:0] select_ln957_11_fu_831_p3;
wire   [10:0] sub_ln1027_fu_1101_p2;
reg   [10:0] sub_ln1027_reg_2134;
wire   [9:0] trunc_ln61_7_fu_1107_p1;
reg   [9:0] trunc_ln61_7_reg_2139;
wire   [9:0] sub_ln61_7_fu_1111_p2;
reg   [9:0] sub_ln61_7_reg_2144;
wire   [10:0] sub_ln1028_fu_1125_p2;
reg   [10:0] sub_ln1028_reg_2149;
wire   [9:0] trunc_ln61_8_fu_1131_p1;
reg   [9:0] trunc_ln61_8_reg_2154;
wire   [9:0] sub_ln61_8_fu_1135_p2;
reg   [9:0] sub_ln61_8_reg_2159;
wire   [10:0] add_ln1030_fu_1149_p2;
reg   [10:0] add_ln1030_reg_2164;
wire   [10:0] add_ln1030_2_fu_1163_p2;
reg   [10:0] add_ln1030_2_reg_2169;
wire   [11:0] add_ln1033_fu_1189_p2;
reg   [11:0] add_ln1033_reg_2174;
wire   [11:0] add_ln1034_fu_1215_p2;
reg   [11:0] add_ln1034_reg_2181;
wire   [11:0] add_ln1039_fu_1241_p2;
reg   [11:0] add_ln1039_reg_2188;
reg   [10:0] trunc_ln1039_2_i_reg_2194;
wire   [11:0] add_ln1040_fu_1283_p2;
reg   [11:0] add_ln1040_reg_2199;
reg   [10:0] trunc_ln1040_2_i_reg_2205;
wire   [13:0] r_2_fu_1591_p2;
reg   [13:0] r_2_reg_2210;
wire   [13:0] b_2_fu_1609_p2;
reg   [13:0] b_2_reg_2215;
reg   [0:0] tmp_22_reg_2221;
reg   [3:0] tmp_23_reg_2227;
reg   [3:0] tmp_25_reg_2232;
reg    ap_condition_exit_pp0_iter3_stage0;
wire   [10:0] lineBuffer_2_address0;
wire   [10:0] lineBuffer_2_address1;
wire   [29:0] lineBuffer_2_q1;
wire   [10:0] lineBuffer_address0;
wire   [10:0] lineBuffer_address1;
wire   [29:0] lineBuffer_q1;
wire   [9:0] ap_phi_reg_pp0_iter0_p_0_0_01183_21780_ph_i_reg_368;
reg   [9:0] ap_phi_reg_pp0_iter1_p_0_0_01183_21780_ph_i_reg_368;
reg   [9:0] ap_phi_reg_pp0_iter2_p_0_0_01183_21780_ph_i_reg_368;
reg   [9:0] ap_phi_reg_pp0_iter3_p_0_0_01183_21780_ph_i_reg_368;
wire   [9:0] ap_phi_reg_pp0_iter0_p_0_0_01184_21778_ph_i_reg_377;
reg   [9:0] ap_phi_reg_pp0_iter1_p_0_0_01184_21778_ph_i_reg_377;
reg   [9:0] ap_phi_reg_pp0_iter2_p_0_0_01184_21778_ph_i_reg_377;
reg   [9:0] ap_phi_reg_pp0_iter3_p_0_0_01184_21778_ph_i_reg_377;
wire   [9:0] ap_phi_reg_pp0_iter0_p_0_0_01185_21776_ph_i_reg_386;
reg   [9:0] ap_phi_reg_pp0_iter1_p_0_0_01185_21776_ph_i_reg_386;
reg   [9:0] ap_phi_reg_pp0_iter2_p_0_0_01185_21776_ph_i_reg_386;
reg   [9:0] ap_phi_reg_pp0_iter3_p_0_0_01185_21776_ph_i_reg_386;
reg   [9:0] ap_phi_mux_pix_8_phi_fu_398_p4;
wire   [9:0] select_ln957_2_fu_771_p3;
wire   [9:0] ap_phi_reg_pp0_iter3_pix_8_reg_395;
reg   [9:0] ap_phi_mux_pix_7_phi_fu_408_p4;
wire   [9:0] select_ln957_1_fu_764_p3;
wire   [9:0] ap_phi_reg_pp0_iter3_pix_7_reg_405;
reg   [9:0] ap_phi_mux_pix_phi_fu_418_p4;
wire   [9:0] select_ln957_fu_757_p3;
wire   [9:0] ap_phi_reg_pp0_iter3_pix_reg_415;
wire   [9:0] ap_phi_reg_pp0_iter0_down_2_reg_425;
reg   [9:0] ap_phi_reg_pp0_iter1_down_2_reg_425;
reg   [9:0] ap_phi_reg_pp0_iter2_down_2_reg_425;
reg   [9:0] ap_phi_reg_pp0_iter3_down_2_reg_425;
reg   [9:0] ap_phi_reg_pp0_iter4_down_2_reg_425;
wire   [9:0] ap_phi_reg_pp0_iter0_down_1_reg_434;
reg   [9:0] ap_phi_reg_pp0_iter1_down_1_reg_434;
reg   [9:0] ap_phi_reg_pp0_iter2_down_1_reg_434;
reg   [9:0] ap_phi_reg_pp0_iter3_down_1_reg_434;
reg   [9:0] ap_phi_reg_pp0_iter4_down_1_reg_434;
wire   [9:0] ap_phi_reg_pp0_iter0_down_reg_443;
reg   [9:0] ap_phi_reg_pp0_iter1_down_reg_443;
reg   [9:0] ap_phi_reg_pp0_iter2_down_reg_443;
reg   [9:0] ap_phi_reg_pp0_iter3_down_reg_443;
reg   [9:0] ap_phi_reg_pp0_iter4_down_reg_443;
wire   [9:0] ap_phi_reg_pp0_iter0_left_2_reg_452;
reg   [9:0] ap_phi_reg_pp0_iter1_left_2_reg_452;
reg   [9:0] ap_phi_reg_pp0_iter2_left_2_reg_452;
reg   [9:0] ap_phi_reg_pp0_iter3_left_2_reg_452;
reg   [9:0] ap_phi_reg_pp0_iter4_left_2_reg_452;
wire   [9:0] ap_phi_reg_pp0_iter0_left_1_reg_461;
reg   [9:0] ap_phi_reg_pp0_iter1_left_1_reg_461;
reg   [9:0] ap_phi_reg_pp0_iter2_left_1_reg_461;
reg   [9:0] ap_phi_reg_pp0_iter3_left_1_reg_461;
reg   [9:0] ap_phi_reg_pp0_iter4_left_1_reg_461;
wire   [9:0] ap_phi_reg_pp0_iter0_left_reg_470;
reg   [9:0] ap_phi_reg_pp0_iter1_left_reg_470;
reg   [9:0] ap_phi_reg_pp0_iter2_left_reg_470;
reg   [9:0] ap_phi_reg_pp0_iter3_left_reg_470;
reg   [9:0] ap_phi_reg_pp0_iter4_left_reg_470;
wire   [9:0] ap_phi_reg_pp0_iter0_up_2_reg_479;
reg   [9:0] ap_phi_reg_pp0_iter1_up_2_reg_479;
reg   [9:0] ap_phi_reg_pp0_iter2_up_2_reg_479;
reg   [9:0] ap_phi_reg_pp0_iter3_up_2_reg_479;
reg   [9:0] ap_phi_reg_pp0_iter4_up_2_reg_479;
wire   [9:0] ap_phi_reg_pp0_iter0_up_1_reg_488;
reg   [9:0] ap_phi_reg_pp0_iter1_up_1_reg_488;
reg   [9:0] ap_phi_reg_pp0_iter2_up_1_reg_488;
reg   [9:0] ap_phi_reg_pp0_iter3_up_1_reg_488;
reg   [9:0] ap_phi_reg_pp0_iter4_up_1_reg_488;
wire   [9:0] ap_phi_reg_pp0_iter0_up_reg_497;
reg   [9:0] ap_phi_reg_pp0_iter1_up_reg_497;
reg   [9:0] ap_phi_reg_pp0_iter2_up_reg_497;
reg   [9:0] ap_phi_reg_pp0_iter3_up_reg_497;
reg   [9:0] ap_phi_reg_pp0_iter4_up_reg_497;
wire   [63:0] zext_ln881_fu_641_p1;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [10:0] x_fu_156;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_z;
reg   [9:0] p_0_0_0116317821793_i_fu_160;
wire   [9:0] trunc_ln902_1_fu_733_p1;
reg   [9:0] p_0_0_0116217841795_i_fu_164;
wire   [9:0] tmp_3_i3_fu_737_p4;
reg   [9:0] p_0_0_0116117861797_i_fu_168;
wire   [9:0] tmp_4_i4_fu_747_p4;
reg   [9:0] right_fu_172;
reg   [9:0] right_1_fu_176;
reg   [9:0] right_2_fu_180;
reg   [9:0] p_0_0_01185_217761805_i_fu_184;
reg   [9:0] p_0_0_01184_217781807_i_fu_188;
reg   [9:0] p_0_0_01183_217801809_i_fu_192;
reg   [9:0] p_0_0_0_0_011551706_i_fu_196;
reg   [9:0] p_0_1_0_0_011561709_i_fu_200;
reg   [9:0] p_0_2_0_0_011571712_i_fu_204;
reg    imgRB_read_local;
wire   [29:0] or_ln1054_3_i_fu_1745_p4;
reg    ap_block_pp0_stage0_01001;
reg    imgRgb_write_local;
reg    lineBuffer_ce1_local;
reg    lineBuffer_we0_local;
reg    lineBuffer_ce0_local;
reg    lineBuffer_2_ce1_local;
reg    lineBuffer_2_we0_local;
wire   [29:0] LineBufVal_4_fu_856_p4;
reg    lineBuffer_2_ce0_local;
wire   [0:0] trunc_ln881_fu_586_p1;
wire   [0:0] xor_ln1014_fu_602_p2;
wire   [0:0] xor_ln1014_1_fu_608_p2;
wire   [14:0] zext_ln1014_fu_614_p1;
wire   [0:0] icmp_ln1052_fu_624_p2;
wire   [9:0] PixBufVal_4_fu_838_p3;
wire   [9:0] PixBufVal_3_fu_844_p3;
wire   [9:0] PixBufVal_fu_850_p3;
wire   [10:0] zext_ln1023_fu_933_p1;
wire   [10:0] zext_ln1023_1_fu_937_p1;
wire   [10:0] sub_ln1023_fu_941_p2;
wire   [9:0] trunc_ln61_fu_947_p1;
wire   [0:0] tmp_12_fu_957_p3;
wire   [9:0] sub_ln61_fu_951_p2;
wire   [10:0] zext_ln1024_fu_973_p1;
wire   [10:0] zext_ln1024_1_fu_977_p1;
wire   [10:0] sub_ln1024_fu_981_p2;
wire   [9:0] trunc_ln61_4_fu_987_p1;
wire   [0:0] tmp_13_fu_997_p3;
wire   [9:0] sub_ln61_4_fu_991_p2;
wire   [10:0] zext_ln1025_fu_1013_p1;
wire   [10:0] zext_ln1025_1_fu_1017_p1;
wire   [10:0] sub_ln1025_fu_1021_p2;
wire   [9:0] trunc_ln61_5_fu_1027_p1;
wire   [0:0] tmp_14_fu_1037_p3;
wire   [9:0] sub_ln61_5_fu_1031_p2;
wire   [10:0] zext_ln1026_fu_1053_p1;
wire   [10:0] zext_ln1026_1_fu_1057_p1;
wire   [10:0] sub_ln1026_fu_1061_p2;
wire   [9:0] trunc_ln61_6_fu_1067_p1;
wire   [0:0] tmp_15_fu_1077_p3;
wire   [9:0] sub_ln61_6_fu_1071_p2;
wire   [10:0] zext_ln1027_fu_1093_p1;
wire   [10:0] zext_ln1027_1_fu_1097_p1;
wire   [10:0] zext_ln1028_fu_1117_p1;
wire   [10:0] zext_ln1028_1_fu_1121_p1;
wire   [9:0] DRh_fu_965_p3;
wire   [9:0] DGh_fu_1045_p3;
wire   [10:0] zext_ln1030_fu_1141_p1;
wire   [10:0] zext_ln1030_1_fu_1145_p1;
wire   [9:0] DRv_fu_1005_p3;
wire   [9:0] DGv_fu_1085_p3;
wire   [10:0] zext_ln1030_4_fu_1155_p1;
wire   [10:0] zext_ln1030_5_fu_1159_p1;
wire   [10:0] sub_ln1033_fu_1169_p2;
wire   [10:0] sub_ln1033_1_fu_1175_p2;
wire  signed [11:0] sext_ln1033_fu_1181_p1;
wire  signed [11:0] sext_ln1033_1_fu_1185_p1;
wire   [10:0] sub_ln1034_fu_1195_p2;
wire   [10:0] sub_ln1034_1_fu_1201_p2;
wire  signed [11:0] sext_ln1034_fu_1207_p1;
wire  signed [11:0] sext_ln1034_1_fu_1211_p1;
wire   [10:0] sub_ln1039_fu_1221_p2;
wire   [10:0] sub_ln1039_1_fu_1227_p2;
wire  signed [11:0] sext_ln1039_fu_1233_p1;
wire  signed [11:0] sext_ln1039_1_fu_1237_p1;
wire   [11:0] sub_ln1039_2_fu_1247_p2;
wire   [10:0] sub_ln1040_fu_1263_p2;
wire   [10:0] sub_ln1040_1_fu_1269_p2;
wire  signed [11:0] sext_ln1040_fu_1275_p1;
wire  signed [11:0] sext_ln1040_1_fu_1279_p1;
wire   [11:0] sub_ln1040_2_fu_1289_p2;
wire   [0:0] tmp_16_fu_1305_p3;
wire   [0:0] tmp_17_fu_1318_p3;
wire   [9:0] DBh_fu_1312_p3;
wire   [11:0] zext_ln1030_2_fu_1331_p1;
wire   [11:0] zext_ln1030_3_fu_1334_p1;
wire   [9:0] DBv_fu_1325_p3;
wire   [11:0] zext_ln1030_6_fu_1344_p1;
wire   [11:0] zext_ln1030_7_fu_1347_p1;
wire   [11:0] add_ln1030_1_fu_1338_p2;
wire   [11:0] add_ln1030_3_fu_1351_p2;
wire   [11:0] sub_ln1033_2_fu_1370_p2;
wire   [10:0] trunc_ln1033_2_i_fu_1375_p4;
wire  signed [11:0] sext_ln1033_2_fu_1385_p1;
wire   [12:0] zext_ln1033_fu_1389_p1;
wire   [10:0] trunc_ln1033_1_i_fu_1399_p4;
wire  signed [11:0] sext_ln1033_3_fu_1408_p1;
wire   [0:0] tmp_18_fu_1363_p3;
wire   [12:0] sub_ln1033_3_fu_1393_p2;
wire   [12:0] zext_ln1033_1_fu_1412_p1;
wire   [11:0] sub_ln1034_2_fu_1435_p2;
wire   [10:0] trunc_ln1034_2_i_fu_1440_p4;
wire  signed [11:0] sext_ln1034_2_fu_1450_p1;
wire   [12:0] zext_ln1034_fu_1454_p1;
wire   [10:0] trunc_ln1034_1_i_fu_1464_p4;
wire  signed [11:0] sext_ln1034_3_fu_1473_p1;
wire   [0:0] tmp_19_fu_1428_p3;
wire   [12:0] sub_ln1034_3_fu_1458_p2;
wire   [12:0] zext_ln1034_1_fu_1477_p1;
wire  signed [11:0] sext_ln1039_2_fu_1496_p1;
wire   [12:0] zext_ln1039_fu_1499_p1;
wire   [10:0] trunc_ln1039_1_i_fu_1509_p4;
wire  signed [11:0] sext_ln1039_3_fu_1518_p1;
wire   [0:0] tmp_20_fu_1489_p3;
wire   [12:0] sub_ln1039_3_fu_1503_p2;
wire   [12:0] zext_ln1039_1_fu_1522_p1;
wire  signed [11:0] sext_ln1040_2_fu_1541_p1;
wire   [12:0] zext_ln1040_fu_1544_p1;
wire   [10:0] trunc_ln1040_1_i_fu_1554_p4;
wire  signed [11:0] sext_ln1040_3_fu_1563_p1;
wire   [0:0] tmp_21_fu_1534_p3;
wire   [12:0] sub_ln1040_3_fu_1548_p2;
wire   [12:0] zext_ln1040_1_fu_1567_p1;
wire   [0:0] icmp_ln1030_fu_1357_p2;
wire   [12:0] select_ln1033_fu_1416_p3;
wire   [12:0] select_ln1039_fu_1526_p3;
wire   [12:0] r_2_v_v_i_fu_1579_p3;
wire   [13:0] zext_ln1033_2_fu_1424_p1;
wire  signed [13:0] r_2_v_i_fu_1587_p1;
wire   [12:0] select_ln1034_fu_1481_p3;
wire   [12:0] select_ln1040_fu_1571_p3;
wire   [12:0] b_2_v_v_i_fu_1597_p3;
wire  signed [13:0] b_2_v_i_fu_1605_p1;
wire   [0:0] xor_ln1042_fu_1654_p2;
wire   [0:0] icmp_ln1042_fu_1649_p2;
wire   [0:0] or_ln1042_fu_1667_p2;
wire   [9:0] select_ln1042_fu_1659_p3;
wire   [9:0] trunc_ln1008_1_fu_1646_p1;
wire   [0:0] icmp_ln1043_fu_1687_p2;
wire   [9:0] trunc_ln1008_fu_1643_p1;
wire   [9:0] r_3_fu_1672_p3;
wire   [0:0] tmp_24_fu_1680_p3;
wire   [0:0] xor_ln1014_2_fu_1707_p2;
wire   [0:0] and_ln1043_fu_1712_p2;
wire   [9:0] b_3_fu_1725_p6;
wire   [9:0] b_3_fu_1725_p7;
wire   [1:0] b_3_fu_1725_p8;
wire   [9:0] r_4_fu_1700_p3;
wire   [9:0] b_3_fu_1725_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_predicate_op76_load_state2;
reg    ap_enable_operation_76;
reg    ap_enable_state2_pp0_iter1_stage0;
reg    ap_predicate_op83_load_state3;
reg    ap_enable_operation_83;
reg    ap_enable_state3_pp0_iter2_stage0;
reg    ap_predicate_op89_store_state3;
reg    ap_enable_operation_89;
reg    ap_predicate_op87_load_state3;
reg    ap_enable_operation_87;
reg    ap_predicate_op106_load_state4;
reg    ap_enable_operation_106;
reg    ap_enable_state4_pp0_iter3_stage0;
reg    ap_predicate_op129_store_state4;
reg    ap_enable_operation_129;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_60;
reg    ap_condition_450;
reg    ap_condition_459;
reg    ap_condition_1423;
wire  signed [1:0] b_3_fu_1725_p1;
wire   [1:0] b_3_fu_1725_p3;
wire   [1:0] b_3_fu_1725_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 x_fu_156 = 11'd0;
#0 p_0_0_0116317821793_i_fu_160 = 10'd0;
#0 p_0_0_0116217841795_i_fu_164 = 10'd0;
#0 p_0_0_0116117861797_i_fu_168 = 10'd0;
#0 right_fu_172 = 10'd0;
#0 right_1_fu_176 = 10'd0;
#0 right_2_fu_180 = 10'd0;
#0 p_0_0_01185_217761805_i_fu_184 = 10'd0;
#0 p_0_0_01184_217781807_i_fu_188 = 10'd0;
#0 p_0_0_01183_217801809_i_fu_192 = 10'd0;
#0 p_0_0_0_0_011551706_i_fu_196 = 10'd0;
#0 p_0_1_0_0_011561709_i_fu_200 = 10'd0;
#0 p_0_2_0_0_011571712_i_fu_204 = 10'd0;
#0 ap_done_reg = 1'b0;
end

design_1_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_lineBuffer_1_RAM_AUTO_1R1W #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lineBuffer_2_address0),
    .ce0(lineBuffer_2_ce0_local),
    .we0(lineBuffer_2_we0_local),
    .d0(LineBufVal_4_fu_856_p4),
    .address1(lineBuffer_2_address1),
    .ce1(lineBuffer_2_ce1_local),
    .q1(lineBuffer_2_q1)
);

design_1_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_lineBuffer_1_RAM_AUTO_1R1W #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lineBuffer_address0),
    .ce0(lineBuffer_ce0_local),
    .we0(lineBuffer_we0_local),
    .d0(InPix_reg_1973),
    .address1(lineBuffer_address1),
    .ce1(lineBuffer_ce1_local),
    .q1(lineBuffer_q1)
);

(* dissolve_hierarchy = "yes" *) design_1_v_demosaic_0_0_sparsemux_7_2_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 10 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 10 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 10 ),
    .def_WIDTH( 10 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 10 ))
sparsemux_7_2_10_1_1_U173(
    .din0(pix_8_reg_395_pp0_iter5_reg),
    .din1(10'd0),
    .din2(b_3_fu_1725_p6),
    .def(b_3_fu_1725_p7),
    .sel(b_3_fu_1725_p8),
    .dout(b_3_fu_1725_p9)
);

design_1_v_demosaic_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter3_stage0)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_450)) begin
        if ((1'b1 == ap_condition_60)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01183_21780_ph_i_reg_368 <= {{imgRB_dout[29:20]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01183_21780_ph_i_reg_368 <= ap_phi_reg_pp0_iter1_p_0_0_01183_21780_ph_i_reg_368;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_450)) begin
        if ((1'b1 == ap_condition_60)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01184_21778_ph_i_reg_377 <= {{imgRB_dout[19:10]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01184_21778_ph_i_reg_377 <= ap_phi_reg_pp0_iter1_p_0_0_01184_21778_ph_i_reg_377;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_450)) begin
        if ((1'b1 == ap_condition_60)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01185_21776_ph_i_reg_386 <= trunc_ln913_fu_646_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_p_0_0_01185_21776_ph_i_reg_386 <= ap_phi_reg_pp0_iter1_p_0_0_01185_21776_ph_i_reg_386;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((1'b1 == ap_condition_459)) begin
            ap_phi_reg_pp0_iter3_p_0_0_01183_21780_ph_i_reg_368 <= {{lineBuffer_q1[29:20]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_p_0_0_01183_21780_ph_i_reg_368 <= ap_phi_reg_pp0_iter2_p_0_0_01183_21780_ph_i_reg_368;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((1'b1 == ap_condition_459)) begin
            ap_phi_reg_pp0_iter3_p_0_0_01184_21778_ph_i_reg_377 <= {{lineBuffer_q1[19:10]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_p_0_0_01184_21778_ph_i_reg_377 <= ap_phi_reg_pp0_iter2_p_0_0_01184_21778_ph_i_reg_377;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((1'b1 == ap_condition_459)) begin
            ap_phi_reg_pp0_iter3_p_0_0_01185_21776_ph_i_reg_386 <= trunc_ln902_fu_670_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter3_p_0_0_01185_21776_ph_i_reg_386 <= ap_phi_reg_pp0_iter2_p_0_0_01185_21776_ph_i_reg_386;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd0) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_down_1_reg_434 <= p_0_0_01184_217781807_i_fu_188;
        end else if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_down_1_reg_434 <= select_ln957_10_fu_824_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_down_1_reg_434 <= ap_phi_reg_pp0_iter3_down_1_reg_434;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd0) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_down_2_reg_425 <= p_0_0_01183_217801809_i_fu_192;
        end else if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_down_2_reg_425 <= select_ln957_9_fu_817_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_down_2_reg_425 <= ap_phi_reg_pp0_iter3_down_2_reg_425;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd0) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_down_reg_443 <= p_0_0_01185_217761805_i_fu_184;
        end else if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_down_reg_443 <= select_ln957_11_fu_831_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_down_reg_443 <= ap_phi_reg_pp0_iter3_down_reg_443;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd0) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_left_1_reg_461 <= p_0_1_0_0_011561709_i_fu_200;
        end else if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_left_1_reg_461 <= select_ln957_4_fu_784_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_left_1_reg_461 <= ap_phi_reg_pp0_iter3_left_1_reg_461;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd0) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_left_2_reg_452 <= p_0_2_0_0_011571712_i_fu_204;
        end else if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_left_2_reg_452 <= select_ln957_5_fu_790_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_left_2_reg_452 <= ap_phi_reg_pp0_iter3_left_2_reg_452;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd0) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_left_reg_470 <= p_0_0_0_0_011551706_i_fu_196;
        end else if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_left_reg_470 <= select_ln957_3_fu_778_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_left_reg_470 <= ap_phi_reg_pp0_iter3_left_reg_470;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd0) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_up_1_reg_488 <= p_0_0_0116217841795_i_fu_164;
        end else if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_up_1_reg_488 <= select_ln957_7_fu_803_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_up_1_reg_488 <= ap_phi_reg_pp0_iter3_up_1_reg_488;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd0) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_up_2_reg_479 <= p_0_0_0116117861797_i_fu_168;
        end else if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_up_2_reg_479 <= select_ln957_6_fu_796_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_up_2_reg_479 <= ap_phi_reg_pp0_iter3_up_2_reg_479;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd0) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_up_reg_497 <= p_0_0_0116317821793_i_fu_160;
        end else if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_up_reg_497 <= select_ln957_8_fu_810_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_up_reg_497 <= ap_phi_reg_pp0_iter3_up_reg_497;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0116117861797_i_fu_168 <= p_0_0_0116117861798_lcssa1834_i;
        end else if ((1'b1 == ap_condition_1423)) begin
            p_0_0_0116117861797_i_fu_168 <= {{lineBuffer_2_q1[29:20]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0116217841795_i_fu_164 <= p_0_0_0116217841796_lcssa1832_i;
        end else if ((1'b1 == ap_condition_1423)) begin
            p_0_0_0116217841795_i_fu_164 <= {{lineBuffer_2_q1[19:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0116317821793_i_fu_160 <= p_0_0_0116317821794_lcssa1830_i;
        end else if ((1'b1 == ap_condition_1423)) begin
            p_0_0_0116317821793_i_fu_160 <= trunc_ln902_1_fu_733_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_01183_217801809_i_fu_192 <= p_0_0_01183_217801810_lcssa1846_i;
        end else if ((1'b1 == ap_condition_1423)) begin
            p_0_0_01183_217801809_i_fu_192 <= ap_phi_reg_pp0_iter3_p_0_0_01183_21780_ph_i_reg_368;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_01184_217781807_i_fu_188 <= p_0_0_01184_217781808_lcssa1844_i;
        end else if ((1'b1 == ap_condition_1423)) begin
            p_0_0_01184_217781807_i_fu_188 <= ap_phi_reg_pp0_iter3_p_0_0_01184_21778_ph_i_reg_377;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_01185_217761805_i_fu_184 <= p_0_0_01185_217761806_lcssa1842_i;
        end else if ((1'b1 == ap_condition_1423)) begin
            p_0_0_01185_217761805_i_fu_184 <= ap_phi_reg_pp0_iter3_p_0_0_01185_21776_ph_i_reg_386;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0_0_011551706_i_fu_196 <= p_0_0_0_0_011551704_lcssa1748_i;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            p_0_0_0_0_011551706_i_fu_196 <= ap_phi_mux_pix_phi_fu_418_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_1_0_0_011561709_i_fu_200 <= p_0_1_0_0_011561707_lcssa1750_i;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            p_0_1_0_0_011561709_i_fu_200 <= ap_phi_mux_pix_7_phi_fu_408_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_2_0_0_011571712_i_fu_204 <= p_0_2_0_0_011571710_lcssa1752_i;
        end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            p_0_2_0_0_011571712_i_fu_204 <= ap_phi_mux_pix_8_phi_fu_398_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd0) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            pix_7_reg_405 <= right_1_fu_176;
        end else if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            pix_7_reg_405 <= select_ln957_1_fu_764_p3;
        end else if (~(icmp_ln881_reg_1921_pp0_iter2_reg == 1'd1)) begin
            pix_7_reg_405 <= ap_phi_reg_pp0_iter3_pix_7_reg_405;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd0) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            pix_8_reg_395 <= right_2_fu_180;
        end else if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            pix_8_reg_395 <= select_ln957_2_fu_771_p3;
        end else if (~(icmp_ln881_reg_1921_pp0_iter2_reg == 1'd1)) begin
            pix_8_reg_395 <= ap_phi_reg_pp0_iter3_pix_8_reg_395;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd0) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            pix_reg_415 <= right_fu_172;
        end else if (((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
            pix_reg_415 <= select_ln957_fu_757_p3;
        end else if (~(icmp_ln881_reg_1921_pp0_iter2_reg == 1'd1)) begin
            pix_reg_415 <= ap_phi_reg_pp0_iter3_pix_reg_415;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            right_1_fu_176 <= p_0_1_0_0_011501801_lcssa1838_i;
        end else if ((1'b1 == ap_condition_1423)) begin
            right_1_fu_176 <= tmp_i1_reg_2002;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            right_2_fu_180 <= p_0_2_0_0_011511803_lcssa1840_i;
        end else if ((1'b1 == ap_condition_1423)) begin
            right_2_fu_180 <= tmp_1_i2_reg_2011;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            right_fu_172 <= p_0_0_0_0_011491799_lcssa1836_i;
        end else if ((1'b1 == ap_condition_1423)) begin
            right_fu_172 <= trunc_ln902_reg_1993;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln881_fu_574_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_156 <= x_8_fu_580_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_156 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        InPix_reg_1973 <= imgRB_dout;
        and_ln1052_reg_1957 <= and_ln1052_fu_630_p2;
        and_ln1052_reg_1957_pp0_iter1_reg <= and_ln1052_reg_1957;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cmp161_i_reg_1934 <= cmp161_i_fu_596_p2;
        cmp161_i_reg_1934_pp0_iter1_reg <= cmp161_i_reg_1934;
        icmp_ln1014_reg_1950 <= icmp_ln1014_fu_618_p2;
        icmp_ln1014_reg_1950_pp0_iter1_reg <= icmp_ln1014_reg_1950;
        icmp_ln881_reg_1921 <= icmp_ln881_fu_574_p2;
        icmp_ln881_reg_1921_pp0_iter1_reg <= icmp_ln881_reg_1921;
        icmp_ln891_reg_1930 <= icmp_ln891_fu_590_p2;
        icmp_ln891_reg_1930_pp0_iter1_reg <= icmp_ln891_reg_1930;
        lineBuffer_2_addr_reg_1967 <= zext_ln881_fu_641_p1;
        lineBuffer_addr_reg_1961 <= zext_ln881_fu_641_p1;
        x_8_reg_1925 <= x_8_fu_580_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln1030_2_reg_2169 <= add_ln1030_2_fu_1163_p2;
        add_ln1030_reg_2164 <= add_ln1030_fu_1149_p2;
        add_ln1033_reg_2174 <= add_ln1033_fu_1189_p2;
        add_ln1034_reg_2181 <= add_ln1034_fu_1215_p2;
        add_ln1039_reg_2188 <= add_ln1039_fu_1241_p2;
        add_ln1040_reg_2199 <= add_ln1040_fu_1283_p2;
        and_ln1052_reg_1957_pp0_iter2_reg <= and_ln1052_reg_1957_pp0_iter1_reg;
        and_ln1052_reg_1957_pp0_iter3_reg <= and_ln1052_reg_1957_pp0_iter2_reg;
        and_ln1052_reg_1957_pp0_iter4_reg <= and_ln1052_reg_1957_pp0_iter3_reg;
        and_ln1052_reg_1957_pp0_iter5_reg <= and_ln1052_reg_1957_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        b_2_reg_2215 <= b_2_fu_1609_p2;
        cmp161_i_reg_1934_pp0_iter2_reg <= cmp161_i_reg_1934_pp0_iter1_reg;
        icmp_ln1014_reg_1950_pp0_iter2_reg <= icmp_ln1014_reg_1950_pp0_iter1_reg;
        icmp_ln1014_reg_1950_pp0_iter3_reg <= icmp_ln1014_reg_1950_pp0_iter2_reg;
        icmp_ln1014_reg_1950_pp0_iter4_reg <= icmp_ln1014_reg_1950_pp0_iter3_reg;
        icmp_ln1014_reg_1950_pp0_iter5_reg <= icmp_ln1014_reg_1950_pp0_iter4_reg;
        icmp_ln881_reg_1921_pp0_iter2_reg <= icmp_ln881_reg_1921_pp0_iter1_reg;
        icmp_ln881_reg_1921_pp0_iter3_reg <= icmp_ln881_reg_1921_pp0_iter2_reg;
        icmp_ln881_reg_1921_pp0_iter4_reg <= icmp_ln881_reg_1921_pp0_iter3_reg;
        icmp_ln891_reg_1930_pp0_iter2_reg <= icmp_ln891_reg_1930_pp0_iter1_reg;
        lineBuffer_2_addr_reg_1967_pp0_iter2_reg <= lineBuffer_2_addr_reg_1967;
        p_0_0_0116117861797_i_load_reg_2032_pp0_iter4_reg <= p_0_0_0116117861797_i_load_reg_2032;
        p_0_0_0116217841795_i_load_reg_2026_pp0_iter4_reg <= p_0_0_0116217841795_i_load_reg_2026;
        p_0_0_0116317821793_i_load_reg_2020_pp0_iter4_reg <= p_0_0_0116317821793_i_load_reg_2020;
        p_0_0_01183_217801809_i_load_reg_2065_pp0_iter4_reg <= p_0_0_01183_217801809_i_load_reg_2065;
        p_0_0_01184_217781807_i_load_reg_2059_pp0_iter4_reg <= p_0_0_01184_217781807_i_load_reg_2059;
        p_0_0_01185_217761805_i_load_reg_2053_pp0_iter4_reg <= p_0_0_01185_217761805_i_load_reg_2053;
        p_0_0_0_0_011551706_i_load_reg_2071_pp0_iter4_reg <= p_0_0_0_0_011551706_i_load_reg_2071;
        p_0_1_0_0_011561709_i_load_reg_2077_pp0_iter4_reg <= p_0_1_0_0_011561709_i_load_reg_2077;
        p_0_2_0_0_011571712_i_load_reg_2083_pp0_iter4_reg <= p_0_2_0_0_011571712_i_load_reg_2083;
        pix_7_reg_405_pp0_iter4_reg <= pix_7_reg_405;
        pix_7_reg_405_pp0_iter5_reg <= pix_7_reg_405_pp0_iter4_reg;
        pix_8_reg_395_pp0_iter4_reg <= pix_8_reg_395;
        pix_8_reg_395_pp0_iter5_reg <= pix_8_reg_395_pp0_iter4_reg;
        pix_reg_415_pp0_iter4_reg <= pix_reg_415;
        pix_reg_415_pp0_iter5_reg <= pix_reg_415_pp0_iter4_reg;
        r_2_reg_2210 <= r_2_fu_1591_p2;
        right_3_reg_2038_pp0_iter4_reg <= right_3_reg_2038;
        right_4_reg_2043_pp0_iter4_reg <= right_4_reg_2043;
        right_5_reg_2048_pp0_iter4_reg <= right_5_reg_2048;
        sub_ln1027_reg_2134 <= sub_ln1027_fu_1101_p2;
        sub_ln1028_reg_2149 <= sub_ln1028_fu_1125_p2;
        sub_ln61_7_reg_2144 <= sub_ln61_7_fu_1111_p2;
        sub_ln61_8_reg_2159 <= sub_ln61_8_fu_1135_p2;
        tmp_1_i2_reg_2011 <= {{lineBuffer_q1[29:20]}};
        tmp_22_reg_2221 <= r_2_fu_1591_p2[32'd13];
        tmp_23_reg_2227 <= {{r_2_fu_1591_p2[13:10]}};
        tmp_25_reg_2232 <= {{b_2_fu_1609_p2[13:10]}};
        tmp_i1_reg_2002 <= {{lineBuffer_q1[19:10]}};
        trunc_ln1039_2_i_reg_2194 <= {{sub_ln1039_2_fu_1247_p2[11:1]}};
        trunc_ln1040_2_i_reg_2205 <= {{sub_ln1040_2_fu_1289_p2[11:1]}};
        trunc_ln61_7_reg_2139 <= trunc_ln61_7_fu_1107_p1;
        trunc_ln61_8_reg_2154 <= trunc_ln61_8_fu_1131_p1;
        trunc_ln902_reg_1993 <= trunc_ln902_fu_670_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_down_1_reg_434 <= ap_phi_reg_pp0_iter0_down_1_reg_434;
        ap_phi_reg_pp0_iter1_down_2_reg_425 <= ap_phi_reg_pp0_iter0_down_2_reg_425;
        ap_phi_reg_pp0_iter1_down_reg_443 <= ap_phi_reg_pp0_iter0_down_reg_443;
        ap_phi_reg_pp0_iter1_left_1_reg_461 <= ap_phi_reg_pp0_iter0_left_1_reg_461;
        ap_phi_reg_pp0_iter1_left_2_reg_452 <= ap_phi_reg_pp0_iter0_left_2_reg_452;
        ap_phi_reg_pp0_iter1_left_reg_470 <= ap_phi_reg_pp0_iter0_left_reg_470;
        ap_phi_reg_pp0_iter1_p_0_0_01183_21780_ph_i_reg_368 <= ap_phi_reg_pp0_iter0_p_0_0_01183_21780_ph_i_reg_368;
        ap_phi_reg_pp0_iter1_p_0_0_01184_21778_ph_i_reg_377 <= ap_phi_reg_pp0_iter0_p_0_0_01184_21778_ph_i_reg_377;
        ap_phi_reg_pp0_iter1_p_0_0_01185_21776_ph_i_reg_386 <= ap_phi_reg_pp0_iter0_p_0_0_01185_21776_ph_i_reg_386;
        ap_phi_reg_pp0_iter1_up_1_reg_488 <= ap_phi_reg_pp0_iter0_up_1_reg_488;
        ap_phi_reg_pp0_iter1_up_2_reg_479 <= ap_phi_reg_pp0_iter0_up_2_reg_479;
        ap_phi_reg_pp0_iter1_up_reg_497 <= ap_phi_reg_pp0_iter0_up_reg_497;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_down_1_reg_434 <= ap_phi_reg_pp0_iter1_down_1_reg_434;
        ap_phi_reg_pp0_iter2_down_2_reg_425 <= ap_phi_reg_pp0_iter1_down_2_reg_425;
        ap_phi_reg_pp0_iter2_down_reg_443 <= ap_phi_reg_pp0_iter1_down_reg_443;
        ap_phi_reg_pp0_iter2_left_1_reg_461 <= ap_phi_reg_pp0_iter1_left_1_reg_461;
        ap_phi_reg_pp0_iter2_left_2_reg_452 <= ap_phi_reg_pp0_iter1_left_2_reg_452;
        ap_phi_reg_pp0_iter2_left_reg_470 <= ap_phi_reg_pp0_iter1_left_reg_470;
        ap_phi_reg_pp0_iter2_up_1_reg_488 <= ap_phi_reg_pp0_iter1_up_1_reg_488;
        ap_phi_reg_pp0_iter2_up_2_reg_479 <= ap_phi_reg_pp0_iter1_up_2_reg_479;
        ap_phi_reg_pp0_iter2_up_reg_497 <= ap_phi_reg_pp0_iter1_up_reg_497;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_down_1_reg_434 <= ap_phi_reg_pp0_iter2_down_1_reg_434;
        ap_phi_reg_pp0_iter3_down_2_reg_425 <= ap_phi_reg_pp0_iter2_down_2_reg_425;
        ap_phi_reg_pp0_iter3_down_reg_443 <= ap_phi_reg_pp0_iter2_down_reg_443;
        ap_phi_reg_pp0_iter3_left_1_reg_461 <= ap_phi_reg_pp0_iter2_left_1_reg_461;
        ap_phi_reg_pp0_iter3_left_2_reg_452 <= ap_phi_reg_pp0_iter2_left_2_reg_452;
        ap_phi_reg_pp0_iter3_left_reg_470 <= ap_phi_reg_pp0_iter2_left_reg_470;
        ap_phi_reg_pp0_iter3_up_1_reg_488 <= ap_phi_reg_pp0_iter2_up_1_reg_488;
        ap_phi_reg_pp0_iter3_up_2_reg_479 <= ap_phi_reg_pp0_iter2_up_2_reg_479;
        ap_phi_reg_pp0_iter3_up_reg_497 <= ap_phi_reg_pp0_iter2_up_reg_497;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_0_0_0116117861797_i_load_reg_2032 <= p_0_0_0116117861797_i_fu_168;
        p_0_0_0116217841795_i_load_reg_2026 <= p_0_0_0116217841795_i_fu_164;
        p_0_0_0116317821793_i_load_reg_2020 <= p_0_0_0116317821793_i_fu_160;
        p_0_0_01183_217801809_i_load_reg_2065 <= p_0_0_01183_217801809_i_fu_192;
        p_0_0_01184_217781807_i_load_reg_2059 <= p_0_0_01184_217781807_i_fu_188;
        p_0_0_01185_217761805_i_load_reg_2053 <= p_0_0_01185_217761805_i_fu_184;
        p_0_0_0_0_011551706_i_load_reg_2071 <= p_0_0_0_0_011551706_i_fu_196;
        p_0_1_0_0_011561709_i_load_reg_2077 <= p_0_1_0_0_011561709_i_fu_200;
        p_0_2_0_0_011571712_i_load_reg_2083 <= p_0_2_0_0_011571712_i_fu_204;
        right_3_reg_2038 <= right_fu_172;
        right_4_reg_2043 <= right_1_fu_176;
        right_5_reg_2048 <= right_2_fu_180;
    end
end

always @ (*) begin
    if (((icmp_ln881_fu_574_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd1))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0)) begin
        if ((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd0)) begin
            ap_phi_mux_pix_7_phi_fu_408_p4 = right_1_fu_176;
        end else if ((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1)) begin
            ap_phi_mux_pix_7_phi_fu_408_p4 = select_ln957_1_fu_764_p3;
        end else begin
            ap_phi_mux_pix_7_phi_fu_408_p4 = ap_phi_reg_pp0_iter3_pix_7_reg_405;
        end
    end else begin
        ap_phi_mux_pix_7_phi_fu_408_p4 = ap_phi_reg_pp0_iter3_pix_7_reg_405;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0)) begin
        if ((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd0)) begin
            ap_phi_mux_pix_8_phi_fu_398_p4 = right_2_fu_180;
        end else if ((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1)) begin
            ap_phi_mux_pix_8_phi_fu_398_p4 = select_ln957_2_fu_771_p3;
        end else begin
            ap_phi_mux_pix_8_phi_fu_398_p4 = ap_phi_reg_pp0_iter3_pix_8_reg_395;
        end
    end else begin
        ap_phi_mux_pix_8_phi_fu_398_p4 = ap_phi_reg_pp0_iter3_pix_8_reg_395;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0)) begin
        if ((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd0)) begin
            ap_phi_mux_pix_phi_fu_418_p4 = right_fu_172;
        end else if ((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1)) begin
            ap_phi_mux_pix_phi_fu_418_p4 = select_ln957_fu_757_p3;
        end else begin
            ap_phi_mux_pix_phi_fu_418_p4 = ap_phi_reg_pp0_iter3_pix_reg_415;
        end
    end else begin
        ap_phi_mux_pix_phi_fu_418_p4 = ap_phi_reg_pp0_iter3_pix_reg_415;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_z = 11'd0;
    end else begin
        ap_sig_allocacmp_z = x_fu_156;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op78_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgRB_blk_n = imgRB_empty_n;
    end else begin
        imgRB_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op78_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgRB_read_local = 1'b1;
    end else begin
        imgRB_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln1052_reg_1957_pp0_iter5_reg) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        imgRgb_blk_n = imgRgb_full_n;
    end else begin
        imgRgb_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln1052_reg_1957_pp0_iter5_reg) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        imgRgb_write_local = 1'b1;
    end else begin
        imgRgb_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        lineBuffer_2_ce0_local = 1'b1;
    end else begin
        lineBuffer_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lineBuffer_2_ce1_local = 1'b1;
    end else begin
        lineBuffer_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0))) begin
        lineBuffer_2_we0_local = 1'b1;
    end else begin
        lineBuffer_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        lineBuffer_ce0_local = 1'b1;
    end else begin
        lineBuffer_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_ce1_local = 1'b1;
    end else begin
        lineBuffer_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (cmp59_i == 1'd1) & (icmp_ln891_reg_1930_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln881_reg_1921_pp0_iter1_reg == 1'd0))) begin
        lineBuffer_we0_local = 1'b1;
    end else begin
        lineBuffer_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (icmp_ln881_reg_1921_pp0_iter4_reg == 1'd1))) begin
        p_0_0_0116117861797_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116117861797_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (icmp_ln881_reg_1921_pp0_iter4_reg == 1'd1))) begin
        p_0_0_0116217841795_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116217841795_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (icmp_ln881_reg_1921_pp0_iter4_reg == 1'd1))) begin
        p_0_0_0116317821793_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116317821793_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (icmp_ln881_reg_1921_pp0_iter4_reg == 1'd1))) begin
        p_0_0_01183_217801809_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01183_217801809_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (icmp_ln881_reg_1921_pp0_iter4_reg == 1'd1))) begin
        p_0_0_01184_217781807_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01184_217781807_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (icmp_ln881_reg_1921_pp0_iter4_reg == 1'd1))) begin
        p_0_0_01185_217761805_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01185_217761805_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (icmp_ln881_reg_1921_pp0_iter4_reg == 1'd1))) begin
        p_0_0_0_0_011551706_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0_0_011551706_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (icmp_ln881_reg_1921_pp0_iter4_reg == 1'd1))) begin
        p_0_1_0_0_011561709_i_out_ap_vld = 1'b1;
    end else begin
        p_0_1_0_0_011561709_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (icmp_ln881_reg_1921_pp0_iter4_reg == 1'd1))) begin
        p_0_2_0_0_011571712_i_out_ap_vld = 1'b1;
    end else begin
        p_0_2_0_0_011571712_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (icmp_ln881_reg_1921_pp0_iter4_reg == 1'd1))) begin
        right_1_i_out_ap_vld = 1'b1;
    end else begin
        right_1_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (icmp_ln881_reg_1921_pp0_iter4_reg == 1'd1))) begin
        right_2_i_out_ap_vld = 1'b1;
    end else begin
        right_2_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1) & (icmp_ln881_reg_1921_pp0_iter4_reg == 1'd1))) begin
        right_i_out_ap_vld = 1'b1;
    end else begin
        right_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DBh_fu_1312_p3 = ((tmp_16_fu_1305_p3[0:0] == 1'b1) ? sub_ln61_7_reg_2144 : trunc_ln61_7_reg_2139);

assign DBv_fu_1325_p3 = ((tmp_17_fu_1318_p3[0:0] == 1'b1) ? sub_ln61_8_reg_2159 : trunc_ln61_8_reg_2154);

assign DGh_fu_1045_p3 = ((tmp_14_fu_1037_p3[0:0] == 1'b1) ? sub_ln61_5_fu_1031_p2 : trunc_ln61_5_fu_1027_p1);

assign DGv_fu_1085_p3 = ((tmp_15_fu_1077_p3[0:0] == 1'b1) ? sub_ln61_6_fu_1071_p2 : trunc_ln61_6_fu_1067_p1);

assign DRh_fu_965_p3 = ((tmp_12_fu_957_p3[0:0] == 1'b1) ? sub_ln61_fu_951_p2 : trunc_ln61_fu_947_p1);

assign DRv_fu_1005_p3 = ((tmp_13_fu_997_p3[0:0] == 1'b1) ? sub_ln61_4_fu_991_p2 : trunc_ln61_4_fu_987_p1);

assign LineBufVal_4_fu_856_p4 = {{{PixBufVal_4_fu_838_p3}, {PixBufVal_3_fu_844_p3}}, {PixBufVal_fu_850_p3}};

assign PixBufVal_3_fu_844_p3 = ((cmp203_i[0:0] == 1'b1) ? tmp_i1_reg_2002 : ap_phi_reg_pp0_iter3_p_0_0_01184_21778_ph_i_reg_377);

assign PixBufVal_4_fu_838_p3 = ((cmp203_i[0:0] == 1'b1) ? tmp_1_i2_reg_2011 : ap_phi_reg_pp0_iter3_p_0_0_01183_21780_ph_i_reg_368);

assign PixBufVal_fu_850_p3 = ((cmp203_i[0:0] == 1'b1) ? trunc_ln902_reg_1993 : ap_phi_reg_pp0_iter3_p_0_0_01185_21776_ph_i_reg_386);

assign add_ln1030_1_fu_1338_p2 = (zext_ln1030_2_fu_1331_p1 + zext_ln1030_3_fu_1334_p1);

assign add_ln1030_2_fu_1163_p2 = (zext_ln1030_4_fu_1155_p1 + zext_ln1030_5_fu_1159_p1);

assign add_ln1030_3_fu_1351_p2 = (zext_ln1030_6_fu_1344_p1 + zext_ln1030_7_fu_1347_p1);

assign add_ln1030_fu_1149_p2 = (zext_ln1030_fu_1141_p1 + zext_ln1030_1_fu_1145_p1);

assign add_ln1033_fu_1189_p2 = ($signed(sext_ln1033_fu_1181_p1) + $signed(sext_ln1033_1_fu_1185_p1));

assign add_ln1034_fu_1215_p2 = ($signed(sext_ln1034_fu_1207_p1) + $signed(sext_ln1034_1_fu_1211_p1));

assign add_ln1039_fu_1241_p2 = ($signed(sext_ln1039_fu_1233_p1) + $signed(sext_ln1039_1_fu_1237_p1));

assign add_ln1040_fu_1283_p2 = ($signed(sext_ln1040_fu_1275_p1) + $signed(sext_ln1040_1_fu_1279_p1));

assign and_ln1043_fu_1712_p2 = (xor_ln1014_2_fu_1707_p2 & tmp_24_fu_1680_p3);

assign and_ln1052_fu_630_p2 = (icmp_ln1052_fu_624_p2 & cmp203_i);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op78_read_state2 == 1'b1) & (imgRB_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6 = ((imgRgb_full_n == 1'b0) & (1'd1 == and_ln1052_reg_1957_pp0_iter5_reg));
end

always @ (*) begin
    ap_condition_1423 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_condition_450 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_459 = ((cmp59_i_read_reg_1910 == 1'd0) & (icmp_ln891_reg_1930_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_60 = ((cmp59_i == 1'd1) & (icmp_ln891_reg_1930 == 1'd1) & (icmp_ln881_reg_1921 == 1'd0));
end

assign ap_done = ap_done_sig;

always @ (*) begin
    ap_enable_operation_106 = (ap_predicate_op106_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_129 = (ap_predicate_op129_store_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_76 = (ap_predicate_op76_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_83 = (ap_predicate_op83_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_87 = (ap_predicate_op87_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_89 = (ap_predicate_op89_store_state3 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state3_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state4_pp0_iter3_stage0 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_down_1_reg_434 = 'bx;

assign ap_phi_reg_pp0_iter0_down_2_reg_425 = 'bx;

assign ap_phi_reg_pp0_iter0_down_reg_443 = 'bx;

assign ap_phi_reg_pp0_iter0_left_1_reg_461 = 'bx;

assign ap_phi_reg_pp0_iter0_left_2_reg_452 = 'bx;

assign ap_phi_reg_pp0_iter0_left_reg_470 = 'bx;

assign ap_phi_reg_pp0_iter0_p_0_0_01183_21780_ph_i_reg_368 = 'bx;

assign ap_phi_reg_pp0_iter0_p_0_0_01184_21778_ph_i_reg_377 = 'bx;

assign ap_phi_reg_pp0_iter0_p_0_0_01185_21776_ph_i_reg_386 = 'bx;

assign ap_phi_reg_pp0_iter0_up_1_reg_488 = 'bx;

assign ap_phi_reg_pp0_iter0_up_2_reg_479 = 'bx;

assign ap_phi_reg_pp0_iter0_up_reg_497 = 'bx;

assign ap_phi_reg_pp0_iter3_pix_7_reg_405 = 'bx;

assign ap_phi_reg_pp0_iter3_pix_8_reg_395 = 'bx;

assign ap_phi_reg_pp0_iter3_pix_reg_415 = 'bx;

always @ (*) begin
    ap_predicate_op106_load_state4 = ((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op129_store_state4 = ((icmp_ln891_reg_1930_pp0_iter2_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter2_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op76_load_state2 = ((icmp_ln891_reg_1930 == 1'd1) & (icmp_ln881_reg_1921 == 1'd0));
end

always @ (*) begin
    ap_predicate_op78_read_state2 = ((cmp59_i == 1'd1) & (icmp_ln891_reg_1930 == 1'd1) & (icmp_ln881_reg_1921 == 1'd0));
end

always @ (*) begin
    ap_predicate_op83_load_state3 = ((icmp_ln891_reg_1930_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op87_load_state3 = ((icmp_ln891_reg_1930_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op89_store_state3 = ((cmp59_i == 1'd1) & (icmp_ln891_reg_1930_pp0_iter1_reg == 1'd1) & (icmp_ln881_reg_1921_pp0_iter1_reg == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign b_2_fu_1609_p2 = ($signed(zext_ln1033_2_fu_1424_p1) - $signed(b_2_v_i_fu_1605_p1));

assign b_2_v_i_fu_1605_p1 = $signed(b_2_v_v_i_fu_1597_p3);

assign b_2_v_v_i_fu_1597_p3 = ((icmp_ln1030_fu_1357_p2[0:0] == 1'b1) ? select_ln1034_fu_1481_p3 : select_ln1040_fu_1571_p3);

assign b_3_fu_1725_p6 = ((icmp_ln1043_fu_1687_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln1008_fu_1643_p1);

assign b_3_fu_1725_p7 = 'bx;

assign b_3_fu_1725_p8 = {{icmp_ln1014_reg_1950_pp0_iter5_reg}, {and_ln1043_fu_1712_p2}};

assign cmp161_i_fu_596_p2 = ((ap_sig_allocacmp_z == 11'd0) ? 1'b1 : 1'b0);

assign cmp59_i_read_reg_1910 = cmp59_i;

assign icmp_ln1014_fu_618_p2 = ((xor_i == zext_ln1014_fu_614_p1) ? 1'b1 : 1'b0);

assign icmp_ln1030_fu_1357_p2 = ((add_ln1030_1_fu_1338_p2 < add_ln1030_3_fu_1351_p2) ? 1'b1 : 1'b0);

assign icmp_ln1042_fu_1649_p2 = (($signed(tmp_23_reg_2227) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1043_fu_1687_p2 = (($signed(tmp_25_reg_2232) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1052_fu_624_p2 = ((ap_sig_allocacmp_z != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln881_fu_574_p2 = ((ap_sig_allocacmp_z == loopWidth_i) ? 1'b1 : 1'b0);

assign icmp_ln891_fu_590_p2 = ((ap_sig_allocacmp_z < empty) ? 1'b1 : 1'b0);

assign imgRB_read = imgRB_read_local;

assign imgRgb_din = or_ln1054_3_i_fu_1745_p4;

assign imgRgb_write = imgRgb_write_local;

assign lineBuffer_2_address0 = lineBuffer_2_addr_reg_1967_pp0_iter2_reg;

assign lineBuffer_2_address1 = lineBuffer_2_addr_reg_1967;

assign lineBuffer_address0 = lineBuffer_addr_reg_1961;

assign lineBuffer_address1 = zext_ln881_fu_641_p1;

assign or_ln1042_fu_1667_p2 = (tmp_22_reg_2221 | icmp_ln1042_fu_1649_p2);

assign or_ln1054_3_i_fu_1745_p4 = {{{r_4_fu_1700_p3}, {b_3_fu_1725_p9}}, {pix_7_reg_405_pp0_iter5_reg}};

assign p_0_0_0116117861797_i_out = p_0_0_0116117861797_i_load_reg_2032_pp0_iter4_reg;

assign p_0_0_0116217841795_i_out = p_0_0_0116217841795_i_load_reg_2026_pp0_iter4_reg;

assign p_0_0_0116317821793_i_out = p_0_0_0116317821793_i_load_reg_2020_pp0_iter4_reg;

assign p_0_0_01183_217801809_i_out = p_0_0_01183_217801809_i_load_reg_2065_pp0_iter4_reg;

assign p_0_0_01184_217781807_i_out = p_0_0_01184_217781807_i_load_reg_2059_pp0_iter4_reg;

assign p_0_0_01185_217761805_i_out = p_0_0_01185_217761805_i_load_reg_2053_pp0_iter4_reg;

assign p_0_0_0_0_011551706_i_out = p_0_0_0_0_011551706_i_load_reg_2071_pp0_iter4_reg;

assign p_0_1_0_0_011561709_i_out = p_0_1_0_0_011561709_i_load_reg_2077_pp0_iter4_reg;

assign p_0_2_0_0_011571712_i_out = p_0_2_0_0_011571712_i_load_reg_2083_pp0_iter4_reg;

assign r_2_fu_1591_p2 = ($signed(zext_ln1033_2_fu_1424_p1) - $signed(r_2_v_i_fu_1587_p1));

assign r_2_v_i_fu_1587_p1 = $signed(r_2_v_v_i_fu_1579_p3);

assign r_2_v_v_i_fu_1579_p3 = ((icmp_ln1030_fu_1357_p2[0:0] == 1'b1) ? select_ln1033_fu_1416_p3 : select_ln1039_fu_1526_p3);

assign r_3_fu_1672_p3 = ((or_ln1042_fu_1667_p2[0:0] == 1'b1) ? select_ln1042_fu_1659_p3 : trunc_ln1008_1_fu_1646_p1);

assign r_4_fu_1700_p3 = ((icmp_ln1014_reg_1950_pp0_iter5_reg[0:0] == 1'b1) ? pix_reg_415_pp0_iter5_reg : r_3_fu_1672_p3);

assign right_1_i_out = right_4_reg_2043_pp0_iter4_reg;

assign right_2_i_out = right_5_reg_2048_pp0_iter4_reg;

assign right_i_out = right_3_reg_2038_pp0_iter4_reg;

assign select_ln1033_fu_1416_p3 = ((tmp_18_fu_1363_p3[0:0] == 1'b1) ? sub_ln1033_3_fu_1393_p2 : zext_ln1033_1_fu_1412_p1);

assign select_ln1034_fu_1481_p3 = ((tmp_19_fu_1428_p3[0:0] == 1'b1) ? sub_ln1034_3_fu_1458_p2 : zext_ln1034_1_fu_1477_p1);

assign select_ln1039_fu_1526_p3 = ((tmp_20_fu_1489_p3[0:0] == 1'b1) ? sub_ln1039_3_fu_1503_p2 : zext_ln1039_1_fu_1522_p1);

assign select_ln1040_fu_1571_p3 = ((tmp_21_fu_1534_p3[0:0] == 1'b1) ? sub_ln1040_3_fu_1548_p2 : zext_ln1040_1_fu_1567_p1);

assign select_ln1042_fu_1659_p3 = ((xor_ln1042_fu_1654_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln957_10_fu_824_p3 = ((cmp161_i_reg_1934_pp0_iter2_reg[0:0] == 1'b1) ? ap_phi_reg_pp0_iter3_p_0_0_01184_21778_ph_i_reg_377 : p_0_0_01184_217781807_i_fu_188);

assign select_ln957_11_fu_831_p3 = ((cmp161_i_reg_1934_pp0_iter2_reg[0:0] == 1'b1) ? ap_phi_reg_pp0_iter3_p_0_0_01185_21776_ph_i_reg_386 : p_0_0_01185_217761805_i_fu_184);

assign select_ln957_1_fu_764_p3 = ((cmp161_i_reg_1934_pp0_iter2_reg[0:0] == 1'b1) ? tmp_i1_reg_2002 : right_1_fu_176);

assign select_ln957_2_fu_771_p3 = ((cmp161_i_reg_1934_pp0_iter2_reg[0:0] == 1'b1) ? tmp_1_i2_reg_2011 : right_2_fu_180);

assign select_ln957_3_fu_778_p3 = ((cmp161_i_reg_1934_pp0_iter2_reg[0:0] == 1'b1) ? trunc_ln902_reg_1993 : p_0_0_0_0_011551706_i_fu_196);

assign select_ln957_4_fu_784_p3 = ((cmp161_i_reg_1934_pp0_iter2_reg[0:0] == 1'b1) ? tmp_i1_reg_2002 : p_0_1_0_0_011561709_i_fu_200);

assign select_ln957_5_fu_790_p3 = ((cmp161_i_reg_1934_pp0_iter2_reg[0:0] == 1'b1) ? tmp_1_i2_reg_2011 : p_0_2_0_0_011571712_i_fu_204);

assign select_ln957_6_fu_796_p3 = ((cmp161_i_reg_1934_pp0_iter2_reg[0:0] == 1'b1) ? tmp_4_i4_fu_747_p4 : p_0_0_0116117861797_i_fu_168);

assign select_ln957_7_fu_803_p3 = ((cmp161_i_reg_1934_pp0_iter2_reg[0:0] == 1'b1) ? tmp_3_i3_fu_737_p4 : p_0_0_0116217841795_i_fu_164);

assign select_ln957_8_fu_810_p3 = ((cmp161_i_reg_1934_pp0_iter2_reg[0:0] == 1'b1) ? trunc_ln902_1_fu_733_p1 : p_0_0_0116317821793_i_fu_160);

assign select_ln957_9_fu_817_p3 = ((cmp161_i_reg_1934_pp0_iter2_reg[0:0] == 1'b1) ? ap_phi_reg_pp0_iter3_p_0_0_01183_21780_ph_i_reg_368 : p_0_0_01183_217801809_i_fu_192);

assign select_ln957_fu_757_p3 = ((cmp161_i_reg_1934_pp0_iter2_reg[0:0] == 1'b1) ? trunc_ln902_reg_1993 : right_fu_172);

assign sext_ln1033_1_fu_1185_p1 = $signed(sub_ln1033_1_fu_1175_p2);

assign sext_ln1033_2_fu_1385_p1 = $signed(trunc_ln1033_2_i_fu_1375_p4);

assign sext_ln1033_3_fu_1408_p1 = $signed(trunc_ln1033_1_i_fu_1399_p4);

assign sext_ln1033_fu_1181_p1 = $signed(sub_ln1033_fu_1169_p2);

assign sext_ln1034_1_fu_1211_p1 = $signed(sub_ln1034_1_fu_1201_p2);

assign sext_ln1034_2_fu_1450_p1 = $signed(trunc_ln1034_2_i_fu_1440_p4);

assign sext_ln1034_3_fu_1473_p1 = $signed(trunc_ln1034_1_i_fu_1464_p4);

assign sext_ln1034_fu_1207_p1 = $signed(sub_ln1034_fu_1195_p2);

assign sext_ln1039_1_fu_1237_p1 = $signed(sub_ln1039_1_fu_1227_p2);

assign sext_ln1039_2_fu_1496_p1 = $signed(trunc_ln1039_2_i_reg_2194);

assign sext_ln1039_3_fu_1518_p1 = $signed(trunc_ln1039_1_i_fu_1509_p4);

assign sext_ln1039_fu_1233_p1 = $signed(sub_ln1039_fu_1221_p2);

assign sext_ln1040_1_fu_1279_p1 = $signed(sub_ln1040_1_fu_1269_p2);

assign sext_ln1040_2_fu_1541_p1 = $signed(trunc_ln1040_2_i_reg_2205);

assign sext_ln1040_3_fu_1563_p1 = $signed(trunc_ln1040_1_i_fu_1554_p4);

assign sext_ln1040_fu_1275_p1 = $signed(sub_ln1040_fu_1263_p2);

assign sub_ln1023_fu_941_p2 = (zext_ln1023_fu_933_p1 - zext_ln1023_1_fu_937_p1);

assign sub_ln1024_fu_981_p2 = (zext_ln1024_fu_973_p1 - zext_ln1024_1_fu_977_p1);

assign sub_ln1025_fu_1021_p2 = (zext_ln1025_fu_1013_p1 - zext_ln1025_1_fu_1017_p1);

assign sub_ln1026_fu_1061_p2 = (zext_ln1026_fu_1053_p1 - zext_ln1026_1_fu_1057_p1);

assign sub_ln1027_fu_1101_p2 = (zext_ln1027_fu_1093_p1 - zext_ln1027_1_fu_1097_p1);

assign sub_ln1028_fu_1125_p2 = (zext_ln1028_fu_1117_p1 - zext_ln1028_1_fu_1121_p1);

assign sub_ln1033_1_fu_1175_p2 = (zext_ln1025_1_fu_1017_p1 - zext_ln1023_1_fu_937_p1);

assign sub_ln1033_2_fu_1370_p2 = (12'd0 - add_ln1033_reg_2174);

assign sub_ln1033_3_fu_1393_p2 = (13'd0 - zext_ln1033_fu_1389_p1);

assign sub_ln1033_fu_1169_p2 = (zext_ln1025_fu_1013_p1 - zext_ln1023_fu_933_p1);

assign sub_ln1034_1_fu_1201_p2 = (zext_ln1025_1_fu_1017_p1 - zext_ln1027_1_fu_1097_p1);

assign sub_ln1034_2_fu_1435_p2 = (12'd0 - add_ln1034_reg_2181);

assign sub_ln1034_3_fu_1458_p2 = (13'd0 - zext_ln1034_fu_1454_p1);

assign sub_ln1034_fu_1195_p2 = (zext_ln1025_fu_1013_p1 - zext_ln1027_fu_1093_p1);

assign sub_ln1039_1_fu_1227_p2 = (zext_ln1026_1_fu_1057_p1 - zext_ln1024_1_fu_977_p1);

assign sub_ln1039_2_fu_1247_p2 = (12'd0 - add_ln1039_fu_1241_p2);

assign sub_ln1039_3_fu_1503_p2 = (13'd0 - zext_ln1039_fu_1499_p1);

assign sub_ln1039_fu_1221_p2 = (zext_ln1026_fu_1053_p1 - zext_ln1024_fu_973_p1);

assign sub_ln1040_1_fu_1269_p2 = (zext_ln1026_1_fu_1057_p1 - zext_ln1028_1_fu_1121_p1);

assign sub_ln1040_2_fu_1289_p2 = (12'd0 - add_ln1040_fu_1283_p2);

assign sub_ln1040_3_fu_1548_p2 = (13'd0 - zext_ln1040_fu_1544_p1);

assign sub_ln1040_fu_1263_p2 = (zext_ln1026_fu_1053_p1 - zext_ln1028_fu_1117_p1);

assign sub_ln61_4_fu_991_p2 = (10'd0 - trunc_ln61_4_fu_987_p1);

assign sub_ln61_5_fu_1031_p2 = (10'd0 - trunc_ln61_5_fu_1027_p1);

assign sub_ln61_6_fu_1071_p2 = (10'd0 - trunc_ln61_6_fu_1067_p1);

assign sub_ln61_7_fu_1111_p2 = (10'd0 - trunc_ln61_7_fu_1107_p1);

assign sub_ln61_8_fu_1135_p2 = (10'd0 - trunc_ln61_8_fu_1131_p1);

assign sub_ln61_fu_951_p2 = (10'd0 - trunc_ln61_fu_947_p1);

assign tmp_12_fu_957_p3 = sub_ln1023_fu_941_p2[32'd10];

assign tmp_13_fu_997_p3 = sub_ln1024_fu_981_p2[32'd10];

assign tmp_14_fu_1037_p3 = sub_ln1025_fu_1021_p2[32'd10];

assign tmp_15_fu_1077_p3 = sub_ln1026_fu_1061_p2[32'd10];

assign tmp_16_fu_1305_p3 = sub_ln1027_reg_2134[32'd10];

assign tmp_17_fu_1318_p3 = sub_ln1028_reg_2149[32'd10];

assign tmp_18_fu_1363_p3 = add_ln1033_reg_2174[32'd11];

assign tmp_19_fu_1428_p3 = add_ln1034_reg_2181[32'd11];

assign tmp_20_fu_1489_p3 = add_ln1039_reg_2188[32'd11];

assign tmp_21_fu_1534_p3 = add_ln1040_reg_2199[32'd11];

assign tmp_24_fu_1680_p3 = b_2_reg_2215[32'd13];

assign tmp_3_i3_fu_737_p4 = {{lineBuffer_2_q1[19:10]}};

assign tmp_4_i4_fu_747_p4 = {{lineBuffer_2_q1[29:20]}};

assign trunc_ln1008_1_fu_1646_p1 = r_2_reg_2210[9:0];

assign trunc_ln1008_fu_1643_p1 = b_2_reg_2215[9:0];

assign trunc_ln1033_1_i_fu_1399_p4 = {{add_ln1033_reg_2174[11:1]}};

assign trunc_ln1033_2_i_fu_1375_p4 = {{sub_ln1033_2_fu_1370_p2[11:1]}};

assign trunc_ln1034_1_i_fu_1464_p4 = {{add_ln1034_reg_2181[11:1]}};

assign trunc_ln1034_2_i_fu_1440_p4 = {{sub_ln1034_2_fu_1435_p2[11:1]}};

assign trunc_ln1039_1_i_fu_1509_p4 = {{add_ln1039_reg_2188[11:1]}};

assign trunc_ln1040_1_i_fu_1554_p4 = {{add_ln1040_reg_2199[11:1]}};

assign trunc_ln61_4_fu_987_p1 = sub_ln1024_fu_981_p2[9:0];

assign trunc_ln61_5_fu_1027_p1 = sub_ln1025_fu_1021_p2[9:0];

assign trunc_ln61_6_fu_1067_p1 = sub_ln1026_fu_1061_p2[9:0];

assign trunc_ln61_7_fu_1107_p1 = sub_ln1027_fu_1101_p2[9:0];

assign trunc_ln61_8_fu_1131_p1 = sub_ln1028_fu_1125_p2[9:0];

assign trunc_ln61_fu_947_p1 = sub_ln1023_fu_941_p2[9:0];

assign trunc_ln881_fu_586_p1 = ap_sig_allocacmp_z[0:0];

assign trunc_ln902_1_fu_733_p1 = lineBuffer_2_q1[9:0];

assign trunc_ln902_fu_670_p1 = lineBuffer_q1[9:0];

assign trunc_ln913_fu_646_p1 = imgRB_dout[9:0];

assign x_8_fu_580_p2 = (ap_sig_allocacmp_z + 11'd1);

assign xor_ln1014_1_fu_608_p2 = (xor_ln1014_fu_602_p2 ^ 1'd1);

assign xor_ln1014_2_fu_1707_p2 = (icmp_ln1014_reg_1950_pp0_iter5_reg ^ 1'd1);

assign xor_ln1014_fu_602_p2 = (trunc_ln881_fu_586_p1 ^ empty_52);

assign xor_ln1042_fu_1654_p2 = (tmp_22_reg_2221 ^ 1'd1);

assign zext_ln1014_fu_614_p1 = xor_ln1014_1_fu_608_p2;

assign zext_ln1023_1_fu_937_p1 = right_fu_172;

assign zext_ln1023_fu_933_p1 = ap_phi_reg_pp0_iter4_left_reg_470;

assign zext_ln1024_1_fu_977_p1 = ap_phi_reg_pp0_iter4_down_reg_443;

assign zext_ln1024_fu_973_p1 = ap_phi_reg_pp0_iter4_up_reg_497;

assign zext_ln1025_1_fu_1017_p1 = right_1_fu_176;

assign zext_ln1025_fu_1013_p1 = ap_phi_reg_pp0_iter4_left_1_reg_461;

assign zext_ln1026_1_fu_1057_p1 = ap_phi_reg_pp0_iter4_down_1_reg_434;

assign zext_ln1026_fu_1053_p1 = ap_phi_reg_pp0_iter4_up_1_reg_488;

assign zext_ln1027_1_fu_1097_p1 = right_2_fu_180;

assign zext_ln1027_fu_1093_p1 = ap_phi_reg_pp0_iter4_left_2_reg_452;

assign zext_ln1028_1_fu_1121_p1 = ap_phi_reg_pp0_iter4_down_2_reg_425;

assign zext_ln1028_fu_1117_p1 = ap_phi_reg_pp0_iter4_up_2_reg_479;

assign zext_ln1030_1_fu_1145_p1 = DGh_fu_1045_p3;

assign zext_ln1030_2_fu_1331_p1 = add_ln1030_reg_2164;

assign zext_ln1030_3_fu_1334_p1 = DBh_fu_1312_p3;

assign zext_ln1030_4_fu_1155_p1 = DRv_fu_1005_p3;

assign zext_ln1030_5_fu_1159_p1 = DGv_fu_1085_p3;

assign zext_ln1030_6_fu_1344_p1 = add_ln1030_2_reg_2169;

assign zext_ln1030_7_fu_1347_p1 = DBv_fu_1325_p3;

assign zext_ln1030_fu_1141_p1 = DRh_fu_965_p3;

assign zext_ln1033_1_fu_1412_p1 = $unsigned(sext_ln1033_3_fu_1408_p1);

assign zext_ln1033_2_fu_1424_p1 = pix_7_reg_405_pp0_iter4_reg;

assign zext_ln1033_fu_1389_p1 = $unsigned(sext_ln1033_2_fu_1385_p1);

assign zext_ln1034_1_fu_1477_p1 = $unsigned(sext_ln1034_3_fu_1473_p1);

assign zext_ln1034_fu_1454_p1 = $unsigned(sext_ln1034_2_fu_1450_p1);

assign zext_ln1039_1_fu_1522_p1 = $unsigned(sext_ln1039_3_fu_1518_p1);

assign zext_ln1039_fu_1499_p1 = $unsigned(sext_ln1039_2_fu_1496_p1);

assign zext_ln1040_1_fu_1567_p1 = $unsigned(sext_ln1040_3_fu_1563_p1);

assign zext_ln1040_fu_1544_p1 = $unsigned(sext_ln1040_2_fu_1541_p1);

assign zext_ln881_fu_641_p1 = x_8_reg_1925;

endmodule //design_1_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2
