-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_tpg_0_0_v_tpgHlsDataFlow is
port (
    s_axis_video_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    height_val4 : IN STD_LOGIC_VECTOR (15 downto 0);
    width_val7 : IN STD_LOGIC_VECTOR (15 downto 0);
    field_id_val8 : IN STD_LOGIC_VECTOR (15 downto 0);
    fid_in_val9 : IN STD_LOGIC_VECTOR (0 downto 0);
    passthruStartX_val10 : IN STD_LOGIC_VECTOR (15 downto 0);
    passthruStartY_val11 : IN STD_LOGIC_VECTOR (15 downto 0);
    passthruEndX_val12 : IN STD_LOGIC_VECTOR (15 downto 0);
    passthruEndY_val13 : IN STD_LOGIC_VECTOR (15 downto 0);
    enableInput_val15 : IN STD_LOGIC_VECTOR (7 downto 0);
    bckgndId_val16 : IN STD_LOGIC_VECTOR (7 downto 0);
    motionSpeed_val17 : IN STD_LOGIC_VECTOR (7 downto 0);
    colorFormat_val20 : IN STD_LOGIC_VECTOR (7 downto 0);
    ZplateHorContStart_val21 : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateHorContDelta_val22 : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContStart_val23 : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContDelta_val24 : IN STD_LOGIC_VECTOR (15 downto 0);
    dpDynamicRange_val25 : IN STD_LOGIC_VECTOR (7 downto 0);
    dpYUVCoef_val26 : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    fid : OUT STD_LOGIC_VECTOR (0 downto 0);
    s : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    field_id_val8_ap_vld : IN STD_LOGIC;
    fid_in_val9_ap_vld : IN STD_LOGIC;
    passthruStartX_val10_ap_vld : IN STD_LOGIC;
    passthruStartY_val11_ap_vld : IN STD_LOGIC;
    passthruEndX_val12_ap_vld : IN STD_LOGIC;
    passthruEndY_val13_ap_vld : IN STD_LOGIC;
    bckgndId_val16_ap_vld : IN STD_LOGIC;
    motionSpeed_val17_ap_vld : IN STD_LOGIC;
    ZplateHorContStart_val21_ap_vld : IN STD_LOGIC;
    ZplateHorContDelta_val22_ap_vld : IN STD_LOGIC;
    ZplateVerContStart_val23_ap_vld : IN STD_LOGIC;
    ZplateVerContDelta_val24_ap_vld : IN STD_LOGIC;
    dpDynamicRange_val25_ap_vld : IN STD_LOGIC;
    dpYUVCoef_val26_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    s_axis_video_TVALID : IN STD_LOGIC;
    s_axis_video_TREADY : OUT STD_LOGIC;
    enableInput_val15_ap_vld : IN STD_LOGIC;
    height_val4_ap_vld : IN STD_LOGIC;
    width_val7_ap_vld : IN STD_LOGIC;
    colorFormat_val20_ap_vld : IN STD_LOGIC;
    s_ap_vld : IN STD_LOGIC;
    m_axis_video_TVALID : OUT STD_LOGIC;
    m_axis_video_TREADY : IN STD_LOGIC;
    fid_ap_vld : OUT STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of design_1_v_tpg_0_0_v_tpgHlsDataFlow is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal entry_proc_U0_ap_start : STD_LOGIC;
    signal entry_proc_U0_ap_done : STD_LOGIC;
    signal entry_proc_U0_ap_continue : STD_LOGIC;
    signal entry_proc_U0_ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_ready : STD_LOGIC;
    signal entry_proc_U0_start_out : STD_LOGIC;
    signal entry_proc_U0_start_write : STD_LOGIC;
    signal entry_proc_U0_field_id_val8_c_din : STD_LOGIC_VECTOR (15 downto 0);
    signal entry_proc_U0_field_id_val8_c_write : STD_LOGIC;
    signal entry_proc_U0_fid_in_val9_c_din : STD_LOGIC_VECTOR (0 downto 0);
    signal entry_proc_U0_fid_in_val9_c_write : STD_LOGIC;
    signal entry_proc_U0_passthruStartX_val10_c_din : STD_LOGIC_VECTOR (15 downto 0);
    signal entry_proc_U0_passthruStartX_val10_c_write : STD_LOGIC;
    signal entry_proc_U0_passthruStartY_val11_c_din : STD_LOGIC_VECTOR (15 downto 0);
    signal entry_proc_U0_passthruStartY_val11_c_write : STD_LOGIC;
    signal entry_proc_U0_passthruEndX_val12_c_din : STD_LOGIC_VECTOR (15 downto 0);
    signal entry_proc_U0_passthruEndX_val12_c_write : STD_LOGIC;
    signal entry_proc_U0_passthruEndY_val13_c_din : STD_LOGIC_VECTOR (15 downto 0);
    signal entry_proc_U0_passthruEndY_val13_c_write : STD_LOGIC;
    signal entry_proc_U0_bckgndId_val16_c_din : STD_LOGIC_VECTOR (7 downto 0);
    signal entry_proc_U0_bckgndId_val16_c_write : STD_LOGIC;
    signal entry_proc_U0_motionSpeed_val17_c_din : STD_LOGIC_VECTOR (7 downto 0);
    signal entry_proc_U0_motionSpeed_val17_c_write : STD_LOGIC;
    signal entry_proc_U0_ZplateHorContStart_val21_c_din : STD_LOGIC_VECTOR (15 downto 0);
    signal entry_proc_U0_ZplateHorContStart_val21_c_write : STD_LOGIC;
    signal entry_proc_U0_ZplateHorContDelta_val22_c_din : STD_LOGIC_VECTOR (15 downto 0);
    signal entry_proc_U0_ZplateHorContDelta_val22_c_write : STD_LOGIC;
    signal entry_proc_U0_ZplateVerContStart_val23_c_din : STD_LOGIC_VECTOR (15 downto 0);
    signal entry_proc_U0_ZplateVerContStart_val23_c_write : STD_LOGIC;
    signal entry_proc_U0_ZplateVerContDelta_val24_c_din : STD_LOGIC_VECTOR (15 downto 0);
    signal entry_proc_U0_ZplateVerContDelta_val24_c_write : STD_LOGIC;
    signal entry_proc_U0_dpDynamicRange_val25_c_din : STD_LOGIC_VECTOR (7 downto 0);
    signal entry_proc_U0_dpDynamicRange_val25_c_write : STD_LOGIC;
    signal entry_proc_U0_dpYUVCoef_val26_c_din : STD_LOGIC_VECTOR (7 downto 0);
    signal entry_proc_U0_dpYUVCoef_val26_c_write : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_ap_start : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_ap_done : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_ap_continue : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_ap_idle : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_ap_ready : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_s_axis_video_TREADY : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_srcYUV_din : STD_LOGIC_VECTOR (29 downto 0);
    signal AXIvideo2MultiPixStream_U0_srcYUV_write : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_height_val4_c3_din : STD_LOGIC_VECTOR (15 downto 0);
    signal AXIvideo2MultiPixStream_U0_height_val4_c3_write : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_width_val7_c4_din : STD_LOGIC_VECTOR (15 downto 0);
    signal AXIvideo2MultiPixStream_U0_width_val7_c4_write : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_enableInput_val15_c_din : STD_LOGIC_VECTOR (7 downto 0);
    signal AXIvideo2MultiPixStream_U0_enableInput_val15_c_write : STD_LOGIC;
    signal AXIvideo2MultiPixStream_U0_colorFormat_val20_c5_din : STD_LOGIC_VECTOR (7 downto 0);
    signal AXIvideo2MultiPixStream_U0_colorFormat_val20_c5_write : STD_LOGIC;
    signal tpgBackground_U0_ap_start : STD_LOGIC;
    signal tpgBackground_U0_ap_done : STD_LOGIC;
    signal tpgBackground_U0_ap_continue : STD_LOGIC;
    signal tpgBackground_U0_ap_idle : STD_LOGIC;
    signal tpgBackground_U0_ap_ready : STD_LOGIC;
    signal tpgBackground_U0_srcYUV_read : STD_LOGIC;
    signal tpgBackground_U0_height_val_read : STD_LOGIC;
    signal tpgBackground_U0_width_val_read : STD_LOGIC;
    signal tpgBackground_U0_passthruStartX_val_read : STD_LOGIC;
    signal tpgBackground_U0_passthruStartY_val_read : STD_LOGIC;
    signal tpgBackground_U0_passthruEndX_val_read : STD_LOGIC;
    signal tpgBackground_U0_passthruEndY_val_read : STD_LOGIC;
    signal tpgBackground_U0_enableInput_val_read : STD_LOGIC;
    signal tpgBackground_U0_patternId_val_read : STD_LOGIC;
    signal tpgBackground_U0_ZplateHorContStart_val_read : STD_LOGIC;
    signal tpgBackground_U0_ZplateHorContDelta_val_read : STD_LOGIC;
    signal tpgBackground_U0_ZplateVerContStart_val_read : STD_LOGIC;
    signal tpgBackground_U0_ZplateVerContDelta_val_read : STD_LOGIC;
    signal tpgBackground_U0_dpDynamicRange_val_read : STD_LOGIC;
    signal tpgBackground_U0_dpYUVCoef_val_read : STD_LOGIC;
    signal tpgBackground_U0_motionSpeed_val_read : STD_LOGIC;
    signal tpgBackground_U0_colorFormat_val_read : STD_LOGIC;
    signal tpgBackground_U0_ovrlayYUV_din : STD_LOGIC_VECTOR (29 downto 0);
    signal tpgBackground_U0_ovrlayYUV_write : STD_LOGIC;
    signal tpgBackground_U0_height_val4_c_din : STD_LOGIC_VECTOR (10 downto 0);
    signal tpgBackground_U0_height_val4_c_write : STD_LOGIC;
    signal tpgBackground_U0_width_val7_c_din : STD_LOGIC_VECTOR (10 downto 0);
    signal tpgBackground_U0_width_val7_c_write : STD_LOGIC;
    signal tpgBackground_U0_colorFormat_val20_c_din : STD_LOGIC_VECTOR (7 downto 0);
    signal tpgBackground_U0_colorFormat_val20_c_write : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_ap_start : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_ap_done : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_ap_continue : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_ap_idle : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_ap_ready : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_ovrlayYUV_read : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TVALID : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal MultiPixStream2AXIvideo_U0_m_axis_video_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal MultiPixStream2AXIvideo_U0_height_val4_read : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_width_val7_read : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_colorFormat_val20_read : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_fid_in_val9_read : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_fid : STD_LOGIC_VECTOR (0 downto 0);
    signal MultiPixStream2AXIvideo_U0_fid_ap_vld : STD_LOGIC;
    signal MultiPixStream2AXIvideo_U0_field_id_val8_read : STD_LOGIC;
    signal field_id_val8_c_full_n : STD_LOGIC;
    signal field_id_val8_c_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal field_id_val8_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal field_id_val8_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal field_id_val8_c_empty_n : STD_LOGIC;
    signal fid_in_val9_c_full_n : STD_LOGIC;
    signal fid_in_val9_c_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal fid_in_val9_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal fid_in_val9_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal fid_in_val9_c_empty_n : STD_LOGIC;
    signal passthruStartX_val10_c_full_n : STD_LOGIC;
    signal passthruStartX_val10_c_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal passthruStartX_val10_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal passthruStartX_val10_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal passthruStartX_val10_c_empty_n : STD_LOGIC;
    signal passthruStartY_val11_c_full_n : STD_LOGIC;
    signal passthruStartY_val11_c_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal passthruStartY_val11_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal passthruStartY_val11_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal passthruStartY_val11_c_empty_n : STD_LOGIC;
    signal passthruEndX_val12_c_full_n : STD_LOGIC;
    signal passthruEndX_val12_c_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal passthruEndX_val12_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal passthruEndX_val12_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal passthruEndX_val12_c_empty_n : STD_LOGIC;
    signal passthruEndY_val13_c_full_n : STD_LOGIC;
    signal passthruEndY_val13_c_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal passthruEndY_val13_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal passthruEndY_val13_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal passthruEndY_val13_c_empty_n : STD_LOGIC;
    signal bckgndId_val16_c_full_n : STD_LOGIC;
    signal bckgndId_val16_c_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal bckgndId_val16_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal bckgndId_val16_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal bckgndId_val16_c_empty_n : STD_LOGIC;
    signal motionSpeed_val17_c_full_n : STD_LOGIC;
    signal motionSpeed_val17_c_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal motionSpeed_val17_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal motionSpeed_val17_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal motionSpeed_val17_c_empty_n : STD_LOGIC;
    signal ZplateHorContStart_val21_c_full_n : STD_LOGIC;
    signal ZplateHorContStart_val21_c_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal ZplateHorContStart_val21_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal ZplateHorContStart_val21_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal ZplateHorContStart_val21_c_empty_n : STD_LOGIC;
    signal ZplateHorContDelta_val22_c_full_n : STD_LOGIC;
    signal ZplateHorContDelta_val22_c_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal ZplateHorContDelta_val22_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal ZplateHorContDelta_val22_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal ZplateHorContDelta_val22_c_empty_n : STD_LOGIC;
    signal ZplateVerContStart_val23_c_full_n : STD_LOGIC;
    signal ZplateVerContStart_val23_c_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal ZplateVerContStart_val23_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal ZplateVerContStart_val23_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal ZplateVerContStart_val23_c_empty_n : STD_LOGIC;
    signal ZplateVerContDelta_val24_c_full_n : STD_LOGIC;
    signal ZplateVerContDelta_val24_c_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal ZplateVerContDelta_val24_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal ZplateVerContDelta_val24_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal ZplateVerContDelta_val24_c_empty_n : STD_LOGIC;
    signal dpDynamicRange_val25_c_full_n : STD_LOGIC;
    signal dpDynamicRange_val25_c_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal dpDynamicRange_val25_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal dpDynamicRange_val25_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal dpDynamicRange_val25_c_empty_n : STD_LOGIC;
    signal dpYUVCoef_val26_c_full_n : STD_LOGIC;
    signal dpYUVCoef_val26_c_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal dpYUVCoef_val26_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal dpYUVCoef_val26_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal dpYUVCoef_val26_c_empty_n : STD_LOGIC;
    signal srcYUV_full_n : STD_LOGIC;
    signal srcYUV_dout : STD_LOGIC_VECTOR (29 downto 0);
    signal srcYUV_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal srcYUV_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal srcYUV_empty_n : STD_LOGIC;
    signal height_val4_c3_full_n : STD_LOGIC;
    signal height_val4_c3_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal height_val4_c3_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal height_val4_c3_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal height_val4_c3_empty_n : STD_LOGIC;
    signal width_val7_c4_full_n : STD_LOGIC;
    signal width_val7_c4_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal width_val7_c4_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal width_val7_c4_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal width_val7_c4_empty_n : STD_LOGIC;
    signal enableInput_val15_c_full_n : STD_LOGIC;
    signal enableInput_val15_c_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal enableInput_val15_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal enableInput_val15_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal enableInput_val15_c_empty_n : STD_LOGIC;
    signal colorFormat_val20_c5_full_n : STD_LOGIC;
    signal colorFormat_val20_c5_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal colorFormat_val20_c5_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal colorFormat_val20_c5_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal colorFormat_val20_c5_empty_n : STD_LOGIC;
    signal ovrlayYUV_full_n : STD_LOGIC;
    signal ovrlayYUV_dout : STD_LOGIC_VECTOR (29 downto 0);
    signal ovrlayYUV_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal ovrlayYUV_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal ovrlayYUV_empty_n : STD_LOGIC;
    signal height_val4_c_full_n : STD_LOGIC;
    signal height_val4_c_dout : STD_LOGIC_VECTOR (10 downto 0);
    signal height_val4_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal height_val4_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal height_val4_c_empty_n : STD_LOGIC;
    signal width_val7_c_full_n : STD_LOGIC;
    signal width_val7_c_dout : STD_LOGIC_VECTOR (10 downto 0);
    signal width_val7_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal width_val7_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal width_val7_c_empty_n : STD_LOGIC;
    signal colorFormat_val20_c_full_n : STD_LOGIC;
    signal colorFormat_val20_c_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal colorFormat_val20_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal colorFormat_val20_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal colorFormat_val20_c_empty_n : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_entry_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_entry_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_AXIvideo2MultiPixStream_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_tpgBackground_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_tpgBackground_U0_ap_ready : STD_LOGIC;
    signal start_for_MultiPixStream2AXIvideo_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_MultiPixStream2AXIvideo_U0_full_n : STD_LOGIC;
    signal start_for_MultiPixStream2AXIvideo_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_MultiPixStream2AXIvideo_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_tpg_0_0_entry_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        field_id_val8 : IN STD_LOGIC_VECTOR (15 downto 0);
        field_id_val8_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        field_id_val8_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        field_id_val8_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        field_id_val8_c_full_n : IN STD_LOGIC;
        field_id_val8_c_write : OUT STD_LOGIC;
        fid_in_val9 : IN STD_LOGIC_VECTOR (0 downto 0);
        fid_in_val9_c_din : OUT STD_LOGIC_VECTOR (0 downto 0);
        fid_in_val9_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        fid_in_val9_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        fid_in_val9_c_full_n : IN STD_LOGIC;
        fid_in_val9_c_write : OUT STD_LOGIC;
        passthruStartX_val10 : IN STD_LOGIC_VECTOR (15 downto 0);
        passthruStartX_val10_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        passthruStartX_val10_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruStartX_val10_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruStartX_val10_c_full_n : IN STD_LOGIC;
        passthruStartX_val10_c_write : OUT STD_LOGIC;
        passthruStartY_val11 : IN STD_LOGIC_VECTOR (15 downto 0);
        passthruStartY_val11_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        passthruStartY_val11_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruStartY_val11_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruStartY_val11_c_full_n : IN STD_LOGIC;
        passthruStartY_val11_c_write : OUT STD_LOGIC;
        passthruEndX_val12 : IN STD_LOGIC_VECTOR (15 downto 0);
        passthruEndX_val12_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        passthruEndX_val12_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruEndX_val12_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruEndX_val12_c_full_n : IN STD_LOGIC;
        passthruEndX_val12_c_write : OUT STD_LOGIC;
        passthruEndY_val13 : IN STD_LOGIC_VECTOR (15 downto 0);
        passthruEndY_val13_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        passthruEndY_val13_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruEndY_val13_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruEndY_val13_c_full_n : IN STD_LOGIC;
        passthruEndY_val13_c_write : OUT STD_LOGIC;
        bckgndId_val16 : IN STD_LOGIC_VECTOR (7 downto 0);
        bckgndId_val16_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        bckgndId_val16_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        bckgndId_val16_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        bckgndId_val16_c_full_n : IN STD_LOGIC;
        bckgndId_val16_c_write : OUT STD_LOGIC;
        motionSpeed_val17 : IN STD_LOGIC_VECTOR (7 downto 0);
        motionSpeed_val17_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        motionSpeed_val17_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        motionSpeed_val17_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        motionSpeed_val17_c_full_n : IN STD_LOGIC;
        motionSpeed_val17_c_write : OUT STD_LOGIC;
        ZplateHorContStart_val21 : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateHorContStart_val21_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        ZplateHorContStart_val21_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateHorContStart_val21_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateHorContStart_val21_c_full_n : IN STD_LOGIC;
        ZplateHorContStart_val21_c_write : OUT STD_LOGIC;
        ZplateHorContDelta_val22 : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateHorContDelta_val22_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        ZplateHorContDelta_val22_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateHorContDelta_val22_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateHorContDelta_val22_c_full_n : IN STD_LOGIC;
        ZplateHorContDelta_val22_c_write : OUT STD_LOGIC;
        ZplateVerContStart_val23 : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateVerContStart_val23_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        ZplateVerContStart_val23_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateVerContStart_val23_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateVerContStart_val23_c_full_n : IN STD_LOGIC;
        ZplateVerContStart_val23_c_write : OUT STD_LOGIC;
        ZplateVerContDelta_val24 : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateVerContDelta_val24_c_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        ZplateVerContDelta_val24_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateVerContDelta_val24_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateVerContDelta_val24_c_full_n : IN STD_LOGIC;
        ZplateVerContDelta_val24_c_write : OUT STD_LOGIC;
        dpDynamicRange_val25 : IN STD_LOGIC_VECTOR (7 downto 0);
        dpDynamicRange_val25_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dpDynamicRange_val25_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        dpDynamicRange_val25_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        dpDynamicRange_val25_c_full_n : IN STD_LOGIC;
        dpDynamicRange_val25_c_write : OUT STD_LOGIC;
        dpYUVCoef_val26 : IN STD_LOGIC_VECTOR (7 downto 0);
        dpYUVCoef_val26_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dpYUVCoef_val26_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        dpYUVCoef_val26_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        dpYUVCoef_val26_c_full_n : IN STD_LOGIC;
        dpYUVCoef_val26_c_write : OUT STD_LOGIC );
    end component;


    component design_1_v_tpg_0_0_AXIvideo2MultiPixStream IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_video_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        s_axis_video_TVALID : IN STD_LOGIC;
        s_axis_video_TREADY : OUT STD_LOGIC;
        s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        srcYUV_din : OUT STD_LOGIC_VECTOR (29 downto 0);
        srcYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        srcYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        srcYUV_full_n : IN STD_LOGIC;
        srcYUV_write : OUT STD_LOGIC;
        enableInput_val : IN STD_LOGIC_VECTOR (7 downto 0);
        Height_val : IN STD_LOGIC_VECTOR (15 downto 0);
        WidthIn_val : IN STD_LOGIC_VECTOR (15 downto 0);
        colorFormat_val : IN STD_LOGIC_VECTOR (7 downto 0);
        height_val4_c3_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        height_val4_c3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        height_val4_c3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        height_val4_c3_full_n : IN STD_LOGIC;
        height_val4_c3_write : OUT STD_LOGIC;
        width_val7_c4_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        width_val7_c4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        width_val7_c4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        width_val7_c4_full_n : IN STD_LOGIC;
        width_val7_c4_write : OUT STD_LOGIC;
        enableInput_val15_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        enableInput_val15_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        enableInput_val15_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        enableInput_val15_c_full_n : IN STD_LOGIC;
        enableInput_val15_c_write : OUT STD_LOGIC;
        colorFormat_val20_c5_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        colorFormat_val20_c5_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        colorFormat_val20_c5_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        colorFormat_val20_c5_full_n : IN STD_LOGIC;
        colorFormat_val20_c5_write : OUT STD_LOGIC );
    end component;


    component design_1_v_tpg_0_0_tpgBackground IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        srcYUV_dout : IN STD_LOGIC_VECTOR (29 downto 0);
        srcYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        srcYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        srcYUV_empty_n : IN STD_LOGIC;
        srcYUV_read : OUT STD_LOGIC;
        height_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        height_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        height_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        height_val_empty_n : IN STD_LOGIC;
        height_val_read : OUT STD_LOGIC;
        width_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        width_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        width_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        width_val_empty_n : IN STD_LOGIC;
        width_val_read : OUT STD_LOGIC;
        passthruStartX_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        passthruStartX_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruStartX_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruStartX_val_empty_n : IN STD_LOGIC;
        passthruStartX_val_read : OUT STD_LOGIC;
        passthruStartY_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        passthruStartY_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruStartY_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruStartY_val_empty_n : IN STD_LOGIC;
        passthruStartY_val_read : OUT STD_LOGIC;
        passthruEndX_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        passthruEndX_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruEndX_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruEndX_val_empty_n : IN STD_LOGIC;
        passthruEndX_val_read : OUT STD_LOGIC;
        passthruEndY_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        passthruEndY_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruEndY_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        passthruEndY_val_empty_n : IN STD_LOGIC;
        passthruEndY_val_read : OUT STD_LOGIC;
        enableInput_val_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        enableInput_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        enableInput_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        enableInput_val_empty_n : IN STD_LOGIC;
        enableInput_val_read : OUT STD_LOGIC;
        patternId_val_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        patternId_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        patternId_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        patternId_val_empty_n : IN STD_LOGIC;
        patternId_val_read : OUT STD_LOGIC;
        ZplateHorContStart_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateHorContStart_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateHorContStart_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateHorContStart_val_empty_n : IN STD_LOGIC;
        ZplateHorContStart_val_read : OUT STD_LOGIC;
        ZplateHorContDelta_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateHorContDelta_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateHorContDelta_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateHorContDelta_val_empty_n : IN STD_LOGIC;
        ZplateHorContDelta_val_read : OUT STD_LOGIC;
        ZplateVerContStart_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateVerContStart_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateVerContStart_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateVerContStart_val_empty_n : IN STD_LOGIC;
        ZplateVerContStart_val_read : OUT STD_LOGIC;
        ZplateVerContDelta_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateVerContDelta_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateVerContDelta_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        ZplateVerContDelta_val_empty_n : IN STD_LOGIC;
        ZplateVerContDelta_val_read : OUT STD_LOGIC;
        dpDynamicRange_val_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        dpDynamicRange_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        dpDynamicRange_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        dpDynamicRange_val_empty_n : IN STD_LOGIC;
        dpDynamicRange_val_read : OUT STD_LOGIC;
        dpYUVCoef_val_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        dpYUVCoef_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        dpYUVCoef_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        dpYUVCoef_val_empty_n : IN STD_LOGIC;
        dpYUVCoef_val_read : OUT STD_LOGIC;
        motionSpeed_val_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        motionSpeed_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        motionSpeed_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        motionSpeed_val_empty_n : IN STD_LOGIC;
        motionSpeed_val_read : OUT STD_LOGIC;
        colorFormat_val_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        colorFormat_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        colorFormat_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        colorFormat_val_empty_n : IN STD_LOGIC;
        colorFormat_val_read : OUT STD_LOGIC;
        ovrlayYUV_din : OUT STD_LOGIC_VECTOR (29 downto 0);
        ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        ovrlayYUV_full_n : IN STD_LOGIC;
        ovrlayYUV_write : OUT STD_LOGIC;
        height_val4_c_din : OUT STD_LOGIC_VECTOR (10 downto 0);
        height_val4_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        height_val4_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        height_val4_c_full_n : IN STD_LOGIC;
        height_val4_c_write : OUT STD_LOGIC;
        width_val7_c_din : OUT STD_LOGIC_VECTOR (10 downto 0);
        width_val7_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        width_val7_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        width_val7_c_full_n : IN STD_LOGIC;
        width_val7_c_write : OUT STD_LOGIC;
        colorFormat_val20_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        colorFormat_val20_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        colorFormat_val20_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        colorFormat_val20_c_full_n : IN STD_LOGIC;
        colorFormat_val20_c_write : OUT STD_LOGIC;
        s : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component design_1_v_tpg_0_0_MultiPixStream2AXIvideo IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ovrlayYUV_dout : IN STD_LOGIC_VECTOR (29 downto 0);
        ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        ovrlayYUV_empty_n : IN STD_LOGIC;
        ovrlayYUV_read : OUT STD_LOGIC;
        m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axis_video_TVALID : OUT STD_LOGIC;
        m_axis_video_TREADY : IN STD_LOGIC;
        m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
        height_val4_dout : IN STD_LOGIC_VECTOR (10 downto 0);
        height_val4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        height_val4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        height_val4_empty_n : IN STD_LOGIC;
        height_val4_read : OUT STD_LOGIC;
        width_val7_dout : IN STD_LOGIC_VECTOR (10 downto 0);
        width_val7_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        width_val7_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        width_val7_empty_n : IN STD_LOGIC;
        width_val7_read : OUT STD_LOGIC;
        colorFormat_val20_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        colorFormat_val20_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        colorFormat_val20_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        colorFormat_val20_empty_n : IN STD_LOGIC;
        colorFormat_val20_read : OUT STD_LOGIC;
        fid_in_val9_dout : IN STD_LOGIC_VECTOR (0 downto 0);
        fid_in_val9_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        fid_in_val9_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        fid_in_val9_empty_n : IN STD_LOGIC;
        fid_in_val9_read : OUT STD_LOGIC;
        fid : OUT STD_LOGIC_VECTOR (0 downto 0);
        fid_ap_vld : OUT STD_LOGIC;
        field_id_val8_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        field_id_val8_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        field_id_val8_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        field_id_val8_empty_n : IN STD_LOGIC;
        field_id_val8_read : OUT STD_LOGIC );
    end component;


    component design_1_v_tpg_0_0_fifo_w16_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component design_1_v_tpg_0_0_fifo_w1_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component design_1_v_tpg_0_0_fifo_w16_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component design_1_v_tpg_0_0_fifo_w8_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component design_1_v_tpg_0_0_fifo_w30_d16_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (29 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (29 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component design_1_v_tpg_0_0_fifo_w16_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component design_1_v_tpg_0_0_fifo_w8_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component design_1_v_tpg_0_0_fifo_w11_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (10 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (10 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component design_1_v_tpg_0_0_start_for_MultiPixStream2AXIvideo_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    entry_proc_U0 : component design_1_v_tpg_0_0_entry_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => entry_proc_U0_ap_start,
        start_full_n => start_for_MultiPixStream2AXIvideo_U0_full_n,
        ap_done => entry_proc_U0_ap_done,
        ap_continue => entry_proc_U0_ap_continue,
        ap_idle => entry_proc_U0_ap_idle,
        ap_ready => entry_proc_U0_ap_ready,
        start_out => entry_proc_U0_start_out,
        start_write => entry_proc_U0_start_write,
        field_id_val8 => field_id_val8,
        field_id_val8_c_din => entry_proc_U0_field_id_val8_c_din,
        field_id_val8_c_num_data_valid => field_id_val8_c_num_data_valid,
        field_id_val8_c_fifo_cap => field_id_val8_c_fifo_cap,
        field_id_val8_c_full_n => field_id_val8_c_full_n,
        field_id_val8_c_write => entry_proc_U0_field_id_val8_c_write,
        fid_in_val9 => fid_in_val9,
        fid_in_val9_c_din => entry_proc_U0_fid_in_val9_c_din,
        fid_in_val9_c_num_data_valid => fid_in_val9_c_num_data_valid,
        fid_in_val9_c_fifo_cap => fid_in_val9_c_fifo_cap,
        fid_in_val9_c_full_n => fid_in_val9_c_full_n,
        fid_in_val9_c_write => entry_proc_U0_fid_in_val9_c_write,
        passthruStartX_val10 => passthruStartX_val10,
        passthruStartX_val10_c_din => entry_proc_U0_passthruStartX_val10_c_din,
        passthruStartX_val10_c_num_data_valid => passthruStartX_val10_c_num_data_valid,
        passthruStartX_val10_c_fifo_cap => passthruStartX_val10_c_fifo_cap,
        passthruStartX_val10_c_full_n => passthruStartX_val10_c_full_n,
        passthruStartX_val10_c_write => entry_proc_U0_passthruStartX_val10_c_write,
        passthruStartY_val11 => passthruStartY_val11,
        passthruStartY_val11_c_din => entry_proc_U0_passthruStartY_val11_c_din,
        passthruStartY_val11_c_num_data_valid => passthruStartY_val11_c_num_data_valid,
        passthruStartY_val11_c_fifo_cap => passthruStartY_val11_c_fifo_cap,
        passthruStartY_val11_c_full_n => passthruStartY_val11_c_full_n,
        passthruStartY_val11_c_write => entry_proc_U0_passthruStartY_val11_c_write,
        passthruEndX_val12 => passthruEndX_val12,
        passthruEndX_val12_c_din => entry_proc_U0_passthruEndX_val12_c_din,
        passthruEndX_val12_c_num_data_valid => passthruEndX_val12_c_num_data_valid,
        passthruEndX_val12_c_fifo_cap => passthruEndX_val12_c_fifo_cap,
        passthruEndX_val12_c_full_n => passthruEndX_val12_c_full_n,
        passthruEndX_val12_c_write => entry_proc_U0_passthruEndX_val12_c_write,
        passthruEndY_val13 => passthruEndY_val13,
        passthruEndY_val13_c_din => entry_proc_U0_passthruEndY_val13_c_din,
        passthruEndY_val13_c_num_data_valid => passthruEndY_val13_c_num_data_valid,
        passthruEndY_val13_c_fifo_cap => passthruEndY_val13_c_fifo_cap,
        passthruEndY_val13_c_full_n => passthruEndY_val13_c_full_n,
        passthruEndY_val13_c_write => entry_proc_U0_passthruEndY_val13_c_write,
        bckgndId_val16 => bckgndId_val16,
        bckgndId_val16_c_din => entry_proc_U0_bckgndId_val16_c_din,
        bckgndId_val16_c_num_data_valid => bckgndId_val16_c_num_data_valid,
        bckgndId_val16_c_fifo_cap => bckgndId_val16_c_fifo_cap,
        bckgndId_val16_c_full_n => bckgndId_val16_c_full_n,
        bckgndId_val16_c_write => entry_proc_U0_bckgndId_val16_c_write,
        motionSpeed_val17 => motionSpeed_val17,
        motionSpeed_val17_c_din => entry_proc_U0_motionSpeed_val17_c_din,
        motionSpeed_val17_c_num_data_valid => motionSpeed_val17_c_num_data_valid,
        motionSpeed_val17_c_fifo_cap => motionSpeed_val17_c_fifo_cap,
        motionSpeed_val17_c_full_n => motionSpeed_val17_c_full_n,
        motionSpeed_val17_c_write => entry_proc_U0_motionSpeed_val17_c_write,
        ZplateHorContStart_val21 => ZplateHorContStart_val21,
        ZplateHorContStart_val21_c_din => entry_proc_U0_ZplateHorContStart_val21_c_din,
        ZplateHorContStart_val21_c_num_data_valid => ZplateHorContStart_val21_c_num_data_valid,
        ZplateHorContStart_val21_c_fifo_cap => ZplateHorContStart_val21_c_fifo_cap,
        ZplateHorContStart_val21_c_full_n => ZplateHorContStart_val21_c_full_n,
        ZplateHorContStart_val21_c_write => entry_proc_U0_ZplateHorContStart_val21_c_write,
        ZplateHorContDelta_val22 => ZplateHorContDelta_val22,
        ZplateHorContDelta_val22_c_din => entry_proc_U0_ZplateHorContDelta_val22_c_din,
        ZplateHorContDelta_val22_c_num_data_valid => ZplateHorContDelta_val22_c_num_data_valid,
        ZplateHorContDelta_val22_c_fifo_cap => ZplateHorContDelta_val22_c_fifo_cap,
        ZplateHorContDelta_val22_c_full_n => ZplateHorContDelta_val22_c_full_n,
        ZplateHorContDelta_val22_c_write => entry_proc_U0_ZplateHorContDelta_val22_c_write,
        ZplateVerContStart_val23 => ZplateVerContStart_val23,
        ZplateVerContStart_val23_c_din => entry_proc_U0_ZplateVerContStart_val23_c_din,
        ZplateVerContStart_val23_c_num_data_valid => ZplateVerContStart_val23_c_num_data_valid,
        ZplateVerContStart_val23_c_fifo_cap => ZplateVerContStart_val23_c_fifo_cap,
        ZplateVerContStart_val23_c_full_n => ZplateVerContStart_val23_c_full_n,
        ZplateVerContStart_val23_c_write => entry_proc_U0_ZplateVerContStart_val23_c_write,
        ZplateVerContDelta_val24 => ZplateVerContDelta_val24,
        ZplateVerContDelta_val24_c_din => entry_proc_U0_ZplateVerContDelta_val24_c_din,
        ZplateVerContDelta_val24_c_num_data_valid => ZplateVerContDelta_val24_c_num_data_valid,
        ZplateVerContDelta_val24_c_fifo_cap => ZplateVerContDelta_val24_c_fifo_cap,
        ZplateVerContDelta_val24_c_full_n => ZplateVerContDelta_val24_c_full_n,
        ZplateVerContDelta_val24_c_write => entry_proc_U0_ZplateVerContDelta_val24_c_write,
        dpDynamicRange_val25 => dpDynamicRange_val25,
        dpDynamicRange_val25_c_din => entry_proc_U0_dpDynamicRange_val25_c_din,
        dpDynamicRange_val25_c_num_data_valid => dpDynamicRange_val25_c_num_data_valid,
        dpDynamicRange_val25_c_fifo_cap => dpDynamicRange_val25_c_fifo_cap,
        dpDynamicRange_val25_c_full_n => dpDynamicRange_val25_c_full_n,
        dpDynamicRange_val25_c_write => entry_proc_U0_dpDynamicRange_val25_c_write,
        dpYUVCoef_val26 => dpYUVCoef_val26,
        dpYUVCoef_val26_c_din => entry_proc_U0_dpYUVCoef_val26_c_din,
        dpYUVCoef_val26_c_num_data_valid => dpYUVCoef_val26_c_num_data_valid,
        dpYUVCoef_val26_c_fifo_cap => dpYUVCoef_val26_c_fifo_cap,
        dpYUVCoef_val26_c_full_n => dpYUVCoef_val26_c_full_n,
        dpYUVCoef_val26_c_write => entry_proc_U0_dpYUVCoef_val26_c_write);

    AXIvideo2MultiPixStream_U0 : component design_1_v_tpg_0_0_AXIvideo2MultiPixStream
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => AXIvideo2MultiPixStream_U0_ap_start,
        ap_done => AXIvideo2MultiPixStream_U0_ap_done,
        ap_continue => AXIvideo2MultiPixStream_U0_ap_continue,
        ap_idle => AXIvideo2MultiPixStream_U0_ap_idle,
        ap_ready => AXIvideo2MultiPixStream_U0_ap_ready,
        s_axis_video_TDATA => s_axis_video_TDATA,
        s_axis_video_TVALID => s_axis_video_TVALID,
        s_axis_video_TREADY => AXIvideo2MultiPixStream_U0_s_axis_video_TREADY,
        s_axis_video_TKEEP => s_axis_video_TKEEP,
        s_axis_video_TSTRB => s_axis_video_TSTRB,
        s_axis_video_TUSER => s_axis_video_TUSER,
        s_axis_video_TLAST => s_axis_video_TLAST,
        s_axis_video_TID => s_axis_video_TID,
        s_axis_video_TDEST => s_axis_video_TDEST,
        srcYUV_din => AXIvideo2MultiPixStream_U0_srcYUV_din,
        srcYUV_num_data_valid => srcYUV_num_data_valid,
        srcYUV_fifo_cap => srcYUV_fifo_cap,
        srcYUV_full_n => srcYUV_full_n,
        srcYUV_write => AXIvideo2MultiPixStream_U0_srcYUV_write,
        enableInput_val => enableInput_val15,
        Height_val => height_val4,
        WidthIn_val => width_val7,
        colorFormat_val => colorFormat_val20,
        height_val4_c3_din => AXIvideo2MultiPixStream_U0_height_val4_c3_din,
        height_val4_c3_num_data_valid => height_val4_c3_num_data_valid,
        height_val4_c3_fifo_cap => height_val4_c3_fifo_cap,
        height_val4_c3_full_n => height_val4_c3_full_n,
        height_val4_c3_write => AXIvideo2MultiPixStream_U0_height_val4_c3_write,
        width_val7_c4_din => AXIvideo2MultiPixStream_U0_width_val7_c4_din,
        width_val7_c4_num_data_valid => width_val7_c4_num_data_valid,
        width_val7_c4_fifo_cap => width_val7_c4_fifo_cap,
        width_val7_c4_full_n => width_val7_c4_full_n,
        width_val7_c4_write => AXIvideo2MultiPixStream_U0_width_val7_c4_write,
        enableInput_val15_c_din => AXIvideo2MultiPixStream_U0_enableInput_val15_c_din,
        enableInput_val15_c_num_data_valid => enableInput_val15_c_num_data_valid,
        enableInput_val15_c_fifo_cap => enableInput_val15_c_fifo_cap,
        enableInput_val15_c_full_n => enableInput_val15_c_full_n,
        enableInput_val15_c_write => AXIvideo2MultiPixStream_U0_enableInput_val15_c_write,
        colorFormat_val20_c5_din => AXIvideo2MultiPixStream_U0_colorFormat_val20_c5_din,
        colorFormat_val20_c5_num_data_valid => colorFormat_val20_c5_num_data_valid,
        colorFormat_val20_c5_fifo_cap => colorFormat_val20_c5_fifo_cap,
        colorFormat_val20_c5_full_n => colorFormat_val20_c5_full_n,
        colorFormat_val20_c5_write => AXIvideo2MultiPixStream_U0_colorFormat_val20_c5_write);

    tpgBackground_U0 : component design_1_v_tpg_0_0_tpgBackground
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => tpgBackground_U0_ap_start,
        ap_done => tpgBackground_U0_ap_done,
        ap_continue => tpgBackground_U0_ap_continue,
        ap_idle => tpgBackground_U0_ap_idle,
        ap_ready => tpgBackground_U0_ap_ready,
        srcYUV_dout => srcYUV_dout,
        srcYUV_num_data_valid => srcYUV_num_data_valid,
        srcYUV_fifo_cap => srcYUV_fifo_cap,
        srcYUV_empty_n => srcYUV_empty_n,
        srcYUV_read => tpgBackground_U0_srcYUV_read,
        height_val_dout => height_val4_c3_dout,
        height_val_num_data_valid => height_val4_c3_num_data_valid,
        height_val_fifo_cap => height_val4_c3_fifo_cap,
        height_val_empty_n => height_val4_c3_empty_n,
        height_val_read => tpgBackground_U0_height_val_read,
        width_val_dout => width_val7_c4_dout,
        width_val_num_data_valid => width_val7_c4_num_data_valid,
        width_val_fifo_cap => width_val7_c4_fifo_cap,
        width_val_empty_n => width_val7_c4_empty_n,
        width_val_read => tpgBackground_U0_width_val_read,
        passthruStartX_val_dout => passthruStartX_val10_c_dout,
        passthruStartX_val_num_data_valid => passthruStartX_val10_c_num_data_valid,
        passthruStartX_val_fifo_cap => passthruStartX_val10_c_fifo_cap,
        passthruStartX_val_empty_n => passthruStartX_val10_c_empty_n,
        passthruStartX_val_read => tpgBackground_U0_passthruStartX_val_read,
        passthruStartY_val_dout => passthruStartY_val11_c_dout,
        passthruStartY_val_num_data_valid => passthruStartY_val11_c_num_data_valid,
        passthruStartY_val_fifo_cap => passthruStartY_val11_c_fifo_cap,
        passthruStartY_val_empty_n => passthruStartY_val11_c_empty_n,
        passthruStartY_val_read => tpgBackground_U0_passthruStartY_val_read,
        passthruEndX_val_dout => passthruEndX_val12_c_dout,
        passthruEndX_val_num_data_valid => passthruEndX_val12_c_num_data_valid,
        passthruEndX_val_fifo_cap => passthruEndX_val12_c_fifo_cap,
        passthruEndX_val_empty_n => passthruEndX_val12_c_empty_n,
        passthruEndX_val_read => tpgBackground_U0_passthruEndX_val_read,
        passthruEndY_val_dout => passthruEndY_val13_c_dout,
        passthruEndY_val_num_data_valid => passthruEndY_val13_c_num_data_valid,
        passthruEndY_val_fifo_cap => passthruEndY_val13_c_fifo_cap,
        passthruEndY_val_empty_n => passthruEndY_val13_c_empty_n,
        passthruEndY_val_read => tpgBackground_U0_passthruEndY_val_read,
        enableInput_val_dout => enableInput_val15_c_dout,
        enableInput_val_num_data_valid => enableInput_val15_c_num_data_valid,
        enableInput_val_fifo_cap => enableInput_val15_c_fifo_cap,
        enableInput_val_empty_n => enableInput_val15_c_empty_n,
        enableInput_val_read => tpgBackground_U0_enableInput_val_read,
        patternId_val_dout => bckgndId_val16_c_dout,
        patternId_val_num_data_valid => bckgndId_val16_c_num_data_valid,
        patternId_val_fifo_cap => bckgndId_val16_c_fifo_cap,
        patternId_val_empty_n => bckgndId_val16_c_empty_n,
        patternId_val_read => tpgBackground_U0_patternId_val_read,
        ZplateHorContStart_val_dout => ZplateHorContStart_val21_c_dout,
        ZplateHorContStart_val_num_data_valid => ZplateHorContStart_val21_c_num_data_valid,
        ZplateHorContStart_val_fifo_cap => ZplateHorContStart_val21_c_fifo_cap,
        ZplateHorContStart_val_empty_n => ZplateHorContStart_val21_c_empty_n,
        ZplateHorContStart_val_read => tpgBackground_U0_ZplateHorContStart_val_read,
        ZplateHorContDelta_val_dout => ZplateHorContDelta_val22_c_dout,
        ZplateHorContDelta_val_num_data_valid => ZplateHorContDelta_val22_c_num_data_valid,
        ZplateHorContDelta_val_fifo_cap => ZplateHorContDelta_val22_c_fifo_cap,
        ZplateHorContDelta_val_empty_n => ZplateHorContDelta_val22_c_empty_n,
        ZplateHorContDelta_val_read => tpgBackground_U0_ZplateHorContDelta_val_read,
        ZplateVerContStart_val_dout => ZplateVerContStart_val23_c_dout,
        ZplateVerContStart_val_num_data_valid => ZplateVerContStart_val23_c_num_data_valid,
        ZplateVerContStart_val_fifo_cap => ZplateVerContStart_val23_c_fifo_cap,
        ZplateVerContStart_val_empty_n => ZplateVerContStart_val23_c_empty_n,
        ZplateVerContStart_val_read => tpgBackground_U0_ZplateVerContStart_val_read,
        ZplateVerContDelta_val_dout => ZplateVerContDelta_val24_c_dout,
        ZplateVerContDelta_val_num_data_valid => ZplateVerContDelta_val24_c_num_data_valid,
        ZplateVerContDelta_val_fifo_cap => ZplateVerContDelta_val24_c_fifo_cap,
        ZplateVerContDelta_val_empty_n => ZplateVerContDelta_val24_c_empty_n,
        ZplateVerContDelta_val_read => tpgBackground_U0_ZplateVerContDelta_val_read,
        dpDynamicRange_val_dout => dpDynamicRange_val25_c_dout,
        dpDynamicRange_val_num_data_valid => dpDynamicRange_val25_c_num_data_valid,
        dpDynamicRange_val_fifo_cap => dpDynamicRange_val25_c_fifo_cap,
        dpDynamicRange_val_empty_n => dpDynamicRange_val25_c_empty_n,
        dpDynamicRange_val_read => tpgBackground_U0_dpDynamicRange_val_read,
        dpYUVCoef_val_dout => dpYUVCoef_val26_c_dout,
        dpYUVCoef_val_num_data_valid => dpYUVCoef_val26_c_num_data_valid,
        dpYUVCoef_val_fifo_cap => dpYUVCoef_val26_c_fifo_cap,
        dpYUVCoef_val_empty_n => dpYUVCoef_val26_c_empty_n,
        dpYUVCoef_val_read => tpgBackground_U0_dpYUVCoef_val_read,
        motionSpeed_val_dout => motionSpeed_val17_c_dout,
        motionSpeed_val_num_data_valid => motionSpeed_val17_c_num_data_valid,
        motionSpeed_val_fifo_cap => motionSpeed_val17_c_fifo_cap,
        motionSpeed_val_empty_n => motionSpeed_val17_c_empty_n,
        motionSpeed_val_read => tpgBackground_U0_motionSpeed_val_read,
        colorFormat_val_dout => colorFormat_val20_c5_dout,
        colorFormat_val_num_data_valid => colorFormat_val20_c5_num_data_valid,
        colorFormat_val_fifo_cap => colorFormat_val20_c5_fifo_cap,
        colorFormat_val_empty_n => colorFormat_val20_c5_empty_n,
        colorFormat_val_read => tpgBackground_U0_colorFormat_val_read,
        ovrlayYUV_din => tpgBackground_U0_ovrlayYUV_din,
        ovrlayYUV_num_data_valid => ovrlayYUV_num_data_valid,
        ovrlayYUV_fifo_cap => ovrlayYUV_fifo_cap,
        ovrlayYUV_full_n => ovrlayYUV_full_n,
        ovrlayYUV_write => tpgBackground_U0_ovrlayYUV_write,
        height_val4_c_din => tpgBackground_U0_height_val4_c_din,
        height_val4_c_num_data_valid => height_val4_c_num_data_valid,
        height_val4_c_fifo_cap => height_val4_c_fifo_cap,
        height_val4_c_full_n => height_val4_c_full_n,
        height_val4_c_write => tpgBackground_U0_height_val4_c_write,
        width_val7_c_din => tpgBackground_U0_width_val7_c_din,
        width_val7_c_num_data_valid => width_val7_c_num_data_valid,
        width_val7_c_fifo_cap => width_val7_c_fifo_cap,
        width_val7_c_full_n => width_val7_c_full_n,
        width_val7_c_write => tpgBackground_U0_width_val7_c_write,
        colorFormat_val20_c_din => tpgBackground_U0_colorFormat_val20_c_din,
        colorFormat_val20_c_num_data_valid => colorFormat_val20_c_num_data_valid,
        colorFormat_val20_c_fifo_cap => colorFormat_val20_c_fifo_cap,
        colorFormat_val20_c_full_n => colorFormat_val20_c_full_n,
        colorFormat_val20_c_write => tpgBackground_U0_colorFormat_val20_c_write,
        s => s);

    MultiPixStream2AXIvideo_U0 : component design_1_v_tpg_0_0_MultiPixStream2AXIvideo
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => MultiPixStream2AXIvideo_U0_ap_start,
        ap_done => MultiPixStream2AXIvideo_U0_ap_done,
        ap_continue => MultiPixStream2AXIvideo_U0_ap_continue,
        ap_idle => MultiPixStream2AXIvideo_U0_ap_idle,
        ap_ready => MultiPixStream2AXIvideo_U0_ap_ready,
        ovrlayYUV_dout => ovrlayYUV_dout,
        ovrlayYUV_num_data_valid => ovrlayYUV_num_data_valid,
        ovrlayYUV_fifo_cap => ovrlayYUV_fifo_cap,
        ovrlayYUV_empty_n => ovrlayYUV_empty_n,
        ovrlayYUV_read => MultiPixStream2AXIvideo_U0_ovrlayYUV_read,
        m_axis_video_TDATA => MultiPixStream2AXIvideo_U0_m_axis_video_TDATA,
        m_axis_video_TVALID => MultiPixStream2AXIvideo_U0_m_axis_video_TVALID,
        m_axis_video_TREADY => m_axis_video_TREADY,
        m_axis_video_TKEEP => MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP,
        m_axis_video_TSTRB => MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB,
        m_axis_video_TUSER => MultiPixStream2AXIvideo_U0_m_axis_video_TUSER,
        m_axis_video_TLAST => MultiPixStream2AXIvideo_U0_m_axis_video_TLAST,
        m_axis_video_TID => MultiPixStream2AXIvideo_U0_m_axis_video_TID,
        m_axis_video_TDEST => MultiPixStream2AXIvideo_U0_m_axis_video_TDEST,
        height_val4_dout => height_val4_c_dout,
        height_val4_num_data_valid => height_val4_c_num_data_valid,
        height_val4_fifo_cap => height_val4_c_fifo_cap,
        height_val4_empty_n => height_val4_c_empty_n,
        height_val4_read => MultiPixStream2AXIvideo_U0_height_val4_read,
        width_val7_dout => width_val7_c_dout,
        width_val7_num_data_valid => width_val7_c_num_data_valid,
        width_val7_fifo_cap => width_val7_c_fifo_cap,
        width_val7_empty_n => width_val7_c_empty_n,
        width_val7_read => MultiPixStream2AXIvideo_U0_width_val7_read,
        colorFormat_val20_dout => colorFormat_val20_c_dout,
        colorFormat_val20_num_data_valid => colorFormat_val20_c_num_data_valid,
        colorFormat_val20_fifo_cap => colorFormat_val20_c_fifo_cap,
        colorFormat_val20_empty_n => colorFormat_val20_c_empty_n,
        colorFormat_val20_read => MultiPixStream2AXIvideo_U0_colorFormat_val20_read,
        fid_in_val9_dout => fid_in_val9_c_dout,
        fid_in_val9_num_data_valid => fid_in_val9_c_num_data_valid,
        fid_in_val9_fifo_cap => fid_in_val9_c_fifo_cap,
        fid_in_val9_empty_n => fid_in_val9_c_empty_n,
        fid_in_val9_read => MultiPixStream2AXIvideo_U0_fid_in_val9_read,
        fid => MultiPixStream2AXIvideo_U0_fid,
        fid_ap_vld => MultiPixStream2AXIvideo_U0_fid_ap_vld,
        field_id_val8_dout => field_id_val8_c_dout,
        field_id_val8_num_data_valid => field_id_val8_c_num_data_valid,
        field_id_val8_fifo_cap => field_id_val8_c_fifo_cap,
        field_id_val8_empty_n => field_id_val8_c_empty_n,
        field_id_val8_read => MultiPixStream2AXIvideo_U0_field_id_val8_read);

    field_id_val8_c_U : component design_1_v_tpg_0_0_fifo_w16_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_field_id_val8_c_din,
        if_full_n => field_id_val8_c_full_n,
        if_write => entry_proc_U0_field_id_val8_c_write,
        if_dout => field_id_val8_c_dout,
        if_num_data_valid => field_id_val8_c_num_data_valid,
        if_fifo_cap => field_id_val8_c_fifo_cap,
        if_empty_n => field_id_val8_c_empty_n,
        if_read => MultiPixStream2AXIvideo_U0_field_id_val8_read);

    fid_in_val9_c_U : component design_1_v_tpg_0_0_fifo_w1_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_fid_in_val9_c_din,
        if_full_n => fid_in_val9_c_full_n,
        if_write => entry_proc_U0_fid_in_val9_c_write,
        if_dout => fid_in_val9_c_dout,
        if_num_data_valid => fid_in_val9_c_num_data_valid,
        if_fifo_cap => fid_in_val9_c_fifo_cap,
        if_empty_n => fid_in_val9_c_empty_n,
        if_read => MultiPixStream2AXIvideo_U0_fid_in_val9_read);

    passthruStartX_val10_c_U : component design_1_v_tpg_0_0_fifo_w16_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_passthruStartX_val10_c_din,
        if_full_n => passthruStartX_val10_c_full_n,
        if_write => entry_proc_U0_passthruStartX_val10_c_write,
        if_dout => passthruStartX_val10_c_dout,
        if_num_data_valid => passthruStartX_val10_c_num_data_valid,
        if_fifo_cap => passthruStartX_val10_c_fifo_cap,
        if_empty_n => passthruStartX_val10_c_empty_n,
        if_read => tpgBackground_U0_passthruStartX_val_read);

    passthruStartY_val11_c_U : component design_1_v_tpg_0_0_fifo_w16_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_passthruStartY_val11_c_din,
        if_full_n => passthruStartY_val11_c_full_n,
        if_write => entry_proc_U0_passthruStartY_val11_c_write,
        if_dout => passthruStartY_val11_c_dout,
        if_num_data_valid => passthruStartY_val11_c_num_data_valid,
        if_fifo_cap => passthruStartY_val11_c_fifo_cap,
        if_empty_n => passthruStartY_val11_c_empty_n,
        if_read => tpgBackground_U0_passthruStartY_val_read);

    passthruEndX_val12_c_U : component design_1_v_tpg_0_0_fifo_w16_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_passthruEndX_val12_c_din,
        if_full_n => passthruEndX_val12_c_full_n,
        if_write => entry_proc_U0_passthruEndX_val12_c_write,
        if_dout => passthruEndX_val12_c_dout,
        if_num_data_valid => passthruEndX_val12_c_num_data_valid,
        if_fifo_cap => passthruEndX_val12_c_fifo_cap,
        if_empty_n => passthruEndX_val12_c_empty_n,
        if_read => tpgBackground_U0_passthruEndX_val_read);

    passthruEndY_val13_c_U : component design_1_v_tpg_0_0_fifo_w16_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_passthruEndY_val13_c_din,
        if_full_n => passthruEndY_val13_c_full_n,
        if_write => entry_proc_U0_passthruEndY_val13_c_write,
        if_dout => passthruEndY_val13_c_dout,
        if_num_data_valid => passthruEndY_val13_c_num_data_valid,
        if_fifo_cap => passthruEndY_val13_c_fifo_cap,
        if_empty_n => passthruEndY_val13_c_empty_n,
        if_read => tpgBackground_U0_passthruEndY_val_read);

    bckgndId_val16_c_U : component design_1_v_tpg_0_0_fifo_w8_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_bckgndId_val16_c_din,
        if_full_n => bckgndId_val16_c_full_n,
        if_write => entry_proc_U0_bckgndId_val16_c_write,
        if_dout => bckgndId_val16_c_dout,
        if_num_data_valid => bckgndId_val16_c_num_data_valid,
        if_fifo_cap => bckgndId_val16_c_fifo_cap,
        if_empty_n => bckgndId_val16_c_empty_n,
        if_read => tpgBackground_U0_patternId_val_read);

    motionSpeed_val17_c_U : component design_1_v_tpg_0_0_fifo_w8_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_motionSpeed_val17_c_din,
        if_full_n => motionSpeed_val17_c_full_n,
        if_write => entry_proc_U0_motionSpeed_val17_c_write,
        if_dout => motionSpeed_val17_c_dout,
        if_num_data_valid => motionSpeed_val17_c_num_data_valid,
        if_fifo_cap => motionSpeed_val17_c_fifo_cap,
        if_empty_n => motionSpeed_val17_c_empty_n,
        if_read => tpgBackground_U0_motionSpeed_val_read);

    ZplateHorContStart_val21_c_U : component design_1_v_tpg_0_0_fifo_w16_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_ZplateHorContStart_val21_c_din,
        if_full_n => ZplateHorContStart_val21_c_full_n,
        if_write => entry_proc_U0_ZplateHorContStart_val21_c_write,
        if_dout => ZplateHorContStart_val21_c_dout,
        if_num_data_valid => ZplateHorContStart_val21_c_num_data_valid,
        if_fifo_cap => ZplateHorContStart_val21_c_fifo_cap,
        if_empty_n => ZplateHorContStart_val21_c_empty_n,
        if_read => tpgBackground_U0_ZplateHorContStart_val_read);

    ZplateHorContDelta_val22_c_U : component design_1_v_tpg_0_0_fifo_w16_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_ZplateHorContDelta_val22_c_din,
        if_full_n => ZplateHorContDelta_val22_c_full_n,
        if_write => entry_proc_U0_ZplateHorContDelta_val22_c_write,
        if_dout => ZplateHorContDelta_val22_c_dout,
        if_num_data_valid => ZplateHorContDelta_val22_c_num_data_valid,
        if_fifo_cap => ZplateHorContDelta_val22_c_fifo_cap,
        if_empty_n => ZplateHorContDelta_val22_c_empty_n,
        if_read => tpgBackground_U0_ZplateHorContDelta_val_read);

    ZplateVerContStart_val23_c_U : component design_1_v_tpg_0_0_fifo_w16_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_ZplateVerContStart_val23_c_din,
        if_full_n => ZplateVerContStart_val23_c_full_n,
        if_write => entry_proc_U0_ZplateVerContStart_val23_c_write,
        if_dout => ZplateVerContStart_val23_c_dout,
        if_num_data_valid => ZplateVerContStart_val23_c_num_data_valid,
        if_fifo_cap => ZplateVerContStart_val23_c_fifo_cap,
        if_empty_n => ZplateVerContStart_val23_c_empty_n,
        if_read => tpgBackground_U0_ZplateVerContStart_val_read);

    ZplateVerContDelta_val24_c_U : component design_1_v_tpg_0_0_fifo_w16_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_ZplateVerContDelta_val24_c_din,
        if_full_n => ZplateVerContDelta_val24_c_full_n,
        if_write => entry_proc_U0_ZplateVerContDelta_val24_c_write,
        if_dout => ZplateVerContDelta_val24_c_dout,
        if_num_data_valid => ZplateVerContDelta_val24_c_num_data_valid,
        if_fifo_cap => ZplateVerContDelta_val24_c_fifo_cap,
        if_empty_n => ZplateVerContDelta_val24_c_empty_n,
        if_read => tpgBackground_U0_ZplateVerContDelta_val_read);

    dpDynamicRange_val25_c_U : component design_1_v_tpg_0_0_fifo_w8_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_dpDynamicRange_val25_c_din,
        if_full_n => dpDynamicRange_val25_c_full_n,
        if_write => entry_proc_U0_dpDynamicRange_val25_c_write,
        if_dout => dpDynamicRange_val25_c_dout,
        if_num_data_valid => dpDynamicRange_val25_c_num_data_valid,
        if_fifo_cap => dpDynamicRange_val25_c_fifo_cap,
        if_empty_n => dpDynamicRange_val25_c_empty_n,
        if_read => tpgBackground_U0_dpDynamicRange_val_read);

    dpYUVCoef_val26_c_U : component design_1_v_tpg_0_0_fifo_w8_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_dpYUVCoef_val26_c_din,
        if_full_n => dpYUVCoef_val26_c_full_n,
        if_write => entry_proc_U0_dpYUVCoef_val26_c_write,
        if_dout => dpYUVCoef_val26_c_dout,
        if_num_data_valid => dpYUVCoef_val26_c_num_data_valid,
        if_fifo_cap => dpYUVCoef_val26_c_fifo_cap,
        if_empty_n => dpYUVCoef_val26_c_empty_n,
        if_read => tpgBackground_U0_dpYUVCoef_val_read);

    srcYUV_U : component design_1_v_tpg_0_0_fifo_w30_d16_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2MultiPixStream_U0_srcYUV_din,
        if_full_n => srcYUV_full_n,
        if_write => AXIvideo2MultiPixStream_U0_srcYUV_write,
        if_dout => srcYUV_dout,
        if_num_data_valid => srcYUV_num_data_valid,
        if_fifo_cap => srcYUV_fifo_cap,
        if_empty_n => srcYUV_empty_n,
        if_read => tpgBackground_U0_srcYUV_read);

    height_val4_c3_U : component design_1_v_tpg_0_0_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2MultiPixStream_U0_height_val4_c3_din,
        if_full_n => height_val4_c3_full_n,
        if_write => AXIvideo2MultiPixStream_U0_height_val4_c3_write,
        if_dout => height_val4_c3_dout,
        if_num_data_valid => height_val4_c3_num_data_valid,
        if_fifo_cap => height_val4_c3_fifo_cap,
        if_empty_n => height_val4_c3_empty_n,
        if_read => tpgBackground_U0_height_val_read);

    width_val7_c4_U : component design_1_v_tpg_0_0_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2MultiPixStream_U0_width_val7_c4_din,
        if_full_n => width_val7_c4_full_n,
        if_write => AXIvideo2MultiPixStream_U0_width_val7_c4_write,
        if_dout => width_val7_c4_dout,
        if_num_data_valid => width_val7_c4_num_data_valid,
        if_fifo_cap => width_val7_c4_fifo_cap,
        if_empty_n => width_val7_c4_empty_n,
        if_read => tpgBackground_U0_width_val_read);

    enableInput_val15_c_U : component design_1_v_tpg_0_0_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2MultiPixStream_U0_enableInput_val15_c_din,
        if_full_n => enableInput_val15_c_full_n,
        if_write => AXIvideo2MultiPixStream_U0_enableInput_val15_c_write,
        if_dout => enableInput_val15_c_dout,
        if_num_data_valid => enableInput_val15_c_num_data_valid,
        if_fifo_cap => enableInput_val15_c_fifo_cap,
        if_empty_n => enableInput_val15_c_empty_n,
        if_read => tpgBackground_U0_enableInput_val_read);

    colorFormat_val20_c5_U : component design_1_v_tpg_0_0_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2MultiPixStream_U0_colorFormat_val20_c5_din,
        if_full_n => colorFormat_val20_c5_full_n,
        if_write => AXIvideo2MultiPixStream_U0_colorFormat_val20_c5_write,
        if_dout => colorFormat_val20_c5_dout,
        if_num_data_valid => colorFormat_val20_c5_num_data_valid,
        if_fifo_cap => colorFormat_val20_c5_fifo_cap,
        if_empty_n => colorFormat_val20_c5_empty_n,
        if_read => tpgBackground_U0_colorFormat_val_read);

    ovrlayYUV_U : component design_1_v_tpg_0_0_fifo_w30_d16_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => tpgBackground_U0_ovrlayYUV_din,
        if_full_n => ovrlayYUV_full_n,
        if_write => tpgBackground_U0_ovrlayYUV_write,
        if_dout => ovrlayYUV_dout,
        if_num_data_valid => ovrlayYUV_num_data_valid,
        if_fifo_cap => ovrlayYUV_fifo_cap,
        if_empty_n => ovrlayYUV_empty_n,
        if_read => MultiPixStream2AXIvideo_U0_ovrlayYUV_read);

    height_val4_c_U : component design_1_v_tpg_0_0_fifo_w11_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => tpgBackground_U0_height_val4_c_din,
        if_full_n => height_val4_c_full_n,
        if_write => tpgBackground_U0_height_val4_c_write,
        if_dout => height_val4_c_dout,
        if_num_data_valid => height_val4_c_num_data_valid,
        if_fifo_cap => height_val4_c_fifo_cap,
        if_empty_n => height_val4_c_empty_n,
        if_read => MultiPixStream2AXIvideo_U0_height_val4_read);

    width_val7_c_U : component design_1_v_tpg_0_0_fifo_w11_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => tpgBackground_U0_width_val7_c_din,
        if_full_n => width_val7_c_full_n,
        if_write => tpgBackground_U0_width_val7_c_write,
        if_dout => width_val7_c_dout,
        if_num_data_valid => width_val7_c_num_data_valid,
        if_fifo_cap => width_val7_c_fifo_cap,
        if_empty_n => width_val7_c_empty_n,
        if_read => MultiPixStream2AXIvideo_U0_width_val7_read);

    colorFormat_val20_c_U : component design_1_v_tpg_0_0_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => tpgBackground_U0_colorFormat_val20_c_din,
        if_full_n => colorFormat_val20_c_full_n,
        if_write => tpgBackground_U0_colorFormat_val20_c_write,
        if_dout => colorFormat_val20_c_dout,
        if_num_data_valid => colorFormat_val20_c_num_data_valid,
        if_fifo_cap => colorFormat_val20_c_fifo_cap,
        if_empty_n => colorFormat_val20_c_empty_n,
        if_read => MultiPixStream2AXIvideo_U0_colorFormat_val20_read);

    start_for_MultiPixStream2AXIvideo_U0_U : component design_1_v_tpg_0_0_start_for_MultiPixStream2AXIvideo_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_MultiPixStream2AXIvideo_U0_din,
        if_full_n => start_for_MultiPixStream2AXIvideo_U0_full_n,
        if_write => entry_proc_U0_start_write,
        if_dout => start_for_MultiPixStream2AXIvideo_U0_dout,
        if_empty_n => start_for_MultiPixStream2AXIvideo_U0_empty_n,
        if_read => MultiPixStream2AXIvideo_U0_ap_ready);





    ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready <= ap_sync_AXIvideo2MultiPixStream_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_entry_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_tpgBackground_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_tpgBackground_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_tpgBackground_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_tpgBackground_U0_ap_ready <= ap_sync_tpgBackground_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    AXIvideo2MultiPixStream_U0_ap_continue <= ap_const_logic_1;
    AXIvideo2MultiPixStream_U0_ap_start <= ((ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready xor ap_const_logic_1) and ap_start);
    MultiPixStream2AXIvideo_U0_ap_continue <= ap_continue;
    MultiPixStream2AXIvideo_U0_ap_start <= start_for_MultiPixStream2AXIvideo_U0_empty_n;
    ap_done <= MultiPixStream2AXIvideo_U0_ap_done;
    ap_idle <= (tpgBackground_U0_ap_idle and entry_proc_U0_ap_idle and MultiPixStream2AXIvideo_U0_ap_idle and AXIvideo2MultiPixStream_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_AXIvideo2MultiPixStream_U0_ap_ready <= (ap_sync_reg_AXIvideo2MultiPixStream_U0_ap_ready or AXIvideo2MultiPixStream_U0_ap_ready);
    ap_sync_entry_proc_U0_ap_ready <= (entry_proc_U0_ap_ready or ap_sync_reg_entry_proc_U0_ap_ready);
    ap_sync_ready <= (ap_sync_tpgBackground_U0_ap_ready and ap_sync_entry_proc_U0_ap_ready and ap_sync_AXIvideo2MultiPixStream_U0_ap_ready);
    ap_sync_tpgBackground_U0_ap_ready <= (tpgBackground_U0_ap_ready or ap_sync_reg_tpgBackground_U0_ap_ready);
    entry_proc_U0_ap_continue <= ap_const_logic_1;
    entry_proc_U0_ap_start <= ((ap_sync_reg_entry_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    fid <= MultiPixStream2AXIvideo_U0_fid;
    fid_ap_vld <= MultiPixStream2AXIvideo_U0_fid_ap_vld;
    m_axis_video_TDATA <= MultiPixStream2AXIvideo_U0_m_axis_video_TDATA;
    m_axis_video_TDEST <= MultiPixStream2AXIvideo_U0_m_axis_video_TDEST;
    m_axis_video_TID <= MultiPixStream2AXIvideo_U0_m_axis_video_TID;
    m_axis_video_TKEEP <= MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP;
    m_axis_video_TLAST <= MultiPixStream2AXIvideo_U0_m_axis_video_TLAST;
    m_axis_video_TSTRB <= MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB;
    m_axis_video_TUSER <= MultiPixStream2AXIvideo_U0_m_axis_video_TUSER;
    m_axis_video_TVALID <= MultiPixStream2AXIvideo_U0_m_axis_video_TVALID;
    s_axis_video_TREADY <= AXIvideo2MultiPixStream_U0_s_axis_video_TREADY;
    start_for_MultiPixStream2AXIvideo_U0_din <= (0=>ap_const_logic_1, others=>'-');
    tpgBackground_U0_ap_continue <= ap_const_logic_1;
    tpgBackground_U0_ap_start <= ((ap_sync_reg_tpgBackground_U0_ap_ready xor ap_const_logic_1) and ap_start);
end behav;
