// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        imgRB_dout,
        imgRB_num_data_valid,
        imgRB_fifo_cap,
        imgRB_empty_n,
        imgRB_read,
        imgRgb_din,
        imgRgb_num_data_valid,
        imgRgb_fifo_cap,
        imgRgb_full_n,
        imgRgb_write,
        p_0_0_01183_217801810_lcssa1846_i,
        p_0_0_01184_217781808_lcssa1844_i,
        p_0_0_01185_217761806_lcssa1842_i,
        p_0_2_0_0_011511803_lcssa1840_i,
        p_0_1_0_0_011501801_lcssa1838_i,
        p_0_0_0_0_011491799_lcssa1836_i,
        p_0_0_0116117861798_lcssa1834_i,
        p_0_0_0116217841796_lcssa1832_i,
        p_0_0_0116317821794_lcssa1830_i,
        p_0_2_0_0_011571710_lcssa1752_i,
        p_0_1_0_0_011561707_lcssa1750_i,
        p_0_0_0_0_011551704_lcssa1748_i,
        loopWidth_i,
        empty_52,
        xor_i,
        cmp203_i,
        empty,
        cmp59_i,
        p_0_0_01183_217801809_i_out,
        p_0_0_01183_217801809_i_out_ap_vld,
        p_0_0_01184_217781807_i_out,
        p_0_0_01184_217781807_i_out_ap_vld,
        p_0_0_01185_217761805_i_out,
        p_0_0_01185_217761805_i_out_ap_vld,
        right_2_i_out,
        right_2_i_out_ap_vld,
        right_1_i_out,
        right_1_i_out_ap_vld,
        right_i_out,
        right_i_out_ap_vld,
        p_0_0_0116117861797_i_out,
        p_0_0_0116117861797_i_out_ap_vld,
        p_0_0_0116217841795_i_out,
        p_0_0_0116217841795_i_out_ap_vld,
        p_0_0_0116317821793_i_out,
        p_0_0_0116317821793_i_out_ap_vld,
        p_0_2_0_0_011571712_i_out,
        p_0_2_0_0_011571712_i_out_ap_vld,
        p_0_1_0_0_011561709_i_out,
        p_0_1_0_0_011561709_i_out_ap_vld,
        p_0_0_0_0_011551706_i_out,
        p_0_0_0_0_011551706_i_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [29:0] imgRB_dout;
input  [2:0] imgRB_num_data_valid;
input  [2:0] imgRB_fifo_cap;
input   imgRB_empty_n;
output   imgRB_read;
output  [29:0] imgRgb_din;
input  [2:0] imgRgb_num_data_valid;
input  [2:0] imgRgb_fifo_cap;
input   imgRgb_full_n;
output   imgRgb_write;
input  [9:0] p_0_0_01183_217801810_lcssa1846_i;
input  [9:0] p_0_0_01184_217781808_lcssa1844_i;
input  [9:0] p_0_0_01185_217761806_lcssa1842_i;
input  [9:0] p_0_2_0_0_011511803_lcssa1840_i;
input  [9:0] p_0_1_0_0_011501801_lcssa1838_i;
input  [9:0] p_0_0_0_0_011491799_lcssa1836_i;
input  [9:0] p_0_0_0116117861798_lcssa1834_i;
input  [9:0] p_0_0_0116217841796_lcssa1832_i;
input  [9:0] p_0_0_0116317821794_lcssa1830_i;
input  [9:0] p_0_2_0_0_011571710_lcssa1752_i;
input  [9:0] p_0_1_0_0_011561707_lcssa1750_i;
input  [9:0] p_0_0_0_0_011551704_lcssa1748_i;
input  [10:0] loopWidth_i;
input  [0:0] empty_52;
input  [14:0] xor_i;
input  [0:0] cmp203_i;
input  [10:0] empty;
input  [0:0] cmp59_i;
output  [9:0] p_0_0_01183_217801809_i_out;
output   p_0_0_01183_217801809_i_out_ap_vld;
output  [9:0] p_0_0_01184_217781807_i_out;
output   p_0_0_01184_217781807_i_out_ap_vld;
output  [9:0] p_0_0_01185_217761805_i_out;
output   p_0_0_01185_217761805_i_out_ap_vld;
output  [9:0] right_2_i_out;
output   right_2_i_out_ap_vld;
output  [9:0] right_1_i_out;
output   right_1_i_out_ap_vld;
output  [9:0] right_i_out;
output   right_i_out_ap_vld;
output  [9:0] p_0_0_0116117861797_i_out;
output   p_0_0_0116117861797_i_out_ap_vld;
output  [9:0] p_0_0_0116217841795_i_out;
output   p_0_0_0116217841795_i_out_ap_vld;
output  [9:0] p_0_0_0116317821793_i_out;
output   p_0_0_0116317821793_i_out_ap_vld;
output  [9:0] p_0_2_0_0_011571712_i_out;
output   p_0_2_0_0_011571712_i_out_ap_vld;
output  [9:0] p_0_1_0_0_011561709_i_out;
output   p_0_1_0_0_011561709_i_out_ap_vld;
output  [9:0] p_0_0_0_0_011551706_i_out;
output   p_0_0_0_0_011551706_i_out_ap_vld;

reg ap_idle;
reg p_0_0_01183_217801809_i_out_ap_vld;
reg p_0_0_01184_217781807_i_out_ap_vld;
reg p_0_0_01185_217761805_i_out_ap_vld;
reg right_2_i_out_ap_vld;
reg right_1_i_out_ap_vld;
reg right_i_out_ap_vld;
reg p_0_0_0116117861797_i_out_ap_vld;
reg p_0_0_0116217841795_i_out_ap_vld;
reg p_0_0_0116317821793_i_out_ap_vld;
reg p_0_2_0_0_011571712_i_out_ap_vld;
reg p_0_1_0_0_011561709_i_out_ap_vld;
reg p_0_0_0_0_011551706_i_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln881_reg_1964;
reg   [0:0] icmp_ln891_reg_1968;
wire   [0:0] cmp59_i_read_reg_1953;
reg    ap_predicate_op101_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] and_ln1052_reg_2007;
reg   [0:0] and_ln1052_reg_2007_pp0_iter2_reg;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln881_fu_578_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    imgRB_blk_n;
wire    ap_block_pp0_stage0;
reg    imgRgb_blk_n;
reg   [9:0] pix_8_reg_399;
reg   [9:0] pix_8_reg_399_pp0_iter2_reg;
reg    ap_block_pp0_stage0_11001;
reg   [9:0] pix_7_reg_409;
reg   [9:0] pix_7_reg_409_pp0_iter2_reg;
reg   [9:0] pix_reg_419;
reg   [9:0] pix_reg_419_pp0_iter2_reg;
reg   [0:0] icmp_ln881_reg_1964_pp0_iter1_reg;
wire   [0:0] icmp_ln891_fu_600_p2;
reg   [10:0] lineBuffer_addr_reg_1972;
reg   [10:0] lineBuffer_2_addr_reg_1978;
wire   [0:0] cmp161_i_fu_606_p2;
reg   [0:0] cmp161_i_reg_1984;
wire   [0:0] icmp_ln1014_fu_628_p2;
reg   [0:0] icmp_ln1014_reg_2000;
reg   [0:0] icmp_ln1014_reg_2000_pp0_iter1_reg;
reg   [0:0] icmp_ln1014_reg_2000_pp0_iter2_reg;
wire   [0:0] and_ln1052_fu_640_p2;
reg   [0:0] and_ln1052_reg_2007_pp0_iter1_reg;
reg   [9:0] p_0_0_0116317821793_i_load_reg_2011;
reg   [9:0] p_0_0_0116217841795_i_load_reg_2017;
reg   [9:0] p_0_0_0116117861797_i_load_reg_2023;
reg   [9:0] right_3_reg_2029;
reg   [9:0] right_4_reg_2034;
reg   [9:0] right_5_reg_2039;
reg   [9:0] p_0_0_01185_217761805_i_load_reg_2044;
reg   [9:0] p_0_0_01184_217781807_i_load_reg_2050;
reg   [9:0] p_0_0_01183_217801809_i_load_reg_2056;
reg   [9:0] p_0_0_0_0_011551706_i_load_reg_2062;
reg   [9:0] p_0_1_0_0_011561709_i_load_reg_2068;
reg   [9:0] p_0_2_0_0_011571712_i_load_reg_2074;
wire   [9:0] select_ln957_3_fu_792_p3;
wire   [9:0] select_ln957_4_fu_799_p3;
wire   [9:0] select_ln957_5_fu_806_p3;
wire   [9:0] select_ln957_6_fu_813_p3;
wire   [9:0] select_ln957_7_fu_820_p3;
wire   [9:0] select_ln957_8_fu_827_p3;
wire   [9:0] select_ln957_9_fu_834_p3;
wire   [9:0] select_ln957_10_fu_841_p3;
wire   [9:0] select_ln957_11_fu_848_p3;
wire   [13:0] r_2_fu_1634_p2;
reg   [13:0] r_2_reg_2125;
wire   [13:0] b_2_fu_1652_p2;
reg   [13:0] b_2_reg_2130;
reg   [0:0] tmp_22_reg_2136;
reg   [3:0] tmp_23_reg_2142;
reg   [3:0] tmp_25_reg_2147;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [10:0] lineBuffer_2_address0;
wire   [10:0] lineBuffer_2_address1;
wire   [29:0] lineBuffer_2_q1;
wire   [10:0] lineBuffer_address0;
wire   [10:0] lineBuffer_address1;
wire   [29:0] lineBuffer_q1;
reg   [9:0] ap_phi_mux_p_0_0_01183_21780_ph_i_phi_fu_375_p4;
wire   [9:0] ap_phi_reg_pp0_iter1_p_0_0_01183_21780_ph_i_reg_372;
wire   [9:0] tmp_1_i2_fu_706_p4;
reg   [9:0] ap_phi_mux_p_0_0_01184_21778_ph_i_phi_fu_384_p4;
wire   [9:0] ap_phi_reg_pp0_iter1_p_0_0_01184_21778_ph_i_reg_381;
wire   [9:0] tmp_i1_fu_695_p4;
reg   [9:0] ap_phi_mux_p_0_0_01185_21776_ph_i_phi_fu_393_p4;
wire   [9:0] trunc_ln913_fu_741_p1;
wire   [9:0] ap_phi_reg_pp0_iter1_p_0_0_01185_21776_ph_i_reg_390;
wire   [9:0] trunc_ln902_fu_690_p1;
reg   [9:0] ap_phi_mux_pix_8_phi_fu_402_p4;
wire   [9:0] select_ln957_2_fu_784_p3;
wire   [9:0] ap_phi_reg_pp0_iter1_pix_8_reg_399;
reg   [9:0] ap_phi_mux_pix_7_phi_fu_412_p4;
wire   [9:0] select_ln957_1_fu_776_p3;
wire   [9:0] ap_phi_reg_pp0_iter1_pix_7_reg_409;
reg   [9:0] ap_phi_mux_pix_phi_fu_422_p4;
wire   [9:0] select_ln957_fu_768_p3;
wire   [9:0] ap_phi_reg_pp0_iter1_pix_reg_419;
wire   [9:0] ap_phi_reg_pp0_iter0_down_2_reg_429;
reg   [9:0] ap_phi_reg_pp0_iter1_down_2_reg_429;
reg   [9:0] ap_phi_reg_pp0_iter2_down_2_reg_429;
wire   [9:0] ap_phi_reg_pp0_iter0_down_1_reg_438;
reg   [9:0] ap_phi_reg_pp0_iter1_down_1_reg_438;
reg   [9:0] ap_phi_reg_pp0_iter2_down_1_reg_438;
wire   [9:0] ap_phi_reg_pp0_iter0_down_reg_447;
reg   [9:0] ap_phi_reg_pp0_iter1_down_reg_447;
reg   [9:0] ap_phi_reg_pp0_iter2_down_reg_447;
wire   [9:0] ap_phi_reg_pp0_iter0_left_2_reg_456;
reg   [9:0] ap_phi_reg_pp0_iter1_left_2_reg_456;
reg   [9:0] ap_phi_reg_pp0_iter2_left_2_reg_456;
wire   [9:0] ap_phi_reg_pp0_iter0_left_1_reg_465;
reg   [9:0] ap_phi_reg_pp0_iter1_left_1_reg_465;
reg   [9:0] ap_phi_reg_pp0_iter2_left_1_reg_465;
wire   [9:0] ap_phi_reg_pp0_iter0_left_reg_474;
reg   [9:0] ap_phi_reg_pp0_iter1_left_reg_474;
reg   [9:0] ap_phi_reg_pp0_iter2_left_reg_474;
wire   [9:0] ap_phi_reg_pp0_iter0_up_2_reg_483;
reg   [9:0] ap_phi_reg_pp0_iter1_up_2_reg_483;
reg   [9:0] ap_phi_reg_pp0_iter2_up_2_reg_483;
wire   [9:0] ap_phi_reg_pp0_iter0_up_1_reg_492;
reg   [9:0] ap_phi_reg_pp0_iter1_up_1_reg_492;
reg   [9:0] ap_phi_reg_pp0_iter2_up_1_reg_492;
wire   [9:0] ap_phi_reg_pp0_iter0_up_reg_501;
reg   [9:0] ap_phi_reg_pp0_iter1_up_reg_501;
reg   [9:0] ap_phi_reg_pp0_iter2_up_reg_501;
wire   [63:0] zext_ln881_fu_594_p1;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [10:0] x_fu_156;
wire   [10:0] x_8_fu_584_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_z;
reg   [9:0] p_0_0_0116317821793_i_fu_160;
wire   [9:0] trunc_ln902_1_fu_717_p1;
reg   [9:0] p_0_0_0116217841795_i_fu_164;
wire   [9:0] tmp_3_i3_fu_721_p4;
reg   [9:0] p_0_0_0116117861797_i_fu_168;
wire   [9:0] tmp_4_i4_fu_731_p4;
reg   [9:0] right_fu_172;
reg   [9:0] right_1_fu_176;
reg   [9:0] right_2_fu_180;
reg   [9:0] p_0_0_01185_217761805_i_fu_184;
reg   [9:0] p_0_0_01184_217781807_i_fu_188;
reg   [9:0] p_0_0_01183_217801809_i_fu_192;
reg   [9:0] p_0_0_0_0_011551706_i_fu_196;
reg   [9:0] p_0_1_0_0_011561709_i_fu_200;
reg   [9:0] p_0_2_0_0_011571712_i_fu_204;
reg    imgRB_read_local;
wire   [29:0] or_ln1054_3_i_fu_1788_p4;
reg    ap_block_pp0_stage0_01001;
reg    imgRgb_write_local;
reg    lineBuffer_ce1_local;
reg    lineBuffer_we0_local;
reg    lineBuffer_ce0_local;
reg    lineBuffer_2_ce1_local;
reg    lineBuffer_2_we0_local;
wire   [29:0] LineBufVal_4_fu_876_p4;
reg    lineBuffer_2_ce0_local;
wire   [0:0] trunc_ln881_fu_590_p1;
wire   [0:0] xor_ln1014_fu_612_p2;
wire   [0:0] xor_ln1014_1_fu_618_p2;
wire   [14:0] zext_ln1014_fu_624_p1;
wire   [0:0] icmp_ln1052_fu_634_p2;
wire   [9:0] PixBufVal_4_fu_855_p3;
wire   [9:0] PixBufVal_3_fu_862_p3;
wire   [9:0] PixBufVal_fu_869_p3;
wire   [10:0] zext_ln1023_fu_956_p1;
wire   [10:0] zext_ln1023_1_fu_960_p1;
wire   [10:0] sub_ln1023_fu_964_p2;
wire   [9:0] trunc_ln61_fu_970_p1;
wire   [0:0] tmp_12_fu_980_p3;
wire   [9:0] sub_ln61_fu_974_p2;
wire   [10:0] zext_ln1024_fu_996_p1;
wire   [10:0] zext_ln1024_1_fu_1000_p1;
wire   [10:0] sub_ln1024_fu_1004_p2;
wire   [9:0] trunc_ln61_4_fu_1010_p1;
wire   [0:0] tmp_13_fu_1020_p3;
wire   [9:0] sub_ln61_4_fu_1014_p2;
wire   [10:0] zext_ln1025_fu_1036_p1;
wire   [10:0] zext_ln1025_1_fu_1040_p1;
wire   [10:0] sub_ln1025_fu_1044_p2;
wire   [9:0] trunc_ln61_5_fu_1050_p1;
wire   [0:0] tmp_14_fu_1060_p3;
wire   [9:0] sub_ln61_5_fu_1054_p2;
wire   [10:0] zext_ln1026_fu_1076_p1;
wire   [10:0] zext_ln1026_1_fu_1080_p1;
wire   [10:0] sub_ln1026_fu_1084_p2;
wire   [9:0] trunc_ln61_6_fu_1090_p1;
wire   [0:0] tmp_15_fu_1100_p3;
wire   [9:0] sub_ln61_6_fu_1094_p2;
wire   [10:0] zext_ln1027_fu_1116_p1;
wire   [10:0] zext_ln1027_1_fu_1120_p1;
wire   [10:0] sub_ln1027_fu_1124_p2;
wire   [9:0] trunc_ln61_7_fu_1130_p1;
wire   [0:0] tmp_16_fu_1140_p3;
wire   [9:0] sub_ln61_7_fu_1134_p2;
wire   [10:0] zext_ln1028_fu_1156_p1;
wire   [10:0] zext_ln1028_1_fu_1160_p1;
wire   [10:0] sub_ln1028_fu_1164_p2;
wire   [9:0] trunc_ln61_8_fu_1170_p1;
wire   [0:0] tmp_17_fu_1180_p3;
wire   [9:0] sub_ln61_8_fu_1174_p2;
wire   [9:0] DRh_fu_988_p3;
wire   [9:0] DGh_fu_1068_p3;
wire   [10:0] zext_ln1030_fu_1196_p1;
wire   [10:0] zext_ln1030_1_fu_1200_p1;
wire   [10:0] add_ln1030_fu_1204_p2;
wire   [9:0] DBh_fu_1148_p3;
wire   [11:0] zext_ln1030_2_fu_1210_p1;
wire   [11:0] zext_ln1030_3_fu_1214_p1;
wire   [9:0] DRv_fu_1028_p3;
wire   [9:0] DGv_fu_1108_p3;
wire   [10:0] zext_ln1030_4_fu_1224_p1;
wire   [10:0] zext_ln1030_5_fu_1228_p1;
wire   [10:0] add_ln1030_2_fu_1232_p2;
wire   [9:0] DBv_fu_1188_p3;
wire   [11:0] zext_ln1030_6_fu_1238_p1;
wire   [11:0] zext_ln1030_7_fu_1242_p1;
wire   [11:0] add_ln1030_1_fu_1218_p2;
wire   [11:0] add_ln1030_3_fu_1246_p2;
wire   [10:0] sub_ln1033_fu_1258_p2;
wire   [10:0] sub_ln1033_1_fu_1264_p2;
wire  signed [11:0] sext_ln1033_fu_1270_p1;
wire  signed [11:0] sext_ln1033_1_fu_1274_p1;
wire   [11:0] add_ln1033_fu_1278_p2;
wire   [11:0] sub_ln1033_2_fu_1292_p2;
wire   [10:0] trunc_ln1033_2_i_fu_1298_p4;
wire  signed [11:0] sext_ln1033_2_fu_1308_p1;
wire   [12:0] zext_ln1033_fu_1312_p1;
wire   [10:0] trunc_ln1033_1_i_fu_1322_p4;
wire  signed [11:0] sext_ln1033_3_fu_1332_p1;
wire   [0:0] tmp_18_fu_1284_p3;
wire   [12:0] sub_ln1033_3_fu_1316_p2;
wire   [12:0] zext_ln1033_1_fu_1336_p1;
wire   [10:0] sub_ln1034_fu_1352_p2;
wire   [10:0] sub_ln1034_1_fu_1358_p2;
wire  signed [11:0] sext_ln1034_fu_1364_p1;
wire  signed [11:0] sext_ln1034_1_fu_1368_p1;
wire   [11:0] add_ln1034_fu_1372_p2;
wire   [11:0] sub_ln1034_2_fu_1386_p2;
wire   [10:0] trunc_ln1034_2_i_fu_1392_p4;
wire  signed [11:0] sext_ln1034_2_fu_1402_p1;
wire   [12:0] zext_ln1034_fu_1406_p1;
wire   [10:0] trunc_ln1034_1_i_fu_1416_p4;
wire  signed [11:0] sext_ln1034_3_fu_1426_p1;
wire   [0:0] tmp_19_fu_1378_p3;
wire   [12:0] sub_ln1034_3_fu_1410_p2;
wire   [12:0] zext_ln1034_1_fu_1430_p1;
wire   [10:0] sub_ln1039_fu_1442_p2;
wire   [10:0] sub_ln1039_1_fu_1448_p2;
wire  signed [11:0] sext_ln1039_fu_1454_p1;
wire  signed [11:0] sext_ln1039_1_fu_1458_p1;
wire   [11:0] add_ln1039_fu_1462_p2;
wire   [11:0] sub_ln1039_2_fu_1476_p2;
wire   [10:0] trunc_ln1039_2_i_fu_1482_p4;
wire  signed [11:0] sext_ln1039_2_fu_1492_p1;
wire   [12:0] zext_ln1039_fu_1496_p1;
wire   [10:0] trunc_ln1039_1_i_fu_1506_p4;
wire  signed [11:0] sext_ln1039_3_fu_1516_p1;
wire   [0:0] tmp_20_fu_1468_p3;
wire   [12:0] sub_ln1039_3_fu_1500_p2;
wire   [12:0] zext_ln1039_1_fu_1520_p1;
wire   [10:0] sub_ln1040_fu_1532_p2;
wire   [10:0] sub_ln1040_1_fu_1538_p2;
wire  signed [11:0] sext_ln1040_fu_1544_p1;
wire  signed [11:0] sext_ln1040_1_fu_1548_p1;
wire   [11:0] add_ln1040_fu_1552_p2;
wire   [11:0] sub_ln1040_2_fu_1566_p2;
wire   [10:0] trunc_ln1040_2_i_fu_1572_p4;
wire  signed [11:0] sext_ln1040_2_fu_1582_p1;
wire   [12:0] zext_ln1040_fu_1586_p1;
wire   [10:0] trunc_ln1040_1_i_fu_1596_p4;
wire  signed [11:0] sext_ln1040_3_fu_1606_p1;
wire   [0:0] tmp_21_fu_1558_p3;
wire   [12:0] sub_ln1040_3_fu_1590_p2;
wire   [12:0] zext_ln1040_1_fu_1610_p1;
wire   [0:0] icmp_ln1030_fu_1252_p2;
wire   [12:0] select_ln1033_fu_1340_p3;
wire   [12:0] select_ln1039_fu_1524_p3;
wire   [12:0] r_2_v_v_i_fu_1622_p3;
wire   [13:0] zext_ln1033_2_fu_1348_p1;
wire  signed [13:0] r_2_v_i_fu_1630_p1;
wire   [12:0] select_ln1034_fu_1434_p3;
wire   [12:0] select_ln1040_fu_1614_p3;
wire   [12:0] b_2_v_v_i_fu_1640_p3;
wire  signed [13:0] b_2_v_i_fu_1648_p1;
wire   [0:0] xor_ln1042_fu_1697_p2;
wire   [0:0] icmp_ln1042_fu_1692_p2;
wire   [0:0] or_ln1042_fu_1710_p2;
wire   [9:0] select_ln1042_fu_1702_p3;
wire   [9:0] trunc_ln1008_1_fu_1689_p1;
wire   [0:0] icmp_ln1043_fu_1730_p2;
wire   [9:0] trunc_ln1008_fu_1686_p1;
wire   [9:0] r_3_fu_1715_p3;
wire   [0:0] tmp_24_fu_1723_p3;
wire   [0:0] xor_ln1014_2_fu_1750_p2;
wire   [0:0] and_ln1043_fu_1755_p2;
wire   [9:0] b_3_fu_1768_p6;
wire   [9:0] b_3_fu_1768_p7;
wire   [1:0] b_3_fu_1768_p8;
wire   [9:0] r_4_fu_1743_p3;
wire   [9:0] b_3_fu_1768_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_predicate_op64_load_state1;
reg    ap_enable_operation_64;
reg    ap_enable_state1_pp0_iter0_stage0;
reg    ap_predicate_op92_load_state2;
reg    ap_enable_operation_92;
reg    ap_enable_state2_pp0_iter1_stage0;
reg    ap_predicate_op105_store_state2;
reg    ap_enable_operation_105;
reg    ap_predicate_op66_load_state1;
reg    ap_enable_operation_66;
reg    ap_predicate_op96_load_state2;
reg    ap_enable_operation_96;
reg    ap_predicate_op126_store_state2;
reg    ap_enable_operation_126;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_219;
reg    ap_condition_1240;
wire  signed [1:0] b_3_fu_1768_p1;
wire   [1:0] b_3_fu_1768_p3;
wire   [1:0] b_3_fu_1768_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 x_fu_156 = 11'd0;
#0 p_0_0_0116317821793_i_fu_160 = 10'd0;
#0 p_0_0_0116217841795_i_fu_164 = 10'd0;
#0 p_0_0_0116117861797_i_fu_168 = 10'd0;
#0 right_fu_172 = 10'd0;
#0 right_1_fu_176 = 10'd0;
#0 right_2_fu_180 = 10'd0;
#0 p_0_0_01185_217761805_i_fu_184 = 10'd0;
#0 p_0_0_01184_217781807_i_fu_188 = 10'd0;
#0 p_0_0_01183_217801809_i_fu_192 = 10'd0;
#0 p_0_0_0_0_011551706_i_fu_196 = 10'd0;
#0 p_0_1_0_0_011561709_i_fu_200 = 10'd0;
#0 p_0_2_0_0_011571712_i_fu_204 = 10'd0;
#0 ap_done_reg = 1'b0;
end

design_1_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_lineBuffer_1_RAM_AUTO_1R1W #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lineBuffer_2_address0),
    .ce0(lineBuffer_2_ce0_local),
    .we0(lineBuffer_2_we0_local),
    .d0(LineBufVal_4_fu_876_p4),
    .address1(lineBuffer_2_address1),
    .ce1(lineBuffer_2_ce1_local),
    .q1(lineBuffer_2_q1)
);

design_1_v_demosaic_0_0_DebayerRatBorBatR_Pipeline_VITIS_LOOP_633_2_lineBuffer_1_RAM_AUTO_1R1W #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lineBuffer_address0),
    .ce0(lineBuffer_ce0_local),
    .we0(lineBuffer_we0_local),
    .d0(imgRB_dout),
    .address1(lineBuffer_address1),
    .ce1(lineBuffer_ce1_local),
    .q1(lineBuffer_q1)
);

(* dissolve_hierarchy = "yes" *) design_1_v_demosaic_0_0_sparsemux_7_2_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 10 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 10 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 10 ),
    .def_WIDTH( 10 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 10 ))
sparsemux_7_2_10_1_1_U172(
    .din0(pix_8_reg_399_pp0_iter2_reg),
    .din1(10'd0),
    .din2(b_3_fu_1768_p6),
    .def(b_3_fu_1768_p7),
    .sel(b_3_fu_1768_p8),
    .dout(b_3_fu_1768_p9)
);

design_1_v_demosaic_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_219)) begin
        if (((icmp_ln891_reg_1968 == 1'd0) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_1_reg_438 <= p_0_0_01184_217781807_i_fu_188;
        end else if (((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_1_reg_438 <= select_ln957_10_fu_841_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_down_1_reg_438 <= ap_phi_reg_pp0_iter1_down_1_reg_438;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_219)) begin
        if (((icmp_ln891_reg_1968 == 1'd0) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_2_reg_429 <= p_0_0_01183_217801809_i_fu_192;
        end else if (((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_2_reg_429 <= select_ln957_9_fu_834_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_down_2_reg_429 <= ap_phi_reg_pp0_iter1_down_2_reg_429;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_219)) begin
        if (((icmp_ln891_reg_1968 == 1'd0) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_reg_447 <= p_0_0_01185_217761805_i_fu_184;
        end else if (((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_down_reg_447 <= select_ln957_11_fu_848_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_down_reg_447 <= ap_phi_reg_pp0_iter1_down_reg_447;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_219)) begin
        if (((icmp_ln891_reg_1968 == 1'd0) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_1_reg_465 <= p_0_1_0_0_011561709_i_fu_200;
        end else if (((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_1_reg_465 <= select_ln957_4_fu_799_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_left_1_reg_465 <= ap_phi_reg_pp0_iter1_left_1_reg_465;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_219)) begin
        if (((icmp_ln891_reg_1968 == 1'd0) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_2_reg_456 <= p_0_2_0_0_011571712_i_fu_204;
        end else if (((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_2_reg_456 <= select_ln957_5_fu_806_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_left_2_reg_456 <= ap_phi_reg_pp0_iter1_left_2_reg_456;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_219)) begin
        if (((icmp_ln891_reg_1968 == 1'd0) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_reg_474 <= p_0_0_0_0_011551706_i_fu_196;
        end else if (((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_left_reg_474 <= select_ln957_3_fu_792_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_left_reg_474 <= ap_phi_reg_pp0_iter1_left_reg_474;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_219)) begin
        if (((icmp_ln891_reg_1968 == 1'd0) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_1_reg_492 <= p_0_0_0116217841795_i_fu_164;
        end else if (((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_1_reg_492 <= select_ln957_7_fu_820_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_up_1_reg_492 <= ap_phi_reg_pp0_iter1_up_1_reg_492;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_219)) begin
        if (((icmp_ln891_reg_1968 == 1'd0) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_2_reg_483 <= p_0_0_0116117861797_i_fu_168;
        end else if (((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_2_reg_483 <= select_ln957_6_fu_813_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_up_2_reg_483 <= ap_phi_reg_pp0_iter1_up_2_reg_483;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_219)) begin
        if (((icmp_ln891_reg_1968 == 1'd0) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_reg_501 <= p_0_0_0116317821793_i_fu_160;
        end else if (((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_up_reg_501 <= select_ln957_8_fu_827_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_up_reg_501 <= ap_phi_reg_pp0_iter1_up_reg_501;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0116117861797_i_fu_168 <= p_0_0_0116117861798_lcssa1834_i;
        end else if ((1'b1 == ap_condition_1240)) begin
            p_0_0_0116117861797_i_fu_168 <= {{lineBuffer_2_q1[29:20]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0116217841795_i_fu_164 <= p_0_0_0116217841796_lcssa1832_i;
        end else if ((1'b1 == ap_condition_1240)) begin
            p_0_0_0116217841795_i_fu_164 <= {{lineBuffer_2_q1[19:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0116317821793_i_fu_160 <= p_0_0_0116317821794_lcssa1830_i;
        end else if ((1'b1 == ap_condition_1240)) begin
            p_0_0_0116317821793_i_fu_160 <= trunc_ln902_1_fu_717_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_01183_217801809_i_fu_192 <= p_0_0_01183_217801810_lcssa1846_i;
        end else if ((1'b1 == ap_condition_1240)) begin
            p_0_0_01183_217801809_i_fu_192 <= ap_phi_mux_p_0_0_01183_21780_ph_i_phi_fu_375_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_01184_217781807_i_fu_188 <= p_0_0_01184_217781808_lcssa1844_i;
        end else if ((1'b1 == ap_condition_1240)) begin
            p_0_0_01184_217781807_i_fu_188 <= ap_phi_mux_p_0_0_01184_21778_ph_i_phi_fu_384_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_01185_217761805_i_fu_184 <= p_0_0_01185_217761806_lcssa1842_i;
        end else if ((1'b1 == ap_condition_1240)) begin
            p_0_0_01185_217761805_i_fu_184 <= ap_phi_mux_p_0_0_01185_21776_ph_i_phi_fu_393_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_0_0_0_011551706_i_fu_196 <= p_0_0_0_0_011551704_lcssa1748_i;
        end else if (((icmp_ln881_reg_1964 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_0_0_0_0_011551706_i_fu_196 <= ap_phi_mux_pix_phi_fu_422_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_1_0_0_011561709_i_fu_200 <= p_0_1_0_0_011561707_lcssa1750_i;
        end else if (((icmp_ln881_reg_1964 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_0_1_0_0_011561709_i_fu_200 <= ap_phi_mux_pix_7_phi_fu_412_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            p_0_2_0_0_011571712_i_fu_204 <= p_0_2_0_0_011571710_lcssa1752_i;
        end else if (((icmp_ln881_reg_1964 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            p_0_2_0_0_011571712_i_fu_204 <= ap_phi_mux_pix_8_phi_fu_402_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_219)) begin
        if (((icmp_ln891_reg_1968 == 1'd0) & (icmp_ln881_reg_1964 == 1'd0))) begin
            pix_7_reg_409 <= right_1_fu_176;
        end else if (((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0))) begin
            pix_7_reg_409 <= select_ln957_1_fu_776_p3;
        end else if (~(icmp_ln881_reg_1964 == 1'd1)) begin
            pix_7_reg_409 <= ap_phi_reg_pp0_iter1_pix_7_reg_409;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_219)) begin
        if (((icmp_ln891_reg_1968 == 1'd0) & (icmp_ln881_reg_1964 == 1'd0))) begin
            pix_8_reg_399 <= right_2_fu_180;
        end else if (((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0))) begin
            pix_8_reg_399 <= select_ln957_2_fu_784_p3;
        end else if (~(icmp_ln881_reg_1964 == 1'd1)) begin
            pix_8_reg_399 <= ap_phi_reg_pp0_iter1_pix_8_reg_399;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_219)) begin
        if (((icmp_ln891_reg_1968 == 1'd0) & (icmp_ln881_reg_1964 == 1'd0))) begin
            pix_reg_419 <= right_fu_172;
        end else if (((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0))) begin
            pix_reg_419 <= select_ln957_fu_768_p3;
        end else if (~(icmp_ln881_reg_1964 == 1'd1)) begin
            pix_reg_419 <= ap_phi_reg_pp0_iter1_pix_reg_419;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            right_1_fu_176 <= p_0_1_0_0_011501801_lcssa1838_i;
        end else if ((1'b1 == ap_condition_1240)) begin
            right_1_fu_176 <= {{lineBuffer_q1[19:10]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            right_2_fu_180 <= p_0_2_0_0_011511803_lcssa1840_i;
        end else if ((1'b1 == ap_condition_1240)) begin
            right_2_fu_180 <= {{lineBuffer_q1[29:20]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            right_fu_172 <= p_0_0_0_0_011491799_lcssa1836_i;
        end else if ((1'b1 == ap_condition_1240)) begin
            right_fu_172 <= trunc_ln902_fu_690_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln881_fu_578_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            x_fu_156 <= x_8_fu_584_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_156 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln1052_reg_2007 <= and_ln1052_fu_640_p2;
        and_ln1052_reg_2007_pp0_iter1_reg <= and_ln1052_reg_2007;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cmp161_i_reg_1984 <= cmp161_i_fu_606_p2;
        icmp_ln1014_reg_2000 <= icmp_ln1014_fu_628_p2;
        icmp_ln1014_reg_2000_pp0_iter1_reg <= icmp_ln1014_reg_2000;
        icmp_ln881_reg_1964 <= icmp_ln881_fu_578_p2;
        icmp_ln881_reg_1964_pp0_iter1_reg <= icmp_ln881_reg_1964;
        icmp_ln891_reg_1968 <= icmp_ln891_fu_600_p2;
        lineBuffer_2_addr_reg_1978 <= zext_ln881_fu_594_p1;
        lineBuffer_addr_reg_1972 <= zext_ln881_fu_594_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln1052_reg_2007_pp0_iter2_reg <= and_ln1052_reg_2007_pp0_iter1_reg;
        b_2_reg_2130 <= b_2_fu_1652_p2;
        icmp_ln1014_reg_2000_pp0_iter2_reg <= icmp_ln1014_reg_2000_pp0_iter1_reg;
        pix_7_reg_409_pp0_iter2_reg <= pix_7_reg_409;
        pix_8_reg_399_pp0_iter2_reg <= pix_8_reg_399;
        pix_reg_419_pp0_iter2_reg <= pix_reg_419;
        r_2_reg_2125 <= r_2_fu_1634_p2;
        tmp_22_reg_2136 <= r_2_fu_1634_p2[32'd13];
        tmp_23_reg_2142 <= {{r_2_fu_1634_p2[13:10]}};
        tmp_25_reg_2147 <= {{b_2_fu_1652_p2[13:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_down_1_reg_438 <= ap_phi_reg_pp0_iter0_down_1_reg_438;
        ap_phi_reg_pp0_iter1_down_2_reg_429 <= ap_phi_reg_pp0_iter0_down_2_reg_429;
        ap_phi_reg_pp0_iter1_down_reg_447 <= ap_phi_reg_pp0_iter0_down_reg_447;
        ap_phi_reg_pp0_iter1_left_1_reg_465 <= ap_phi_reg_pp0_iter0_left_1_reg_465;
        ap_phi_reg_pp0_iter1_left_2_reg_456 <= ap_phi_reg_pp0_iter0_left_2_reg_456;
        ap_phi_reg_pp0_iter1_left_reg_474 <= ap_phi_reg_pp0_iter0_left_reg_474;
        ap_phi_reg_pp0_iter1_up_1_reg_492 <= ap_phi_reg_pp0_iter0_up_1_reg_492;
        ap_phi_reg_pp0_iter1_up_2_reg_483 <= ap_phi_reg_pp0_iter0_up_2_reg_483;
        ap_phi_reg_pp0_iter1_up_reg_501 <= ap_phi_reg_pp0_iter0_up_reg_501;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_0116117861797_i_load_reg_2023 <= p_0_0_0116117861797_i_fu_168;
        p_0_0_0116217841795_i_load_reg_2017 <= p_0_0_0116217841795_i_fu_164;
        p_0_0_0116317821793_i_load_reg_2011 <= p_0_0_0116317821793_i_fu_160;
        p_0_0_01183_217801809_i_load_reg_2056 <= p_0_0_01183_217801809_i_fu_192;
        p_0_0_01184_217781807_i_load_reg_2050 <= p_0_0_01184_217781807_i_fu_188;
        p_0_0_01185_217761805_i_load_reg_2044 <= p_0_0_01185_217761805_i_fu_184;
        p_0_0_0_0_011551706_i_load_reg_2062 <= p_0_0_0_0_011551706_i_fu_196;
        p_0_1_0_0_011561709_i_load_reg_2068 <= p_0_1_0_0_011561709_i_fu_200;
        p_0_2_0_0_011571712_i_load_reg_2074 <= p_0_2_0_0_011571712_i_fu_204;
        right_3_reg_2029 <= right_fu_172;
        right_4_reg_2034 <= right_1_fu_176;
        right_5_reg_2039 <= right_2_fu_180;
    end
end

always @ (*) begin
    if (((icmp_ln881_fu_578_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln881_reg_1964 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0))) begin
        if ((cmp59_i_read_reg_1953 == 1'd0)) begin
            ap_phi_mux_p_0_0_01183_21780_ph_i_phi_fu_375_p4 = {{lineBuffer_q1[29:20]}};
        end else if ((cmp59_i == 1'd1)) begin
            ap_phi_mux_p_0_0_01183_21780_ph_i_phi_fu_375_p4 = {{imgRB_dout[29:20]}};
        end else begin
            ap_phi_mux_p_0_0_01183_21780_ph_i_phi_fu_375_p4 = ap_phi_reg_pp0_iter1_p_0_0_01183_21780_ph_i_reg_372;
        end
    end else begin
        ap_phi_mux_p_0_0_01183_21780_ph_i_phi_fu_375_p4 = ap_phi_reg_pp0_iter1_p_0_0_01183_21780_ph_i_reg_372;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0))) begin
        if ((cmp59_i_read_reg_1953 == 1'd0)) begin
            ap_phi_mux_p_0_0_01184_21778_ph_i_phi_fu_384_p4 = {{lineBuffer_q1[19:10]}};
        end else if ((cmp59_i == 1'd1)) begin
            ap_phi_mux_p_0_0_01184_21778_ph_i_phi_fu_384_p4 = {{imgRB_dout[19:10]}};
        end else begin
            ap_phi_mux_p_0_0_01184_21778_ph_i_phi_fu_384_p4 = ap_phi_reg_pp0_iter1_p_0_0_01184_21778_ph_i_reg_381;
        end
    end else begin
        ap_phi_mux_p_0_0_01184_21778_ph_i_phi_fu_384_p4 = ap_phi_reg_pp0_iter1_p_0_0_01184_21778_ph_i_reg_381;
    end
end

always @ (*) begin
    if (((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0))) begin
        if ((cmp59_i_read_reg_1953 == 1'd0)) begin
            ap_phi_mux_p_0_0_01185_21776_ph_i_phi_fu_393_p4 = trunc_ln902_fu_690_p1;
        end else if ((cmp59_i == 1'd1)) begin
            ap_phi_mux_p_0_0_01185_21776_ph_i_phi_fu_393_p4 = trunc_ln913_fu_741_p1;
        end else begin
            ap_phi_mux_p_0_0_01185_21776_ph_i_phi_fu_393_p4 = ap_phi_reg_pp0_iter1_p_0_0_01185_21776_ph_i_reg_390;
        end
    end else begin
        ap_phi_mux_p_0_0_01185_21776_ph_i_phi_fu_393_p4 = ap_phi_reg_pp0_iter1_p_0_0_01185_21776_ph_i_reg_390;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1964 == 1'd0)) begin
        if ((icmp_ln891_reg_1968 == 1'd0)) begin
            ap_phi_mux_pix_7_phi_fu_412_p4 = right_1_fu_176;
        end else if ((icmp_ln891_reg_1968 == 1'd1)) begin
            ap_phi_mux_pix_7_phi_fu_412_p4 = select_ln957_1_fu_776_p3;
        end else begin
            ap_phi_mux_pix_7_phi_fu_412_p4 = ap_phi_reg_pp0_iter1_pix_7_reg_409;
        end
    end else begin
        ap_phi_mux_pix_7_phi_fu_412_p4 = ap_phi_reg_pp0_iter1_pix_7_reg_409;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1964 == 1'd0)) begin
        if ((icmp_ln891_reg_1968 == 1'd0)) begin
            ap_phi_mux_pix_8_phi_fu_402_p4 = right_2_fu_180;
        end else if ((icmp_ln891_reg_1968 == 1'd1)) begin
            ap_phi_mux_pix_8_phi_fu_402_p4 = select_ln957_2_fu_784_p3;
        end else begin
            ap_phi_mux_pix_8_phi_fu_402_p4 = ap_phi_reg_pp0_iter1_pix_8_reg_399;
        end
    end else begin
        ap_phi_mux_pix_8_phi_fu_402_p4 = ap_phi_reg_pp0_iter1_pix_8_reg_399;
    end
end

always @ (*) begin
    if ((icmp_ln881_reg_1964 == 1'd0)) begin
        if ((icmp_ln891_reg_1968 == 1'd0)) begin
            ap_phi_mux_pix_phi_fu_422_p4 = right_fu_172;
        end else if ((icmp_ln891_reg_1968 == 1'd1)) begin
            ap_phi_mux_pix_phi_fu_422_p4 = select_ln957_fu_768_p3;
        end else begin
            ap_phi_mux_pix_phi_fu_422_p4 = ap_phi_reg_pp0_iter1_pix_reg_419;
        end
    end else begin
        ap_phi_mux_pix_phi_fu_422_p4 = ap_phi_reg_pp0_iter1_pix_reg_419;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_z = 11'd0;
    end else begin
        ap_sig_allocacmp_z = x_fu_156;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op101_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgRB_blk_n = imgRB_empty_n;
    end else begin
        imgRB_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op101_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imgRB_read_local = 1'b1;
    end else begin
        imgRB_read_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln1052_reg_2007_pp0_iter2_reg) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        imgRgb_blk_n = imgRgb_full_n;
    end else begin
        imgRgb_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln1052_reg_2007_pp0_iter2_reg) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        imgRgb_write_local = 1'b1;
    end else begin
        imgRgb_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_2_ce0_local = 1'b1;
    end else begin
        lineBuffer_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_2_ce1_local = 1'b1;
    end else begin
        lineBuffer_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_2_we0_local = 1'b1;
    end else begin
        lineBuffer_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_ce0_local = 1'b1;
    end else begin
        lineBuffer_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_ce1_local = 1'b1;
    end else begin
        lineBuffer_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (cmp59_i == 1'd1) & (icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lineBuffer_we0_local = 1'b1;
    end else begin
        lineBuffer_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1964_pp0_iter1_reg == 1'd1))) begin
        p_0_0_0116117861797_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116117861797_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1964_pp0_iter1_reg == 1'd1))) begin
        p_0_0_0116217841795_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116217841795_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1964_pp0_iter1_reg == 1'd1))) begin
        p_0_0_0116317821793_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116317821793_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1964_pp0_iter1_reg == 1'd1))) begin
        p_0_0_01183_217801809_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01183_217801809_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1964_pp0_iter1_reg == 1'd1))) begin
        p_0_0_01184_217781807_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01184_217781807_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1964_pp0_iter1_reg == 1'd1))) begin
        p_0_0_01185_217761805_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01185_217761805_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1964_pp0_iter1_reg == 1'd1))) begin
        p_0_0_0_0_011551706_i_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0_0_011551706_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1964_pp0_iter1_reg == 1'd1))) begin
        p_0_1_0_0_011561709_i_out_ap_vld = 1'b1;
    end else begin
        p_0_1_0_0_011561709_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1964_pp0_iter1_reg == 1'd1))) begin
        p_0_2_0_0_011571712_i_out_ap_vld = 1'b1;
    end else begin
        p_0_2_0_0_011571712_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1964_pp0_iter1_reg == 1'd1))) begin
        right_1_i_out_ap_vld = 1'b1;
    end else begin
        right_1_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1964_pp0_iter1_reg == 1'd1))) begin
        right_2_i_out_ap_vld = 1'b1;
    end else begin
        right_2_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln881_reg_1964_pp0_iter1_reg == 1'd1))) begin
        right_i_out_ap_vld = 1'b1;
    end else begin
        right_i_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DBh_fu_1148_p3 = ((tmp_16_fu_1140_p3[0:0] == 1'b1) ? sub_ln61_7_fu_1134_p2 : trunc_ln61_7_fu_1130_p1);

assign DBv_fu_1188_p3 = ((tmp_17_fu_1180_p3[0:0] == 1'b1) ? sub_ln61_8_fu_1174_p2 : trunc_ln61_8_fu_1170_p1);

assign DGh_fu_1068_p3 = ((tmp_14_fu_1060_p3[0:0] == 1'b1) ? sub_ln61_5_fu_1054_p2 : trunc_ln61_5_fu_1050_p1);

assign DGv_fu_1108_p3 = ((tmp_15_fu_1100_p3[0:0] == 1'b1) ? sub_ln61_6_fu_1094_p2 : trunc_ln61_6_fu_1090_p1);

assign DRh_fu_988_p3 = ((tmp_12_fu_980_p3[0:0] == 1'b1) ? sub_ln61_fu_974_p2 : trunc_ln61_fu_970_p1);

assign DRv_fu_1028_p3 = ((tmp_13_fu_1020_p3[0:0] == 1'b1) ? sub_ln61_4_fu_1014_p2 : trunc_ln61_4_fu_1010_p1);

assign LineBufVal_4_fu_876_p4 = {{{PixBufVal_4_fu_855_p3}, {PixBufVal_3_fu_862_p3}}, {PixBufVal_fu_869_p3}};

assign PixBufVal_3_fu_862_p3 = ((cmp203_i[0:0] == 1'b1) ? tmp_i1_fu_695_p4 : ap_phi_mux_p_0_0_01184_21778_ph_i_phi_fu_384_p4);

assign PixBufVal_4_fu_855_p3 = ((cmp203_i[0:0] == 1'b1) ? tmp_1_i2_fu_706_p4 : ap_phi_mux_p_0_0_01183_21780_ph_i_phi_fu_375_p4);

assign PixBufVal_fu_869_p3 = ((cmp203_i[0:0] == 1'b1) ? trunc_ln902_fu_690_p1 : ap_phi_mux_p_0_0_01185_21776_ph_i_phi_fu_393_p4);

assign add_ln1030_1_fu_1218_p2 = (zext_ln1030_2_fu_1210_p1 + zext_ln1030_3_fu_1214_p1);

assign add_ln1030_2_fu_1232_p2 = (zext_ln1030_4_fu_1224_p1 + zext_ln1030_5_fu_1228_p1);

assign add_ln1030_3_fu_1246_p2 = (zext_ln1030_6_fu_1238_p1 + zext_ln1030_7_fu_1242_p1);

assign add_ln1030_fu_1204_p2 = (zext_ln1030_fu_1196_p1 + zext_ln1030_1_fu_1200_p1);

assign add_ln1033_fu_1278_p2 = ($signed(sext_ln1033_fu_1270_p1) + $signed(sext_ln1033_1_fu_1274_p1));

assign add_ln1034_fu_1372_p2 = ($signed(sext_ln1034_fu_1364_p1) + $signed(sext_ln1034_1_fu_1368_p1));

assign add_ln1039_fu_1462_p2 = ($signed(sext_ln1039_fu_1454_p1) + $signed(sext_ln1039_1_fu_1458_p1));

assign add_ln1040_fu_1552_p2 = ($signed(sext_ln1040_fu_1544_p1) + $signed(sext_ln1040_1_fu_1548_p1));

assign and_ln1043_fu_1755_p2 = (xor_ln1014_2_fu_1750_p2 & tmp_24_fu_1723_p3);

assign and_ln1052_fu_640_p2 = (icmp_ln1052_fu_634_p2 & cmp203_i);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op101_read_state2 == 1'b1) & (imgRB_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((imgRgb_full_n == 1'b0) & (1'd1 == and_ln1052_reg_2007_pp0_iter2_reg));
end

always @ (*) begin
    ap_condition_1240 = ((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_219 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

always @ (*) begin
    ap_enable_operation_105 = (ap_predicate_op105_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_126 = (ap_predicate_op126_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_64 = (ap_predicate_op64_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_66 = (ap_predicate_op66_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_92 = (ap_predicate_op92_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_96 = (ap_predicate_op96_load_state2 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state1_pp0_iter0_stage0 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_down_1_reg_438 = 'bx;

assign ap_phi_reg_pp0_iter0_down_2_reg_429 = 'bx;

assign ap_phi_reg_pp0_iter0_down_reg_447 = 'bx;

assign ap_phi_reg_pp0_iter0_left_1_reg_465 = 'bx;

assign ap_phi_reg_pp0_iter0_left_2_reg_456 = 'bx;

assign ap_phi_reg_pp0_iter0_left_reg_474 = 'bx;

assign ap_phi_reg_pp0_iter0_up_1_reg_492 = 'bx;

assign ap_phi_reg_pp0_iter0_up_2_reg_483 = 'bx;

assign ap_phi_reg_pp0_iter0_up_reg_501 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_01183_21780_ph_i_reg_372 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_01184_21778_ph_i_reg_381 = 'bx;

assign ap_phi_reg_pp0_iter1_p_0_0_01185_21776_ph_i_reg_390 = 'bx;

assign ap_phi_reg_pp0_iter1_pix_7_reg_409 = 'bx;

assign ap_phi_reg_pp0_iter1_pix_8_reg_399 = 'bx;

assign ap_phi_reg_pp0_iter1_pix_reg_419 = 'bx;

always @ (*) begin
    ap_predicate_op101_read_state2 = ((cmp59_i == 1'd1) & (icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0));
end

always @ (*) begin
    ap_predicate_op105_store_state2 = ((cmp59_i == 1'd1) & (icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0));
end

always @ (*) begin
    ap_predicate_op126_store_state2 = ((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0));
end

always @ (*) begin
    ap_predicate_op64_load_state1 = ((icmp_ln881_fu_578_p2 == 1'd0) & (icmp_ln891_fu_600_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op66_load_state1 = ((icmp_ln881_fu_578_p2 == 1'd0) & (icmp_ln891_fu_600_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op92_load_state2 = ((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0));
end

always @ (*) begin
    ap_predicate_op96_load_state2 = ((icmp_ln891_reg_1968 == 1'd1) & (icmp_ln881_reg_1964 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign b_2_fu_1652_p2 = ($signed(zext_ln1033_2_fu_1348_p1) - $signed(b_2_v_i_fu_1648_p1));

assign b_2_v_i_fu_1648_p1 = $signed(b_2_v_v_i_fu_1640_p3);

assign b_2_v_v_i_fu_1640_p3 = ((icmp_ln1030_fu_1252_p2[0:0] == 1'b1) ? select_ln1034_fu_1434_p3 : select_ln1040_fu_1614_p3);

assign b_3_fu_1768_p6 = ((icmp_ln1043_fu_1730_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln1008_fu_1686_p1);

assign b_3_fu_1768_p7 = 'bx;

assign b_3_fu_1768_p8 = {{icmp_ln1014_reg_2000_pp0_iter2_reg}, {and_ln1043_fu_1755_p2}};

assign cmp161_i_fu_606_p2 = ((ap_sig_allocacmp_z == 11'd0) ? 1'b1 : 1'b0);

assign cmp59_i_read_reg_1953 = cmp59_i;

assign icmp_ln1014_fu_628_p2 = ((xor_i == zext_ln1014_fu_624_p1) ? 1'b1 : 1'b0);

assign icmp_ln1030_fu_1252_p2 = ((add_ln1030_1_fu_1218_p2 < add_ln1030_3_fu_1246_p2) ? 1'b1 : 1'b0);

assign icmp_ln1042_fu_1692_p2 = (($signed(tmp_23_reg_2142) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1043_fu_1730_p2 = (($signed(tmp_25_reg_2147) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1052_fu_634_p2 = ((ap_sig_allocacmp_z != 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln881_fu_578_p2 = ((ap_sig_allocacmp_z == loopWidth_i) ? 1'b1 : 1'b0);

assign icmp_ln891_fu_600_p2 = ((ap_sig_allocacmp_z < empty) ? 1'b1 : 1'b0);

assign imgRB_read = imgRB_read_local;

assign imgRgb_din = or_ln1054_3_i_fu_1788_p4;

assign imgRgb_write = imgRgb_write_local;

assign lineBuffer_2_address0 = lineBuffer_2_addr_reg_1978;

assign lineBuffer_2_address1 = zext_ln881_fu_594_p1;

assign lineBuffer_address0 = lineBuffer_addr_reg_1972;

assign lineBuffer_address1 = zext_ln881_fu_594_p1;

assign or_ln1042_fu_1710_p2 = (tmp_22_reg_2136 | icmp_ln1042_fu_1692_p2);

assign or_ln1054_3_i_fu_1788_p4 = {{{r_4_fu_1743_p3}, {b_3_fu_1768_p9}}, {pix_7_reg_409_pp0_iter2_reg}};

assign p_0_0_0116117861797_i_out = p_0_0_0116117861797_i_load_reg_2023;

assign p_0_0_0116217841795_i_out = p_0_0_0116217841795_i_load_reg_2017;

assign p_0_0_0116317821793_i_out = p_0_0_0116317821793_i_load_reg_2011;

assign p_0_0_01183_217801809_i_out = p_0_0_01183_217801809_i_load_reg_2056;

assign p_0_0_01184_217781807_i_out = p_0_0_01184_217781807_i_load_reg_2050;

assign p_0_0_01185_217761805_i_out = p_0_0_01185_217761805_i_load_reg_2044;

assign p_0_0_0_0_011551706_i_out = p_0_0_0_0_011551706_i_load_reg_2062;

assign p_0_1_0_0_011561709_i_out = p_0_1_0_0_011561709_i_load_reg_2068;

assign p_0_2_0_0_011571712_i_out = p_0_2_0_0_011571712_i_load_reg_2074;

assign r_2_fu_1634_p2 = ($signed(zext_ln1033_2_fu_1348_p1) - $signed(r_2_v_i_fu_1630_p1));

assign r_2_v_i_fu_1630_p1 = $signed(r_2_v_v_i_fu_1622_p3);

assign r_2_v_v_i_fu_1622_p3 = ((icmp_ln1030_fu_1252_p2[0:0] == 1'b1) ? select_ln1033_fu_1340_p3 : select_ln1039_fu_1524_p3);

assign r_3_fu_1715_p3 = ((or_ln1042_fu_1710_p2[0:0] == 1'b1) ? select_ln1042_fu_1702_p3 : trunc_ln1008_1_fu_1689_p1);

assign r_4_fu_1743_p3 = ((icmp_ln1014_reg_2000_pp0_iter2_reg[0:0] == 1'b1) ? pix_reg_419_pp0_iter2_reg : r_3_fu_1715_p3);

assign right_1_i_out = right_4_reg_2034;

assign right_2_i_out = right_5_reg_2039;

assign right_i_out = right_3_reg_2029;

assign select_ln1033_fu_1340_p3 = ((tmp_18_fu_1284_p3[0:0] == 1'b1) ? sub_ln1033_3_fu_1316_p2 : zext_ln1033_1_fu_1336_p1);

assign select_ln1034_fu_1434_p3 = ((tmp_19_fu_1378_p3[0:0] == 1'b1) ? sub_ln1034_3_fu_1410_p2 : zext_ln1034_1_fu_1430_p1);

assign select_ln1039_fu_1524_p3 = ((tmp_20_fu_1468_p3[0:0] == 1'b1) ? sub_ln1039_3_fu_1500_p2 : zext_ln1039_1_fu_1520_p1);

assign select_ln1040_fu_1614_p3 = ((tmp_21_fu_1558_p3[0:0] == 1'b1) ? sub_ln1040_3_fu_1590_p2 : zext_ln1040_1_fu_1610_p1);

assign select_ln1042_fu_1702_p3 = ((xor_ln1042_fu_1697_p2[0:0] == 1'b1) ? 10'd1023 : 10'd0);

assign select_ln957_10_fu_841_p3 = ((cmp161_i_reg_1984[0:0] == 1'b1) ? ap_phi_mux_p_0_0_01184_21778_ph_i_phi_fu_384_p4 : p_0_0_01184_217781807_i_fu_188);

assign select_ln957_11_fu_848_p3 = ((cmp161_i_reg_1984[0:0] == 1'b1) ? ap_phi_mux_p_0_0_01185_21776_ph_i_phi_fu_393_p4 : p_0_0_01185_217761805_i_fu_184);

assign select_ln957_1_fu_776_p3 = ((cmp161_i_reg_1984[0:0] == 1'b1) ? tmp_i1_fu_695_p4 : right_1_fu_176);

assign select_ln957_2_fu_784_p3 = ((cmp161_i_reg_1984[0:0] == 1'b1) ? tmp_1_i2_fu_706_p4 : right_2_fu_180);

assign select_ln957_3_fu_792_p3 = ((cmp161_i_reg_1984[0:0] == 1'b1) ? trunc_ln902_fu_690_p1 : p_0_0_0_0_011551706_i_fu_196);

assign select_ln957_4_fu_799_p3 = ((cmp161_i_reg_1984[0:0] == 1'b1) ? tmp_i1_fu_695_p4 : p_0_1_0_0_011561709_i_fu_200);

assign select_ln957_5_fu_806_p3 = ((cmp161_i_reg_1984[0:0] == 1'b1) ? tmp_1_i2_fu_706_p4 : p_0_2_0_0_011571712_i_fu_204);

assign select_ln957_6_fu_813_p3 = ((cmp161_i_reg_1984[0:0] == 1'b1) ? tmp_4_i4_fu_731_p4 : p_0_0_0116117861797_i_fu_168);

assign select_ln957_7_fu_820_p3 = ((cmp161_i_reg_1984[0:0] == 1'b1) ? tmp_3_i3_fu_721_p4 : p_0_0_0116217841795_i_fu_164);

assign select_ln957_8_fu_827_p3 = ((cmp161_i_reg_1984[0:0] == 1'b1) ? trunc_ln902_1_fu_717_p1 : p_0_0_0116317821793_i_fu_160);

assign select_ln957_9_fu_834_p3 = ((cmp161_i_reg_1984[0:0] == 1'b1) ? ap_phi_mux_p_0_0_01183_21780_ph_i_phi_fu_375_p4 : p_0_0_01183_217801809_i_fu_192);

assign select_ln957_fu_768_p3 = ((cmp161_i_reg_1984[0:0] == 1'b1) ? trunc_ln902_fu_690_p1 : right_fu_172);

assign sext_ln1033_1_fu_1274_p1 = $signed(sub_ln1033_1_fu_1264_p2);

assign sext_ln1033_2_fu_1308_p1 = $signed(trunc_ln1033_2_i_fu_1298_p4);

assign sext_ln1033_3_fu_1332_p1 = $signed(trunc_ln1033_1_i_fu_1322_p4);

assign sext_ln1033_fu_1270_p1 = $signed(sub_ln1033_fu_1258_p2);

assign sext_ln1034_1_fu_1368_p1 = $signed(sub_ln1034_1_fu_1358_p2);

assign sext_ln1034_2_fu_1402_p1 = $signed(trunc_ln1034_2_i_fu_1392_p4);

assign sext_ln1034_3_fu_1426_p1 = $signed(trunc_ln1034_1_i_fu_1416_p4);

assign sext_ln1034_fu_1364_p1 = $signed(sub_ln1034_fu_1352_p2);

assign sext_ln1039_1_fu_1458_p1 = $signed(sub_ln1039_1_fu_1448_p2);

assign sext_ln1039_2_fu_1492_p1 = $signed(trunc_ln1039_2_i_fu_1482_p4);

assign sext_ln1039_3_fu_1516_p1 = $signed(trunc_ln1039_1_i_fu_1506_p4);

assign sext_ln1039_fu_1454_p1 = $signed(sub_ln1039_fu_1442_p2);

assign sext_ln1040_1_fu_1548_p1 = $signed(sub_ln1040_1_fu_1538_p2);

assign sext_ln1040_2_fu_1582_p1 = $signed(trunc_ln1040_2_i_fu_1572_p4);

assign sext_ln1040_3_fu_1606_p1 = $signed(trunc_ln1040_1_i_fu_1596_p4);

assign sext_ln1040_fu_1544_p1 = $signed(sub_ln1040_fu_1532_p2);

assign sub_ln1023_fu_964_p2 = (zext_ln1023_fu_956_p1 - zext_ln1023_1_fu_960_p1);

assign sub_ln1024_fu_1004_p2 = (zext_ln1024_fu_996_p1 - zext_ln1024_1_fu_1000_p1);

assign sub_ln1025_fu_1044_p2 = (zext_ln1025_fu_1036_p1 - zext_ln1025_1_fu_1040_p1);

assign sub_ln1026_fu_1084_p2 = (zext_ln1026_fu_1076_p1 - zext_ln1026_1_fu_1080_p1);

assign sub_ln1027_fu_1124_p2 = (zext_ln1027_fu_1116_p1 - zext_ln1027_1_fu_1120_p1);

assign sub_ln1028_fu_1164_p2 = (zext_ln1028_fu_1156_p1 - zext_ln1028_1_fu_1160_p1);

assign sub_ln1033_1_fu_1264_p2 = (zext_ln1025_1_fu_1040_p1 - zext_ln1023_1_fu_960_p1);

assign sub_ln1033_2_fu_1292_p2 = (12'd0 - add_ln1033_fu_1278_p2);

assign sub_ln1033_3_fu_1316_p2 = (13'd0 - zext_ln1033_fu_1312_p1);

assign sub_ln1033_fu_1258_p2 = (zext_ln1025_fu_1036_p1 - zext_ln1023_fu_956_p1);

assign sub_ln1034_1_fu_1358_p2 = (zext_ln1025_1_fu_1040_p1 - zext_ln1027_1_fu_1120_p1);

assign sub_ln1034_2_fu_1386_p2 = (12'd0 - add_ln1034_fu_1372_p2);

assign sub_ln1034_3_fu_1410_p2 = (13'd0 - zext_ln1034_fu_1406_p1);

assign sub_ln1034_fu_1352_p2 = (zext_ln1025_fu_1036_p1 - zext_ln1027_fu_1116_p1);

assign sub_ln1039_1_fu_1448_p2 = (zext_ln1026_1_fu_1080_p1 - zext_ln1024_1_fu_1000_p1);

assign sub_ln1039_2_fu_1476_p2 = (12'd0 - add_ln1039_fu_1462_p2);

assign sub_ln1039_3_fu_1500_p2 = (13'd0 - zext_ln1039_fu_1496_p1);

assign sub_ln1039_fu_1442_p2 = (zext_ln1026_fu_1076_p1 - zext_ln1024_fu_996_p1);

assign sub_ln1040_1_fu_1538_p2 = (zext_ln1026_1_fu_1080_p1 - zext_ln1028_1_fu_1160_p1);

assign sub_ln1040_2_fu_1566_p2 = (12'd0 - add_ln1040_fu_1552_p2);

assign sub_ln1040_3_fu_1590_p2 = (13'd0 - zext_ln1040_fu_1586_p1);

assign sub_ln1040_fu_1532_p2 = (zext_ln1026_fu_1076_p1 - zext_ln1028_fu_1156_p1);

assign sub_ln61_4_fu_1014_p2 = (10'd0 - trunc_ln61_4_fu_1010_p1);

assign sub_ln61_5_fu_1054_p2 = (10'd0 - trunc_ln61_5_fu_1050_p1);

assign sub_ln61_6_fu_1094_p2 = (10'd0 - trunc_ln61_6_fu_1090_p1);

assign sub_ln61_7_fu_1134_p2 = (10'd0 - trunc_ln61_7_fu_1130_p1);

assign sub_ln61_8_fu_1174_p2 = (10'd0 - trunc_ln61_8_fu_1170_p1);

assign sub_ln61_fu_974_p2 = (10'd0 - trunc_ln61_fu_970_p1);

assign tmp_12_fu_980_p3 = sub_ln1023_fu_964_p2[32'd10];

assign tmp_13_fu_1020_p3 = sub_ln1024_fu_1004_p2[32'd10];

assign tmp_14_fu_1060_p3 = sub_ln1025_fu_1044_p2[32'd10];

assign tmp_15_fu_1100_p3 = sub_ln1026_fu_1084_p2[32'd10];

assign tmp_16_fu_1140_p3 = sub_ln1027_fu_1124_p2[32'd10];

assign tmp_17_fu_1180_p3 = sub_ln1028_fu_1164_p2[32'd10];

assign tmp_18_fu_1284_p3 = add_ln1033_fu_1278_p2[32'd11];

assign tmp_19_fu_1378_p3 = add_ln1034_fu_1372_p2[32'd11];

assign tmp_1_i2_fu_706_p4 = {{lineBuffer_q1[29:20]}};

assign tmp_20_fu_1468_p3 = add_ln1039_fu_1462_p2[32'd11];

assign tmp_21_fu_1558_p3 = add_ln1040_fu_1552_p2[32'd11];

assign tmp_24_fu_1723_p3 = b_2_reg_2130[32'd13];

assign tmp_3_i3_fu_721_p4 = {{lineBuffer_2_q1[19:10]}};

assign tmp_4_i4_fu_731_p4 = {{lineBuffer_2_q1[29:20]}};

assign tmp_i1_fu_695_p4 = {{lineBuffer_q1[19:10]}};

assign trunc_ln1008_1_fu_1689_p1 = r_2_reg_2125[9:0];

assign trunc_ln1008_fu_1686_p1 = b_2_reg_2130[9:0];

assign trunc_ln1033_1_i_fu_1322_p4 = {{add_ln1033_fu_1278_p2[11:1]}};

assign trunc_ln1033_2_i_fu_1298_p4 = {{sub_ln1033_2_fu_1292_p2[11:1]}};

assign trunc_ln1034_1_i_fu_1416_p4 = {{add_ln1034_fu_1372_p2[11:1]}};

assign trunc_ln1034_2_i_fu_1392_p4 = {{sub_ln1034_2_fu_1386_p2[11:1]}};

assign trunc_ln1039_1_i_fu_1506_p4 = {{add_ln1039_fu_1462_p2[11:1]}};

assign trunc_ln1039_2_i_fu_1482_p4 = {{sub_ln1039_2_fu_1476_p2[11:1]}};

assign trunc_ln1040_1_i_fu_1596_p4 = {{add_ln1040_fu_1552_p2[11:1]}};

assign trunc_ln1040_2_i_fu_1572_p4 = {{sub_ln1040_2_fu_1566_p2[11:1]}};

assign trunc_ln61_4_fu_1010_p1 = sub_ln1024_fu_1004_p2[9:0];

assign trunc_ln61_5_fu_1050_p1 = sub_ln1025_fu_1044_p2[9:0];

assign trunc_ln61_6_fu_1090_p1 = sub_ln1026_fu_1084_p2[9:0];

assign trunc_ln61_7_fu_1130_p1 = sub_ln1027_fu_1124_p2[9:0];

assign trunc_ln61_8_fu_1170_p1 = sub_ln1028_fu_1164_p2[9:0];

assign trunc_ln61_fu_970_p1 = sub_ln1023_fu_964_p2[9:0];

assign trunc_ln881_fu_590_p1 = ap_sig_allocacmp_z[0:0];

assign trunc_ln902_1_fu_717_p1 = lineBuffer_2_q1[9:0];

assign trunc_ln902_fu_690_p1 = lineBuffer_q1[9:0];

assign trunc_ln913_fu_741_p1 = imgRB_dout[9:0];

assign x_8_fu_584_p2 = (ap_sig_allocacmp_z + 11'd1);

assign xor_ln1014_1_fu_618_p2 = (xor_ln1014_fu_612_p2 ^ 1'd1);

assign xor_ln1014_2_fu_1750_p2 = (icmp_ln1014_reg_2000_pp0_iter2_reg ^ 1'd1);

assign xor_ln1014_fu_612_p2 = (trunc_ln881_fu_590_p1 ^ empty_52);

assign xor_ln1042_fu_1697_p2 = (tmp_22_reg_2136 ^ 1'd1);

assign zext_ln1014_fu_624_p1 = xor_ln1014_1_fu_618_p2;

assign zext_ln1023_1_fu_960_p1 = right_fu_172;

assign zext_ln1023_fu_956_p1 = ap_phi_reg_pp0_iter2_left_reg_474;

assign zext_ln1024_1_fu_1000_p1 = ap_phi_reg_pp0_iter2_down_reg_447;

assign zext_ln1024_fu_996_p1 = ap_phi_reg_pp0_iter2_up_reg_501;

assign zext_ln1025_1_fu_1040_p1 = right_1_fu_176;

assign zext_ln1025_fu_1036_p1 = ap_phi_reg_pp0_iter2_left_1_reg_465;

assign zext_ln1026_1_fu_1080_p1 = ap_phi_reg_pp0_iter2_down_1_reg_438;

assign zext_ln1026_fu_1076_p1 = ap_phi_reg_pp0_iter2_up_1_reg_492;

assign zext_ln1027_1_fu_1120_p1 = right_2_fu_180;

assign zext_ln1027_fu_1116_p1 = ap_phi_reg_pp0_iter2_left_2_reg_456;

assign zext_ln1028_1_fu_1160_p1 = ap_phi_reg_pp0_iter2_down_2_reg_429;

assign zext_ln1028_fu_1156_p1 = ap_phi_reg_pp0_iter2_up_2_reg_483;

assign zext_ln1030_1_fu_1200_p1 = DGh_fu_1068_p3;

assign zext_ln1030_2_fu_1210_p1 = add_ln1030_fu_1204_p2;

assign zext_ln1030_3_fu_1214_p1 = DBh_fu_1148_p3;

assign zext_ln1030_4_fu_1224_p1 = DRv_fu_1028_p3;

assign zext_ln1030_5_fu_1228_p1 = DGv_fu_1108_p3;

assign zext_ln1030_6_fu_1238_p1 = add_ln1030_2_fu_1232_p2;

assign zext_ln1030_7_fu_1242_p1 = DBv_fu_1188_p3;

assign zext_ln1030_fu_1196_p1 = DRh_fu_988_p3;

assign zext_ln1033_1_fu_1336_p1 = $unsigned(sext_ln1033_3_fu_1332_p1);

assign zext_ln1033_2_fu_1348_p1 = pix_7_reg_409;

assign zext_ln1033_fu_1312_p1 = $unsigned(sext_ln1033_2_fu_1308_p1);

assign zext_ln1034_1_fu_1430_p1 = $unsigned(sext_ln1034_3_fu_1426_p1);

assign zext_ln1034_fu_1406_p1 = $unsigned(sext_ln1034_2_fu_1402_p1);

assign zext_ln1039_1_fu_1520_p1 = $unsigned(sext_ln1039_3_fu_1516_p1);

assign zext_ln1039_fu_1496_p1 = $unsigned(sext_ln1039_2_fu_1492_p1);

assign zext_ln1040_1_fu_1610_p1 = $unsigned(sext_ln1040_3_fu_1606_p1);

assign zext_ln1040_fu_1586_p1 = $unsigned(sext_ln1040_2_fu_1582_p1);

assign zext_ln881_fu_594_p1 = x_8_fu_584_p2;

endmodule //design_1_v_demosaic_0_0_DebayerRandBatG_Pipeline_VITIS_LOOP_881_2
