# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: e:/ultra96v2_imx219_to_displayport-master/ultra96v2_imx219_to_displayport-master/fpga/bd/myproj/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_d10d_r_sync_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_r_sync_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/ultra96v2_imx219_to_displayport-master/ultra96v2_imx219_to_displayport-master/fpga/bd/myproj/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_d10d_r_sync_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_r_sync_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/ultra96v2_imx219_to_displayport-master/ultra96v2_imx219_to_displayport-master/fpga/bd/myproj/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_d10d_r_sync_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_r_sync_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/ultra96v2_imx219_to_displayport-master/ultra96v2_imx219_to_displayport-master/fpga/bd/myproj/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_d10d_r_sync_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_r_sync_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/ultra96v2_imx219_to_displayport-master/ultra96v2_imx219_to_displayport-master/fpga/bd/myproj/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_d10d_r_sync_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_r_sync_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/ultra96v2_imx219_to_displayport-master/ultra96v2_imx219_to_displayport-master/fpga/bd/myproj/project_2/project_2.gen/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_0/bd_d10d_r_sync_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_d10d_r_sync_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
