<AutoPilot:project xmlns:AutoPilot="com.autoesl.autopilot.project" projectType="C/C++" top="v_gamma_lut" name="prj" ideType="classic">
    <solutions>
        <solution name="sol" status=""/>
    </solutions>
    <files>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls/hls_video_undistort.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls/hls_video_types.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls/hls_video_stereobm.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls/hls_video_mem.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls/hls_video_io.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls/hls_video_imgproc.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls/hls_video_imgbase.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls/hls_video_hough.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls/hls_video_histogram.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls/hls_video_harris.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls/hls_video_haar.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls/hls_video_fast.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls/hls_video_core.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls/hls_video_arithm.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls/hls_axi_io.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls_opencv.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls_video.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/v_gamma_lut.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/v_gamma_lut.cpp" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
        <file name="../../project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/v_gamma_lut_config.h" sc="0" tb="false" cflags="-If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src/hls -If:/Projects/Vivado/project_Scratch/project_Scratch.gen/sources_1/bd/design_1/ip/design_1_v_gamma_lut_0_0/src" csimflags="" blackbox="false"/>
    </files>
</AutoPilot:project>

